export const ARGENTINA_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'ARG-1', name: 'San Lorenzo', badge: 'https://img.sofascore.com/api/v1/team/3201/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-2', name: 'Boca Juniors', badge: 'https://img.sofascore.com/api/v1/team/3202/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-3', name: 'Belgrano', badge: 'https://img.sofascore.com/api/v1/team/3203/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-4', name: 'Unión de Santa Fe', badge: 'https://img.sofascore.com/api/v1/team/3204/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-5', name: 'Gimnasia y Esgrima', badge: 'https://img.sofascore.com/api/v1/team/3205/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-6', name: 'Estudiantes', badge: 'https://img.sofascore.com/api/v1/team/3206/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-7', name: 'Colón', badge: 'https://img.sofascore.com/api/v1/team/3207/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-8', name: 'Vélez Sarsfield', badge: 'https://img.sofascore.com/api/v1/team/3208/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-9', name: 'Independiente', badge: 'https://img.sofascore.com/api/v1/team/3209/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-10', name: 'Talleres', badge: 'https://img.sofascore.com/api/v1/team/3210/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-11', name: 'River Plate', badge: 'https://img.sofascore.com/api/v1/team/3211/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-12', name: 'Newell\'s', badge: 'https://img.sofascore.com/api/v1/team/3212/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-13', name: 'Racing', badge: 'https://img.sofascore.com/api/v1/team/3215/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-14', name: 'Argentinos Jrs.', badge: 'https://img.sofascore.com/api/v1/team/3216/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-15', name: 'Rosario Central', badge: 'https://img.sofascore.com/api/v1/team/3217/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-16', name: 'Lanús', badge: 'https://img.sofascore.com/api/v1/team/3218/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-17', name: 'Banfield', badge: 'https://img.sofascore.com/api/v1/team/3219/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-18', name: 'Arsenal de Sarandí', badge: 'https://img.sofascore.com/api/v1/team/3221/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-19', name: 'Godoy Cruz', badge: 'https://img.sofascore.com/api/v1/team/6074/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-20', name: 'Tigre', badge: 'https://img.sofascore.com/api/v1/team/7628/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-21', name: 'Huracán', badge: 'https://img.sofascore.com/api/v1/team/7629/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-22', name: 'San Martín', badge: 'https://img.sofascore.com/api/v1/team/7772/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-23', name: 'Platense', badge: 'https://img.sofascore.com/api/v1/team/36837/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-24', name: 'Defensa y Justicia', badge: 'https://img.sofascore.com/api/v1/team/36839/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-25', name: 'Sarmiento', badge: 'https://img.sofascore.com/api/v1/team/42338/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-26', name: 'Barracas', badge: 'https://img.sofascore.com/api/v1/team/65668/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-27', name: 'Central Córdoba', badge: 'https://img.sofascore.com/api/v1/team/65676/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-28', name: 'Everton (LP)', badge: 'https://img.sofascore.com/api/v1/team/260041/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-29', name: 'Instituto', badge: 'https://img.sofascore.com/api/v1/team/4937/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-30', name: 'Gimnasia Mendoza', badge: 'https://img.sofascore.com/api/v1/team/188441/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-31', name: 'Dep. Riestra', badge: 'https://img.sofascore.com/api/v1/team/189723/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-32', name: 'Ind. Rivadavia', badge: 'https://img.sofascore.com/api/v1/team/36842/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-33', name: 'Atlético Tucumán', badge: 'https://img.sofascore.com/api/v1/team/36833/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-34', name: 'Aldosivi', badge: 'https://img.sofascore.com/api/v1/team/36836/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
  { id: 'ARG-35', name: 'Estudiantes de Río Cuarto', badge: 'https://img.sofascore.com/api/v1/team/266694/image', country: 'ARG', type: TeamType.CLUB, tags: [] },
];
