export const BRAZIL_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'BRA-1', name: 'Cruzeiro', badge: 'https://img.sofascore.com/api/v1/team/1954/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-2', name: 'Bahia', badge: 'https://img.sofascore.com/api/v1/team/1955/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-3', name: 'Corinthians', badge: 'https://img.sofascore.com/api/v1/team/1957/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-4', name: 'Botafogo', badge: 'https://img.sofascore.com/api/v1/team/1958/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-5', name: 'Sport', badge: 'https://img.sofascore.com/api/v1/team/1959/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-6', name: 'Goiás', badge: 'https://img.sofascore.com/api/v1/team/1960/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-7', name: 'Fluminense', badge: 'https://img.sofascore.com/api/v1/team/1961/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-8', name: 'Vitória', badge: 'https://img.sofascore.com/api/v1/team/1962/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-9', name: 'Palmeiras', badge: 'https://img.sofascore.com/api/v1/team/1963/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-10', name: 'São Caetano', badge: 'https://img.sofascore.com/api/v1/team/1964/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-11', name: 'Paraná', badge: 'https://img.sofascore.com/api/v1/team/1965/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-12', name: 'Internacional', badge: 'https://img.sofascore.com/api/v1/team/1966/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-13', name: 'Athletico', badge: 'https://img.sofascore.com/api/v1/team/1967/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-14', name: 'Santos', badge: 'https://img.sofascore.com/api/v1/team/1968/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-15', name: 'Ponte Preta', badge: 'https://img.sofascore.com/api/v1/team/1969/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-16', name: 'Guarani', badge: 'https://img.sofascore.com/api/v1/team/1972/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-17', name: 'América-MG', badge: 'https://img.sofascore.com/api/v1/team/1973/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-18', name: 'Vasco', badge: 'https://img.sofascore.com/api/v1/team/1974/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-19', name: 'Santa Cruz ', badge: 'https://img.sofascore.com/api/v1/team/1976/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-20', name: 'Atlético-MG', badge: 'https://img.sofascore.com/api/v1/team/1977/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-21', name: 'Gama', badge: 'https://img.sofascore.com/api/v1/team/1978/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-22', name: 'Botafogo-SP', badge: 'https://img.sofascore.com/api/v1/team/1979/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-23', name: 'Juventude', badge: 'https://img.sofascore.com/api/v1/team/1980/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-24', name: 'São Paulo', badge: 'https://img.sofascore.com/api/v1/team/1981/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-25', name: 'Coritiba', badge: 'https://img.sofascore.com/api/v1/team/1982/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-26', name: 'Criciúma', badge: 'https://img.sofascore.com/api/v1/team/1984/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-27', name: 'Figueirense', badge: 'https://img.sofascore.com/api/v1/team/1985/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-28', name: 'GE Brasil', badge: 'https://img.sofascore.com/api/v1/team/1986/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-29', name: 'Joinville', badge: 'https://img.sofascore.com/api/v1/team/1987/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-30', name: 'Bangu', badge: 'https://img.sofascore.com/api/v1/team/1993/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-31', name: 'Paysandu', badge: 'https://img.sofascore.com/api/v1/team/1997/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-32', name: 'RB Bragantino', badge: 'https://img.sofascore.com/api/v1/team/1999/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-33', name: 'Ceará', badge: 'https://img.sofascore.com/api/v1/team/2001/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-34', name: 'Sampaio Corrêa', badge: 'https://img.sofascore.com/api/v1/team/2005/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-35', name: 'Moto Club', badge: 'https://img.sofascore.com/api/v1/team/2009/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-36', name: 'CSA', badge: 'https://img.sofascore.com/api/v1/team/2010/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-37', name: 'Náutico', badge: 'https://img.sofascore.com/api/v1/team/2011/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-38', name: 'Remo', badge: 'https://img.sofascore.com/api/v1/team/2012/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-39', name: 'Confiança', badge: 'https://img.sofascore.com/api/v1/team/2017/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-40', name: 'Treze', badge: 'https://img.sofascore.com/api/v1/team/2018/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-41', name: 'ASA', badge: 'https://img.sofascore.com/api/v1/team/2019/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-42', name: 'Fortaleza', badge: 'https://img.sofascore.com/api/v1/team/2020/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-43', name: 'Vila Nova', badge: 'https://img.sofascore.com/api/v1/team/2021/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-44', name: 'Londrina', badge: 'https://img.sofascore.com/api/v1/team/2022/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-45', name: 'América-RN', badge: 'https://img.sofascore.com/api/v1/team/2023/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-46', name: 'Brasiliense', badge: 'https://img.sofascore.com/api/v1/team/2024/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-47', name: 'Ituano', badge: 'https://img.sofascore.com/api/v1/team/2025/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-48', name: 'Grêmio', badge: 'https://img.sofascore.com/api/v1/team/5926/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-49', name: 'Flamengo', badge: 'https://img.sofascore.com/api/v1/team/5981/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-50', name: 'Barueri', badge: 'https://img.sofascore.com/api/v1/team/6956/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-51', name: 'Guaratinguetá', badge: 'https://img.sofascore.com/api/v1/team/6957/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-52', name: 'Juventus-SP', badge: 'https://img.sofascore.com/api/v1/team/6960/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-53', name: 'Marília', badge: 'https://img.sofascore.com/api/v1/team/6961/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-54', name: 'Noroeste', badge: 'https://img.sofascore.com/api/v1/team/6962/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-55', name: 'Rio Branco-SP', badge: 'https://img.sofascore.com/api/v1/team/6964/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-56', name: 'Rio Claro', badge: 'https://img.sofascore.com/api/v1/team/6965/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-57', name: 'Santo André', badge: 'https://img.sofascore.com/api/v1/team/6966/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-58', name: 'São Bento', badge: 'https://img.sofascore.com/api/v1/team/6967/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-59', name: 'Madureira', badge: 'https://img.sofascore.com/api/v1/team/6980/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-60', name: 'Nova Iguaçu', badge: 'https://img.sofascore.com/api/v1/team/6981/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-61', name: 'Volta Redonda', badge: 'https://img.sofascore.com/api/v1/team/6982/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-62', name: 'Ipatinga', badge: 'https://img.sofascore.com/api/v1/team/7297/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-63', name: 'Atlético-GO', badge: 'https://img.sofascore.com/api/v1/team/7314/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-64', name: 'Avaí', badge: 'https://img.sofascore.com/api/v1/team/7315/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-65', name: 'ABC', badge: 'https://img.sofascore.com/api/v1/team/21838/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-66', name: 'Chapecoense', badge: 'https://img.sofascore.com/api/v1/team/21845/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-67', name: 'Icasa', badge: 'https://img.sofascore.com/api/v1/team/21851/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-68', name: 'Itabaiana', badge: 'https://img.sofascore.com/api/v1/team/21853/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-69', name: 'Boa Esporte', badge: 'https://img.sofascore.com/api/v1/team/21854/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-70', name: 'Sousa', badge: 'https://img.sofascore.com/api/v1/team/21864/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-71', name: 'Trem', badge: 'https://img.sofascore.com/api/v1/team/21865/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-72', name: 'XV de Piracicaba', badge: 'https://img.sofascore.com/api/v1/team/61692/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-73', name: 'Anápolis', badge: 'https://img.sofascore.com/api/v1/team/21872/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-74', name: 'Brusque', badge: 'https://img.sofascore.com/api/v1/team/21884/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-75', name: 'Cascavel', badge: 'https://img.sofascore.com/api/v1/team/21891/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-76', name: 'Cianorte', badge: 'https://img.sofascore.com/api/v1/team/21892/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-77', name: 'Portuguesa', badge: 'https://img.sofascore.com/api/v1/team/21896/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-78', name: 'Duque de Caxias', badge: 'https://img.sofascore.com/api/v1/team/21959/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-79', name: 'Itabuna EC', badge: 'https://img.sofascore.com/api/v1/team/21973/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-80', name: 'Marcílio Dias', badge: 'https://img.sofascore.com/api/v1/team/21978/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-81', name: 'Mirassol', badge: 'https://img.sofascore.com/api/v1/team/21982/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série A'] },
  { id: 'BRA-82', name: 'Novo Hamburgo', badge: 'https://img.sofascore.com/api/v1/team/480376/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-83', name: 'CRB', badge: 'https://img.sofascore.com/api/v1/team/22032/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-84', name: 'Ferroviário', badge: 'https://img.sofascore.com/api/v1/team/32672/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-85', name: 'Avenida', badge: 'https://img.sofascore.com/api/v1/team/32765/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-86', name: 'Ypiranga', badge: 'https://img.sofascore.com/api/v1/team/32766/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-87', name: 'São José-RS', badge: 'https://img.sofascore.com/api/v1/team/480379/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-88', name: 'Oeste', badge: 'https://img.sofascore.com/api/v1/team/32779/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-89', name: 'Mogi Mirim', badge: 'https://img.sofascore.com/api/v1/team/32781/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-90', name: 'Uberlândia', badge: 'https://img.sofascore.com/api/v1/team/32873/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-91', name: 'Águia de Marabá', badge: 'https://img.sofascore.com/api/v1/team/33998/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-92', name: 'Mixto', badge: 'https://img.sofascore.com/api/v1/team/34005/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-93', name: 'Potiguar', badge: 'https://img.sofascore.com/api/v1/team/34006/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-94', name: 'Ferroviária', badge: 'https://img.sofascore.com/api/v1/team/35285/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-95', name: 'Olaria', badge: 'https://img.sofascore.com/api/v1/team/39616/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-96', name: 'Caldense', badge: 'https://img.sofascore.com/api/v1/team/39621/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-97', name: 'Operário-PR', badge: 'https://img.sofascore.com/api/v1/team/39634/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-98', name: 'Luverdense', badge: 'https://img.sofascore.com/api/v1/team/40161/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-99', name: 'Naviraiense', badge: 'https://img.sofascore.com/api/v1/team/40168/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-100', name: 'Concórdia', badge: 'https://img.sofascore.com/api/v1/team/257674/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-101', name: 'Linense', badge: 'https://img.sofascore.com/api/v1/team/47503/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-102', name: 'São Bernardo', badge: 'https://img.sofascore.com/api/v1/team/47504/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-103', name: 'Botafogo-PB', badge: 'https://img.sofascore.com/api/v1/team/49196/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-104', name: 'Comercial-PI', badge: 'https://img.sofascore.com/api/v1/team/49200/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-105', name: 'Cuiabá', badge: 'https://img.sofascore.com/api/v1/team/49202/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-106', name: 'Comercial-SP', badge: 'https://img.sofascore.com/api/v1/team/61690/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-107', name: 'Juazeirense', badge: 'https://img.sofascore.com/api/v1/team/61724/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-108', name: 'Maracanã', badge: 'https://img.sofascore.com/api/v1/team/87156/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-109', name: 'Jacuipense', badge: 'https://img.sofascore.com/api/v1/team/87166/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-110', name: 'Tombense', badge: 'https://img.sofascore.com/api/v1/team/87202/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-111', name: 'Capivariano', badge: 'https://img.sofascore.com/api/v1/team/88738/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-112', name: 'Cametá', badge: 'https://img.sofascore.com/api/v1/team/90272/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-113', name: 'Betim', badge: 'https://img.sofascore.com/api/v1/team/368413/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-114', name: 'Aimoré', badge: 'https://img.sofascore.com/api/v1/team/480383/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-115', name: 'Maringá', badge: 'https://img.sofascore.com/api/v1/team/135324/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-116', name: 'Água Santa', badge: 'https://img.sofascore.com/api/v1/team/135510/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-117', name: 'Novorizontino', badge: 'https://img.sofascore.com/api/v1/team/135514/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
  { id: 'BRA-118', name: 'Votuporanguense', badge: 'https://img.sofascore.com/api/v1/team/135524/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-119', name: 'Inter de Limeira', badge: 'https://img.sofascore.com/api/v1/team/135526/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-120', name: 'Princesa', badge: 'https://img.sofascore.com/api/v1/team/144854/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-121', name: 'Lemense', badge: 'https://img.sofascore.com/api/v1/team/188775/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-122', name: 'Primavera', badge: 'https://img.sofascore.com/api/v1/team/188777/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-123', name: 'Ríver-PI', badge: 'https://img.sofascore.com/api/v1/team/188849/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-124', name: 'Alecrim', badge: 'https://img.sofascore.com/api/v1/team/189493/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-125', name: 'Portuguesa-RJ', badge: 'https://img.sofascore.com/api/v1/team/208067/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-126', name: 'Tocantinópolis', badge: 'https://img.sofascore.com/api/v1/team/215371/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-127', name: 'EC São Bernardo', badge: 'https://img.sofascore.com/api/v1/team/224647/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-128', name: 'Portuguesa Santista', badge: 'https://img.sofascore.com/api/v1/team/225186/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-129', name: 'Altos', badge: 'https://img.sofascore.com/api/v1/team/228199/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-130', name: 'Hercílio Luz', badge: 'https://img.sofascore.com/api/v1/team/234222/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-131', name: 'Afogados', badge: 'https://img.sofascore.com/api/v1/team/242130/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-132', name: 'Grêmio Prudente', badge: 'https://img.sofascore.com/api/v1/team/252408/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-133', name: 'XV de Jaú', badge: 'https://img.sofascore.com/api/v1/team/389971/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-134', name: 'Sampaio Corrêa-RJ', badge: 'https://img.sofascore.com/api/v1/team/257632/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-135', name: 'Floresta', badge: 'https://img.sofascore.com/api/v1/team/274286/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-136', name: 'Maricá', badge: 'https://img.sofascore.com/api/v1/team/288535/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-137', name: 'Humaitá', badge: 'https://img.sofascore.com/api/v1/team/293460/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-138', name: 'Costa Rica-MS', badge: 'https://img.sofascore.com/api/v1/team/308001/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-139', name: 'Tuna Luso', badge: 'https://img.sofascore.com/api/v1/team/333422/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-140', name: 'Amazonas', badge: 'https://img.sofascore.com/api/v1/team/336664/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-141', name: 'Pouso Alegre', badge: 'https://img.sofascore.com/api/v1/team/343540/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-142', name: 'Democrata (SL)', badge: 'https://img.sofascore.com/api/v1/team/343628/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-143', name: 'Fluminense-PI', badge: 'https://img.sofascore.com/api/v1/team/375317/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-144', name: 'Azuriz', badge: 'https://img.sofascore.com/api/v1/team/375853/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-145', name: 'Barcelona de Ilhéus', badge: 'https://img.sofascore.com/api/v1/team/386170/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-146', name: 'Aymorés', badge: 'https://img.sofascore.com/api/v1/team/388220/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-147', name: 'Aster Brasil', badge: 'https://img.sofascore.com/api/v1/team/401092/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-148', name: 'Itabirito', badge: 'https://img.sofascore.com/api/v1/team/454864/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-149', name: 'Velo Clube', badge: 'https://img.sofascore.com/api/v1/team/88736/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-150', name: 'Boavista', badge: 'https://img.sofascore.com/api/v1/team/6977/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-151', name: 'São Gonçalo', badge: 'https://img.sofascore.com/api/v1/team/257252/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-152', name: 'Americano', badge: 'https://img.sofascore.com/api/v1/team/1992/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-153', name: 'Araruama', badge: 'https://img.sofascore.com/api/v1/team/289892/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-154', name: 'America-RJ', badge: 'https://img.sofascore.com/api/v1/team/6976/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-155', name: 'Cabofriense', badge: 'https://img.sofascore.com/api/v1/team/6978/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-156', name: 'Resende', badge: 'https://img.sofascore.com/api/v1/team/32878/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-157', name: 'Audax-RJ', badge: 'https://img.sofascore.com/api/v1/team/85341/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-158', name: 'URT', badge: 'https://img.sofascore.com/api/v1/team/35278/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-159', name: 'Democrata (GV)', badge: 'https://img.sofascore.com/api/v1/team/21848/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-160', name: 'North', badge: 'https://img.sofascore.com/api/v1/team/465989/image', country: 'BRA', type: TeamType.CLUB, tags: [] },
  { id: 'BRA-161', name: 'Athletic', badge: 'https://img.sofascore.com/api/v1/team/342775/image', country: 'BRA', type: TeamType.CLUB, tags: ['Série B'] },
];
