export const CHINA_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'CHN-1', name: 'Beijing Guoan', badge: 'https://img.sofascore.com/api/v1/team/3376/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-2', name: 'Chengdu Rongcheng', badge: 'https://img.sofascore.com/api/v1/team/221241/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-3', name: 'Tongliang Long', badge: 'https://img.sofascore.com/api/v1/team/474989/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-4', name: 'Dalian Yingbo', badge: 'https://img.sofascore.com/api/v1/team/474992/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-5', name: 'Yukun', badge: 'https://img.sofascore.com/api/v1/team/474991/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-6', name: 'Shandong Taishan', badge: 'https://img.sofascore.com/api/v1/team/3371/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-7', name: 'Shenhua', badge: 'https://img.sofascore.com/api/v1/team/3373/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-8', name: 'Shenzhen', badge: 'https://img.sofascore.com/api/v1/team/281331/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-9', name: 'Zhejiang', badge: 'https://img.sofascore.com/api/v1/team/34697/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-10', name: 'Qingdao West Coast', badge: 'https://img.sofascore.com/api/v1/team/369532/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-11', name: 'Hainiu', badge: 'https://img.sofascore.com/api/v1/team/34695/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-12', name: 'Tieren', badge: 'https://img.sofascore.com/api/v1/team/221240/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-13', name: 'Shanghai Port', badge: 'https://img.sofascore.com/api/v1/team/41537/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-14', name: 'Henan', badge: 'https://img.sofascore.com/api/v1/team/34692/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-15', name: 'Three Towns', badge: 'https://img.sofascore.com/api/v1/team/295152/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
  { id: 'CHN-16', name: 'Jinmen Tiger', badge: 'https://img.sofascore.com/api/v1/team/3367/image', country: 'CHN', type: TeamType.CLUB, tags: [] },
];
