export const COLOMBIA_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'COL-1', name: 'América de Cali', badge: 'https://img.sofascore.com/api/v1/team/6102/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-2', name: 'Junior Barranquilla', badge: 'https://img.sofascore.com/api/v1/team/6105/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-3', name: 'Atlético Nacional', badge: 'https://img.sofascore.com/api/v1/team/6106/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-4', name: 'Deportivo Pereira', badge: 'https://img.sofascore.com/api/v1/team/6109/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-5', name: 'Tolima', badge: 'https://img.sofascore.com/api/v1/team/6111/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-6', name: 'Deportivo Cali', badge: 'https://img.sofascore.com/api/v1/team/6112/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-7', name: 'Independiente Medellín', badge: 'https://img.sofascore.com/api/v1/team/6115/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-8', name: 'Santa Fe', badge: 'https://img.sofascore.com/api/v1/team/6116/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-9', name: 'Millonarios', badge: 'https://img.sofascore.com/api/v1/team/6117/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-10', name: 'Once Caldas', badge: 'https://img.sofascore.com/api/v1/team/6118/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-11', name: 'Deportivo Pasto', badge: 'https://img.sofascore.com/api/v1/team/6113/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-12', name: 'Inter de Bogotá', badge: 'https://img.sofascore.com/api/v1/team/1164534/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-13', name: 'Águilas Doradas', badge: 'https://img.sofascore.com/api/v1/team/48244/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-14', name: 'Bucaramanga', badge: 'https://img.sofascore.com/api/v1/team/6103/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-15', name: 'Llaneros', badge: 'https://img.sofascore.com/api/v1/team/89374/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-16', name: 'Fortaleza', badge: 'https://img.sofascore.com/api/v1/team/89368/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-17', name: 'Jaguares', badge: 'https://img.sofascore.com/api/v1/team/89370/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-18', name: 'Alianza Valledupar', badge: 'https://img.sofascore.com/api/v1/team/504899/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-19', name: 'Boyacá Chicó', badge: 'https://img.sofascore.com/api/v1/team/6107/image', country: 'COL', type: TeamType.CLUB, tags: [] },
  { id: 'COL-20', name: 'Cúcuta', badge: 'https://img.sofascore.com/api/v1/team/6108/image', country: 'COL', type: TeamType.CLUB, tags: [] },
];
