const brazilTeams = [
  { id: 'CUS-BRA-1', name: 'Alves Dias', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-2', name: 'Anchieta', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-3', name: 'Assunção', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-4', name: 'Baeta Neves', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-5', name: 'Bairro dos Casa', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-6', name: 'Chácara Inglesa', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-7', name: 'Demarchi', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-8', name: 'Jardim Batistini', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-9', name: 'Jardim Calux', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-10', name: 'Jardim Campestre', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-11', name: 'Jardim Cláudia', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-12', name: 'Jardim Colombo', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-13', name: 'Jardim Colonial', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-14', name: 'Jardim Detroid', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-15', name: 'Jardim Independência', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-16', name: 'Jardim Ipanema', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-17', name: 'Jardim Ipê', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-18', name: 'Jardim Las Palmas', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-19', name: 'Jardim Las Vegas', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-20', name: 'Jardim Laura', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-21', name: 'Jardim Los Angeles', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-22', name: 'Jardim Piraporinha', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-23', name: 'Jardim Represa', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-24', name: 'Jardim Telma', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-25', name: 'Jardim Vergueiro', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-26', name: 'Jardim do Lago', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-27', name: 'Jardim do Mar', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-28', name: 'Jordanópolis', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-29', name: 'Ferrazópolis', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-30', name: 'Mizuo', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-31', name: 'Nova Petrópolis', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-32', name: 'Orquídeas', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-33', name: 'Paradão', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-34', name: 'Parque Avaí', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-35', name: 'Parque Espacial', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-36', name: 'Parque dos Pássaros', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-37', name: 'Parque Imigrantes', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-38', name: 'Parque Terra Nova', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-39', name: 'Paulicéia', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-40', name: 'Planalto', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-41', name: 'Químicos', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-42', name: 'Rudge Ramos', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-43', name: 'Sítio Bom Jesus', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-44', name: 'Sítio dos Vianas', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-45', name: 'Taboão', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-46', name: 'Vila Alvarenga', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-47', name: 'Vila Aurora', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-48', name: 'Vila Capivari', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-49', name: 'Vila Cooperativa', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-50', name: 'Vila Euclides', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-51', name: 'Vila Euro', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-52', name: 'Vila Floresta', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-53', name: 'Vila Marchi', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-54', name: 'Vila Rosa', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-55', name: 'Vila São Pedro', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-56', name: 'Vila Vitória', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-57', name: 'Bairro da Sé', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-58', name: 'Freguesia do Ó', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-59', name: 'Itaim Paulista', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-60', name: 'Itaquera', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-61', name: 'Jabaquara', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-62', name: 'Jardins', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-63', name: 'Jardim Belém', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-64', name: 'Jardim Imperial', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-65', name: 'Jardim Limoeiro', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-66', name: 'Jardim Alves', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-67', name: 'Jardim Turquesa', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-68', name: 'Lapa', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-69', name: 'Liberdade', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-70', name: 'Moca', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-71', name: 'Moema', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-72', name: 'Morumbi', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-73', name: 'Parque Primavera', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-74', name: 'Pinheiros', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-75', name: 'Planalto Paulista', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-76', name: 'Tatuapé', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-77', name: 'Tietê', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-78', name: 'Vila Alpina', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-79', name: 'Vila Alvinópolis', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-80', name: 'Vila Brás', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-81', name: 'Vila Brasilândia', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-82', name: 'Vila Clemente', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-83', name: 'Vila Guilherme', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-84', name: 'Vila Ipiranga', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-85', name: 'Vila Leopoldina', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-86', name: 'Vila Lobos', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-87', name: 'Vila Madalena', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-88', name: 'Vila Olímpia', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-89', name: 'Vila Paulina', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-90', name: 'Vila Paulista', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-91', name: 'Vila Prudente', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-92', name: 'Vila Ré', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-93', name: 'Vila Rica', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-94', name: 'Vila Rio Claro', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-95', name: 'Vila Romana', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
  { id: 'CUS-BRA-96', name: 'Vila Saúde', badge: '/images/leagues/brazilian-league.png', type: TeamType.CUSTOM, country: 'BRA', tags: [] },
]

const argentinaTeams = [
  { id: 'CUS-ARG-1', name: 'Bariloche', badge: '/images/leagues/argentinian-league.png', type: TeamType.CUSTOM, country: 'ARG', tags: [] },
  { id: 'CUS-ARG-2', name: 'Jardim Lopez', badge: '/images/leagues/argentinian-league.png', type: TeamType.CUSTOM, country: 'ARG', tags: [] },
  { id: 'CUS-ARG-3', name: 'Jardim Mendonza', badge: '/images/leagues/argentinian-league.png', type: TeamType.CUSTOM, country: 'ARG', tags: [] },
  { id: 'CUS-ARG-4', name: 'Vila Banfield', badge: '/images/leagues/argentinian-league.png', type: TeamType.CUSTOM, country: 'ARG', tags: [] },
  { id: 'CUS-ARG-5', name: 'Vila Buenos Aires', badge: '/images/leagues/argentinian-league.png', type: TeamType.CUSTOM, country: 'ARG', tags: [] },
  { id: 'CUS-ARG-6', name: 'Vila Ortobom', badge: '/images/leagues/argentinian-league.png', type: TeamType.CUSTOM, country: 'ARG', tags: [] },
  { id: 'CUS-ARG-7', name: 'Vila Rosário', badge: '/images/leagues/argentinian-league.png', type: TeamType.CUSTOM, country: 'ARG', tags: [] },
  { id: 'CUS-ARG-8', name: 'Vila Santa Rosa', badge: '/images/leagues/argentinian-league.png', type: TeamType.CUSTOM, country: 'ARG', tags: [] },
  { id: 'CUS-ARG-9', name: 'Vila Tucumán', badge: '/images/leagues/argentinian-league.png', type: TeamType.CUSTOM, country: 'ARG', tags: [] },
  { id: 'CUS-ARG-10', name: 'Vila Mercedez', badge: '/images/leagues/argentinian-league.png', type: TeamType.CUSTOM, country: 'ARG', tags: [] },
]

const mexicoTeams = [
  { id: 'CUS-MEX-1', name: 'Cancún', badge: '/images/leagues/mexican-league.png', type: TeamType.CUSTOM, country: 'MEX', tags: [] },
  { id: 'CUS-MEX-2', name: 'Huatulco', badge: '/images/leagues/mexican-league.png', type: TeamType.CUSTOM, country: 'MEX', tags: [] },
  { id: 'CUS-MEX-3', name: 'Jardim Asteca', badge: '/images/leagues/mexican-league.png', type: TeamType.CUSTOM, country: 'MEX', tags: [] },
  { id: 'CUS-MEX-4', name: 'Jardim Laguna', badge: '/images/leagues/mexican-league.png', type: TeamType.CUSTOM, country: 'MEX', tags: [] },
  { id: 'CUS-MEX-5', name: 'Jardim Tijuana', badge: '/images/leagues/mexican-league.png', type: TeamType.CUSTOM, country: 'MEX', tags: [] },
  { id: 'CUS-MEX-6', name: 'Olarya', badge: '/images/leagues/mexican-league.png', type: TeamType.CUSTOM, country: 'MEX', tags: [] },
  { id: 'CUS-MEX-7', name: 'Vila América', badge: '/images/leagues/mexican-league.png', type: TeamType.CUSTOM, country: 'MEX', tags: [] },
  { id: 'CUS-MEX-8', name: 'Vila Monterrey', badge: '/images/leagues/mexican-league.png', type: TeamType.CUSTOM, country: 'MEX', tags: [] },
  { id: 'CUS-MEX-9', name: 'Vila Titaco', badge: '/images/leagues/mexican-league.png', type: TeamType.CUSTOM, country: 'MEX', tags: [] },
  { id: 'CUS-MEX-10', name: 'Vila Yucatán', badge: '/images/leagues/mexican-league.png', type: TeamType.CUSTOM, country: 'MEX', tags: [] },
]

const usaTeams = [
  { id: 'CUS-USA-1', name: 'Brooklin', badge: '/images/leagues/american-league.png', type: TeamType.CUSTOM, country: 'USA', tags: [] },
  { id: 'CUS-USA-2', name: 'Parque Hood River', badge: '/images/leagues/american-league.png', type: TeamType.CUSTOM, country: 'USA', tags: [] },
  { id: 'CUS-USA-3', name: 'Jardim Dallas', badge: '/images/leagues/american-league.png', type: TeamType.CUSTOM, country: 'USA', tags: [] },
  { id: 'CUS-USA-4', name: 'Jardim Lancaster', badge: '/images/leagues/american-league.png', type: TeamType.CUSTOM, country: 'USA', tags: [] },
  { id: 'CUS-USA-5', name: 'Nashville', badge: '/images/leagues/american-league.png', type: TeamType.CUSTOM, country: 'USA', tags: [] },
  { id: 'CUS-USA-6', name: 'Palm Island', badge: '/images/leagues/american-league.png', type: TeamType.CUSTOM, country: 'USA', tags: [] },
  { id: 'CUS-USA-7', name: 'Vila Phoenix', badge: '/images/leagues/american-league.png', type: TeamType.CUSTOM, country: 'USA', tags: [] },
  { id: 'CUS-USA-8', name: 'Vila Portland', badge: '/images/leagues/american-league.png', type: TeamType.CUSTOM, country: 'USA', tags: [] },
]

const colombiaTeams = [
  { id: 'CUS-COL-1', name: 'Jardim Ametista', badge: '/images/leagues/colombian-league.png', type: TeamType.CUSTOM, country: 'COL', tags: [] },
  { id: 'CUS-COL-2', name: 'Jardim Aliança', badge: '/images/leagues/colombian-league.png', type: TeamType.CUSTOM, country: 'COL', tags: [] },
  { id: 'CUS-COL-3', name: 'Jardim Cali', badge: '/images/leagues/colombian-league.png', type: TeamType.CUSTOM, country: 'COL', tags: [] },
  { id: 'CUS-COL-4', name: 'Vila Candelária', badge: '/images/leagues/colombian-league.png', type: TeamType.CUSTOM, country: 'COL', tags: [] },
  { id: 'CUS-COL-5', name: 'Vila Medellín', badge: '/images/leagues/colombian-league.png', type: TeamType.CUSTOM, country: 'COL', tags: [] },
  { id: 'CUS-COL-6', name: 'Jardim Bellavista', badge: '/images/leagues/colombian-league.png', type: TeamType.CUSTOM, country: 'COL', tags: [] },
  { id: 'CUS-COL-7', name: 'Turmalina', badge: '/images/leagues/colombian-league.png', type: TeamType.CUSTOM, country: 'COL', tags: [] },
  { id: 'CUS-COL-8', name: 'Parque Industrial', badge: '/images/leagues/colombian-league.png', type: TeamType.CUSTOM, country: 'COL', tags: [] },
]

const chileTeams = [
  { id: 'CUS-CHL-1', name: 'Bairro Únion', badge: '/images/leagues/chilean-league.png', type: TeamType.CUSTOM, country: 'CHL', tags: [] },
  { id: 'CUS-CHL-2', name: 'Vila Salinitas', badge: '/images/leagues/chilean-league.png', type: TeamType.CUSTOM, country: 'CHL', tags: [] },
  { id: 'CUS-CHL-3', name: 'Jardim Santiago', badge: '/images/leagues/chilean-league.png', type: TeamType.CUSTOM, country: 'CHL', tags: [] },
  { id: 'CUS-CHL-4', name: 'Jardim Valência', badge: '/images/leagues/chilean-league.png', type: TeamType.CUSTOM, country: 'CHL', tags: [] },
  { id: 'CUS-CHL-5', name: 'Vila Águilas', badge: '/images/leagues/chilean-league.png', type: TeamType.CUSTOM, country: 'CHL', tags: [] },
  { id: 'CUS-CHL-6', name: 'Vila Santander', badge: '/images/leagues/chilean-league.png', type: TeamType.CUSTOM, country: 'CHL', tags: [] },
  { id: 'CUS-CHL-7', name: 'Vila Estación Central', badge: '/images/leagues/chilean-league.png', type: TeamType.CUSTOM, country: 'CHL', tags: [] },
  { id: 'CUS-CHL-8', name: 'Jardim Del Este', badge: '/images/leagues/chilean-league.png', type: TeamType.CUSTOM, country: 'CHL', tags: [] },
  { id: 'CUS-CHL-9', name: 'Vila Real Audiencia', badge: '/images/leagues/chilean-league.png', type: TeamType.CUSTOM, country: 'CHL', tags: [] },
  { id: 'CUS-CHL-10', name: 'Jardim Atacama', badge: '/images/leagues/chilean-league.png', type: TeamType.CUSTOM, country: 'CHL', tags: [] },
]

const uruguayTeams = [
  { id: 'CUS-URY-1', name: 'Castanhal', badge: '/images/leagues/uruguayan-league.png', type: TeamType.CUSTOM, country: 'URY', tags: [] },
  { id: 'CUS-URY-2', name: 'Jardim Castillos', badge: '/images/leagues/uruguayan-league.png', type: TeamType.CUSTOM, country: 'URY', tags: [] },
  { id: 'CUS-URY-3', name: 'Jardim Canelones', badge: '/images/leagues/uruguayan-league.png', type: TeamType.CUSTOM, country: 'URY', tags: [] },
  { id: 'CUS-URY-4', name: 'Punta Este', badge: '/images/leagues/uruguayan-league.png', type: TeamType.CUSTOM, country: 'URY', tags: [] },
  { id: 'CUS-URY-5', name: 'Vila Libertad', badge: '/images/leagues/uruguayan-league.png', type: TeamType.CUSTOM, country: 'URY', tags: [] },
  { id: 'CUS-URY-6', name: 'Vila Montevidéu', badge: '/images/leagues/uruguayan-league.png', type: TeamType.CUSTOM, country: 'URY', tags: [] },
  { id: 'CUS-URY-7', name: 'Vila Molina', badge: '/images/leagues/uruguayan-league.png', type: TeamType.CUSTOM, country: 'URY', tags: [] },
  { id: 'CUS-URY-8', name: 'Casavalle', badge: '/images/leagues/uruguayan-league.png', type: TeamType.CUSTOM, country: 'URY', tags: [] },
]

const peruTeams = [
  { id: 'CUS-PER-1', name: 'Allende', badge: '/images/leagues/peruvian-league.png', type: TeamType.CUSTOM, country: 'PER', tags: [] },
  { id: 'CUS-PER-2', name: 'Jardim Iolita', badge: '/images/leagues/peruvian-league.png', type: TeamType.CUSTOM, country: 'PER', tags: [] },
  { id: 'CUS-PER-3', name: 'Vila Lima', badge: '/images/leagues/peruvian-league.png', type: TeamType.CUSTOM, country: 'PER', tags: [] },
  { id: 'CUS-PER-4', name: 'Vila Maya', badge: '/images/leagues/peruvian-league.png', type: TeamType.CUSTOM, country: 'PER', tags: [] },
  { id: 'CUS-PER-5', name: 'Vila Larimar', badge: '/images/leagues/peruvian-league.png', type: TeamType.CUSTOM, country: 'PER', tags: [] },
  { id: 'CUS-PER-6', name: 'Avellana', badge: '/images/leagues/peruvian-league.png', type: TeamType.CUSTOM, country: 'PER', tags: [] },
]

const paraguayTeams = [
  { id: 'CUS-PRY-1', name: 'Jardim Miraflores', badge: '/images/leagues/paraguayan-league.png', type: TeamType.CUSTOM, country: 'PRY', tags: [] },
  { id: 'CUS-PRY-2', name: 'Parque Assuncíon', badge: '/images/leagues/paraguayan-league.png', type: TeamType.CUSTOM, country: 'PRY', tags: [] },
  { id: 'CUS-PRY-3', name: 'Vila San Bernardino', badge: '/images/leagues/paraguayan-league.png', type: TeamType.CUSTOM, country: 'PRY', tags: [] },
  { id: 'CUS-PRY-4', name: 'Villarica', badge: '/images/leagues/paraguayan-league.png', type: TeamType.CUSTOM, country: 'PRY', tags: [] },
  { id: 'CUS-PRY-5', name: 'Parque Guaraní', badge: '/images/leagues/paraguayan-league.png', type: TeamType.CUSTOM, country: 'PRY', tags: [] },
  { id: 'CUS-PRY-6', name: 'Vila Mirtillo', badge: '/images/leagues/paraguayan-league.png', type: TeamType.CUSTOM, country: 'PRY', tags: [] },
]

const venezuelaTeams = [
  { id: 'CUS-VEN-1', name: 'Jardim Independente', badge: '/images/leagues/venezuelan-league.png', type: TeamType.CUSTOM, country: 'VEN', tags: [] },
  { id: 'CUS-VEN-2', name: 'Jardim Lázuli', badge: '/images/leagues/venezuelan-league.png', type: TeamType.CUSTOM, country: 'VEN', tags: [] },
  { id: 'CUS-VEN-3', name: 'Vila Baltimore', badge: '/images/leagues/venezuelan-league.png', type: TeamType.CUSTOM, country: 'VEN', tags: [] },
  { id: 'CUS-VEN-4', name: 'Vila Caracas', badge: '/images/leagues/venezuelan-league.png', type: TeamType.CUSTOM, country: 'VEN', tags: [] },
  { id: 'CUS-VEN-5', name: 'Jardim Nuevo', badge: '/images/leagues/venezuelan-league.png', type: TeamType.CUSTOM, country: 'VEN', tags: [] },
  { id: 'CUS-VEN-6', name: 'Vila Andaluz', badge: '/images/leagues/venezuelan-league.png', type: TeamType.CUSTOM, country: 'VEN', tags: [] },
]

const ecuadorTeams = [
  { id: 'CUS-ECU-1', name: 'Jardim Ambatho', badge: '/images/leagues/ecuadorian-league.png', type: TeamType.CUSTOM, country: 'ECU', tags: [] },
  { id: 'CUS-ECU-2', name: 'Jardim Huesca', badge: '/images/leagues/ecuadorian-league.png', type: TeamType.CUSTOM, country: 'ECU', tags: [] },
  { id: 'CUS-ECU-3', name: 'Salta', badge: '/images/leagues/ecuadorian-league.png', type: TeamType.CUSTOM, country: 'ECU', tags: [] },
  { id: 'CUS-ECU-4', name: 'Vila Mérida', badge: '/images/leagues/ecuadorian-league.png', type: TeamType.CUSTOM, country: 'ECU', tags: [] },
  { id: 'CUS-ECU-5', name: 'Vila Central', badge: '/images/leagues/ecuadorian-league.png', type: TeamType.CUSTOM, country: 'ECU', tags: [] },
  { id: 'CUS-ECU-6', name: 'Vila Cobre', badge: '/images/leagues/ecuadorian-league.png', type: TeamType.CUSTOM, country: 'ECU', tags: [] },
]

const boliviaTeams = [
  { id: 'CUS-BOL-1', name: 'Jardim da Prata', badge: '/images/leagues/bolivian-league.png', type: TeamType.CUSTOM, country: 'BOL', tags: [] },
  { id: 'CUS-BOL-2', name: 'Vila Loretto', badge: '/images/leagues/bolivian-league.png', type: TeamType.CUSTOM, country: 'BOL', tags: [] },
  { id: 'CUS-BOL-3', name: 'Vila Rúbia', badge: '/images/leagues/bolivian-league.png', type: TeamType.CUSTOM, country: 'BOL', tags: [] },
  { id: 'CUS-BOL-4', name: 'Vila Hamburgo', badge: '/images/leagues/bolivian-league.png', type: TeamType.CUSTOM, country: 'BOL', tags: [] },
  { id: 'CUS-BOL-5', name: 'Jardim Sierra', badge: '/images/leagues/bolivian-league.png', type: TeamType.CUSTOM, country: 'BOL', tags: [] },
  { id: 'CUS-BOL-6', name: 'Vila Ouro', badge: '/images/leagues/bolivian-league.png', type: TeamType.CUSTOM, country: 'BOL', tags: [] },
]

export const CUSTOM_TEAM_LIST: Readonly<TeamDetails[]> = [
  ...brazilTeams,
  ...argentinaTeams,
  ...mexicoTeams,
  ...usaTeams,
  ...colombiaTeams,
  ...chileTeams,
  ...uruguayTeams,
  ...peruTeams,
  ...paraguayTeams,
  ...venezuelaTeams,
  ...ecuadorTeams,
  ...boliviaTeams,
]
