export const ENGLAND_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'ENG-1', name: 'QPR', badge: 'https://img.sofascore.com/api/v1/team/1/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-2', name: 'Portsmouth', badge: 'https://img.sofascore.com/api/v1/team/2/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-3', name: 'Wolverhampton', badge: 'https://img.sofascore.com/api/v1/team/3/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-4', name: 'Bolton', badge: 'https://img.sofascore.com/api/v1/team/5/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-5', name: 'Burnley', badge: 'https://img.sofascore.com/api/v1/team/6/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-6', name: 'Crystal Palace', badge: 'https://img.sofascore.com/api/v1/team/7/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-7', name: 'West Brom', badge: 'https://img.sofascore.com/api/v1/team/8/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-8', name: 'Birmingham', badge: 'https://img.sofascore.com/api/v1/team/9/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-9', name: 'Coventry City', badge: 'https://img.sofascore.com/api/v1/team/11/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-10', name: 'Rotherham', badge: 'https://img.sofascore.com/api/v1/team/13/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-11', name: 'Nottingham Forest', badge: 'https://img.sofascore.com/api/v1/team/14/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-12', name: 'Sheffield Utd', badge: 'https://img.sofascore.com/api/v1/team/15/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-13', name: 'Manchester City', badge: 'https://img.sofascore.com/api/v1/team/17/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-14', name: 'Barnsley', badge: 'https://img.sofascore.com/api/v1/team/23/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-15', name: 'Watford', badge: 'https://img.sofascore.com/api/v1/team/24/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-16', name: 'Derby County', badge: 'https://img.sofascore.com/api/v1/team/27/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-17', name: 'Reading', badge: 'https://img.sofascore.com/api/v1/team/28/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-18', name: 'Brighton', badge: 'https://img.sofascore.com/api/v1/team/30/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-19', name: 'Leicester', badge: 'https://img.sofascore.com/api/v1/team/31/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-20', name: 'Ipswich Town', badge: 'https://img.sofascore.com/api/v1/team/32/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-21', name: 'Tottenham', badge: 'https://img.sofascore.com/api/v1/team/33/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-22', name: 'Leeds United', badge: 'https://img.sofascore.com/api/v1/team/34/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-23', name: 'Manchester United', badge: 'https://img.sofascore.com/api/v1/team/35/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-24', name: 'Middlesbrough', badge: 'https://img.sofascore.com/api/v1/team/36/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-25', name: 'West Ham', badge: 'https://img.sofascore.com/api/v1/team/37/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-26', name: 'Chelsea', badge: 'https://img.sofascore.com/api/v1/team/38/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-27', name: 'Newcastle', badge: 'https://img.sofascore.com/api/v1/team/39/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-28', name: 'Aston Villa', badge: 'https://img.sofascore.com/api/v1/team/40/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-29', name: 'Sunderland', badge: 'https://img.sofascore.com/api/v1/team/41/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-30', name: 'Arsenal', badge: 'https://img.sofascore.com/api/v1/team/42/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-31', name: 'Fulham', badge: 'https://img.sofascore.com/api/v1/team/43/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-32', name: 'Liverpool', badge: 'https://img.sofascore.com/api/v1/team/44/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-33', name: 'Southampton', badge: 'https://img.sofascore.com/api/v1/team/45/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-34', name: 'Blackburn', badge: 'https://img.sofascore.com/api/v1/team/46/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-35', name: 'Wigan Athletic', badge: 'https://img.sofascore.com/api/v1/team/49/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-36', name: 'Brentford', badge: 'https://img.sofascore.com/api/v1/team/50/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-37', name: 'Northampton', badge: 'https://img.sofascore.com/api/v1/team/57/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-38', name: 'Bristol City', badge: 'https://img.sofascore.com/api/v1/team/58/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-39', name: 'Huddersfield', badge: 'https://img.sofascore.com/api/v1/team/59/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-40', name: 'Bournemouth', badge: 'https://img.sofascore.com/api/v1/team/60/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-41', name: 'Cambridge', badge: 'https://img.sofascore.com/api/v1/team/63/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-42', name: 'Mansfield', badge: 'https://img.sofascore.com/api/v1/team/70/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-43', name: 'Plymouth', badge: 'https://img.sofascore.com/api/v1/team/71/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-44', name: 'Luton Town', badge: 'https://img.sofascore.com/api/v1/team/72/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-45', name: 'Bristol Rovers', badge: 'https://img.sofascore.com/api/v1/team/76/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-46', name: 'Carlisle', badge: 'https://img.sofascore.com/api/v1/team/78/image', country: 'ENG', type: TeamType.CLUB, tags: [] },
  { id: 'ENG-47', name: 'Hull City', badge: 'https://img.sofascore.com/api/v1/team/96/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-48', name: 'Norwich', badge: 'https://img.sofascore.com/api/v1/team/263/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-49', name: 'Rochester United', badge: 'https://img.sofascore.com/api/v1/team/206439/image', country: 'ENG', type: TeamType.CLUB, tags: [] },
  { id: 'ENG-50', name: 'Everton', badge: 'https://img.sofascore.com/api/v1/team/48/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.PREMIER_26] },
  { id: 'ENG-51', name: 'Millwall', badge: 'https://img.sofascore.com/api/v1/team/25/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-52', name: 'Wrexham', badge: 'https://img.sofascore.com/api/v1/team/64/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-53', name: 'Swansea', badge: 'https://img.sofascore.com/api/v1/team/74/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-54', name: 'Preston', badge: 'https://img.sofascore.com/api/v1/team/21/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-55', name: 'Stoke City', badge: 'https://img.sofascore.com/api/v1/team/29/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-56', name: 'Charlton Athletic', badge: 'https://img.sofascore.com/api/v1/team/47/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-57', name: 'Oxford Utd', badge: 'https://img.sofascore.com/api/v1/team/95/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-58', name: 'Sheffield Wed', badge: 'https://img.sofascore.com/api/v1/team/12/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-59', name: 'Lincoln City', badge: 'https://img.sofascore.com/api/v1/team/92/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-60', name: 'Cardiff', badge: 'https://img.sofascore.com/api/v1/team/61/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_26] },
  { id: 'ENG-61', name: 'Stockport County', badge: 'https://img.sofascore.com/api/v1/team/10/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-62', name: 'Bradford', badge: 'https://img.sofascore.com/api/v1/team/22/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-63', name: 'Stevenage', badge: 'https://img.sofascore.com/api/v1/team/133/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-64', name: 'Wycombe', badge: 'https://img.sofascore.com/api/v1/team/62/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-65', name: 'Blackpool', badge: 'https://img.sofascore.com/api/v1/team/67/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-66', name: 'Doncaster', badge: 'https://img.sofascore.com/api/v1/team/84/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-67', name: 'Burton Albion', badge: 'https://img.sofascore.com/api/v1/team/134/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-68', name: 'Peterborough Utd', badge: 'https://img.sofascore.com/api/v1/team/54/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-69', name: 'Wimbledon', badge: 'https://img.sofascore.com/api/v1/team/23957/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-70', name: 'Leyton Orient', badge: 'https://img.sofascore.com/api/v1/team/83/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-71', name: 'Exeter City', badge: 'https://img.sofascore.com/api/v1/team/86/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-72', name: 'Port Vale', badge: 'https://img.sofascore.com/api/v1/team/55/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-73', name: 'Bromley', badge: 'https://img.sofascore.com/api/v1/team/180/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-74', name: 'MK Dons', badge: 'https://img.sofascore.com/api/v1/team/4/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-75', name: 'Salford City', badge: 'https://img.sofascore.com/api/v1/team/37998/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-76', name: 'Notts County', badge: 'https://img.sofascore.com/api/v1/team/56/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_ONE_26] },
  { id: 'ENG-77', name: 'Chesterfield', badge: 'https://img.sofascore.com/api/v1/team/68/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-78', name: 'Grimsby', badge: 'https://img.sofascore.com/api/v1/team/18/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-79', name: 'Barnet', badge: 'https://img.sofascore.com/api/v1/team/77/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-80', name: 'Swindon Town', badge: 'https://img.sofascore.com/api/v1/team/53/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-81', name: 'Oldham Athletic', badge: 'https://img.sofascore.com/api/v1/team/65/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-82', name: 'Crewe Alexandra', badge: 'https://img.sofascore.com/api/v1/team/19/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-83', name: 'Colchester', badge: 'https://img.sofascore.com/api/v1/team/66/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-84', name: 'Walsall', badge: 'https://img.sofascore.com/api/v1/team/26/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-85', name: 'Fleetwood Town', badge: 'https://img.sofascore.com/api/v1/team/23959/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-86', name: 'Accrington Stanley', badge: 'https://img.sofascore.com/api/v1/team/187/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-87', name: 'Gillingham', badge: 'https://img.sofascore.com/api/v1/team/20/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-88', name: 'Cheltenham Town', badge: 'https://img.sofascore.com/api/v1/team/69/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-89', name: 'Shrewsbury Town', badge: 'https://img.sofascore.com/api/v1/team/82/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-90', name: 'Newport County', badge: 'https://img.sofascore.com/api/v1/team/79/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-91', name: 'Tranmere Rovers', badge: 'https://img.sofascore.com/api/v1/team/51/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-92', name: 'Crawley Town', badge: 'https://img.sofascore.com/api/v1/team/4875/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-93', name: 'Harrogate Town', badge: 'https://img.sofascore.com/api/v1/team/159/image', country: 'ENG', type: TeamType.CLUB, tags: [] },
  { id: 'ENG-94', name: 'Barrow AFC', badge: 'https://img.sofascore.com/api/v1/team/97/image', country: 'ENG', type: TeamType.CLUB, tags: [] },
  { id: 'ENG-95', name: 'Rochdale', badge: 'https://img.sofascore.com/api/v1/team/103/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
  { id: 'ENG-96', name: 'York City', badge: 'https://img.sofascore.com/api/v1/team/73/image', country: 'ENG', type: TeamType.CLUB, tags: [TeamTags.EFL_TWO_26] },
];
