export const ENGLAND_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'ENG-1', name: 'QPR', badge: 'https://img.sofascore.com/api/v1/team/1/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-2', name: 'Portsmouth', badge: 'https://img.sofascore.com/api/v1/team/2/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-3', name: 'Wolves', badge: 'https://img.sofascore.com/api/v1/team/3/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-4', name: 'Bolton', badge: 'https://img.sofascore.com/api/v1/team/5/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-5', name: 'Burnley', badge: 'https://img.sofascore.com/api/v1/team/6/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-6', name: 'Crystal Palace', badge: 'https://img.sofascore.com/api/v1/team/7/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-7', name: 'West Brom', badge: 'https://img.sofascore.com/api/v1/team/8/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-8', name: 'Birmingham', badge: 'https://img.sofascore.com/api/v1/team/9/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-9', name: 'Coventry', badge: 'https://img.sofascore.com/api/v1/team/11/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-10', name: 'Rotherham', badge: 'https://img.sofascore.com/api/v1/team/13/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-11', name: 'Nottingham Forest', badge: 'https://img.sofascore.com/api/v1/team/14/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-12', name: 'Sheffield Utd', badge: 'https://img.sofascore.com/api/v1/team/15/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-13', name: 'Manchester City', badge: 'https://img.sofascore.com/api/v1/team/17/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-14', name: 'Barnsley', badge: 'https://img.sofascore.com/api/v1/team/23/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-15', name: 'Watford', badge: 'https://img.sofascore.com/api/v1/team/24/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-16', name: 'Derby County', badge: 'https://img.sofascore.com/api/v1/team/27/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-17', name: 'Reading', badge: 'https://img.sofascore.com/api/v1/team/28/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-18', name: 'Brighton', badge: 'https://img.sofascore.com/api/v1/team/30/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-19', name: 'Leicester', badge: 'https://img.sofascore.com/api/v1/team/31/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-20', name: 'Ipswich Town', badge: 'https://img.sofascore.com/api/v1/team/32/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-21', name: 'Tottenham ', badge: 'https://img.sofascore.com/api/v1/team/33/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-22', name: 'Leeds', badge: 'https://img.sofascore.com/api/v1/team/34/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-23', name: 'Manchester United', badge: 'https://img.sofascore.com/api/v1/team/35/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-24', name: 'Middlesbrough', badge: 'https://img.sofascore.com/api/v1/team/36/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-25', name: 'West Ham', badge: 'https://img.sofascore.com/api/v1/team/37/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-26', name: 'Chelsea', badge: 'https://img.sofascore.com/api/v1/team/38/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-27', name: 'Newcastle', badge: 'https://img.sofascore.com/api/v1/team/39/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-28', name: 'Aston Villa', badge: 'https://img.sofascore.com/api/v1/team/40/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-29', name: 'Sunderland', badge: 'https://img.sofascore.com/api/v1/team/41/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-30', name: 'Arsenal', badge: 'https://img.sofascore.com/api/v1/team/42/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-31', name: 'Fulham', badge: 'https://img.sofascore.com/api/v1/team/43/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-32', name: 'Liverpool', badge: 'https://img.sofascore.com/api/v1/team/44/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-33', name: 'Southampton', badge: 'https://img.sofascore.com/api/v1/team/45/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-34', name: 'Blackburn', badge: 'https://img.sofascore.com/api/v1/team/46/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-35', name: 'Wigan', badge: 'https://img.sofascore.com/api/v1/team/49/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-36', name: 'Brentford', badge: 'https://img.sofascore.com/api/v1/team/50/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-37', name: 'Northampton', badge: 'https://img.sofascore.com/api/v1/team/57/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-38', name: 'Bristol City', badge: 'https://img.sofascore.com/api/v1/team/58/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-39', name: 'Huddersfield', badge: 'https://img.sofascore.com/api/v1/team/59/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-40', name: 'Bournemouth', badge: 'https://img.sofascore.com/api/v1/team/60/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-41', name: 'Cambridge', badge: 'https://img.sofascore.com/api/v1/team/63/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-42', name: 'Mansfield', badge: 'https://img.sofascore.com/api/v1/team/70/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-43', name: 'Plymouth', badge: 'https://img.sofascore.com/api/v1/team/71/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-44', name: 'Luton', badge: 'https://img.sofascore.com/api/v1/team/72/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-45', name: 'Bristol Rovers', badge: 'https://img.sofascore.com/api/v1/team/76/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-46', name: 'Carlisle', badge: 'https://img.sofascore.com/api/v1/team/78/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-47', name: 'Hull', badge: 'https://img.sofascore.com/api/v1/team/96/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-48', name: 'Norwich', badge: 'https://img.sofascore.com/api/v1/team/263/image', country: 'ENG', type: TeamType.CLUB },
  { id: 'ENG-49', name: 'Rochester United', badge: 'https://img.sofascore.com/api/v1/team/206439/image', country: 'ENG', type: TeamType.CLUB },
];
