export const FRANCE_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'FRA-1', name: 'Olympique de Marseille', badge: 'https://img.sofascore.com/api/v1/team/1641/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-2', name: 'Montpellier', badge: 'https://img.sofascore.com/api/v1/team/1642/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-3', name: 'Lille', badge: 'https://img.sofascore.com/api/v1/team/1643/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-4', name: 'Paris', badge: 'https://img.sofascore.com/api/v1/team/1644/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-5', name: 'Bordeaux', badge: 'https://img.sofascore.com/api/v1/team/1645/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-6', name: 'Auxerre', badge: 'https://img.sofascore.com/api/v1/team/1646/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-7', name: 'Nantes', badge: 'https://img.sofascore.com/api/v1/team/1647/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-8', name: 'Lyon', badge: 'https://img.sofascore.com/api/v1/team/1649/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-9', name: 'Strasbourg', badge: 'https://img.sofascore.com/api/v1/team/1659/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-10', name: 'Nice', badge: 'https://img.sofascore.com/api/v1/team/1661/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-11', name: 'Le Havre', badge: 'https://img.sofascore.com/api/v1/team/1662/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-12', name: 'Saint-Étienne', badge: 'https://img.sofascore.com/api/v1/team/1678/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-13', name: 'Toulouse', badge: 'https://img.sofascore.com/api/v1/team/1681/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-14', name: 'Stade de Reims', badge: 'https://img.sofascore.com/api/v1/team/1682/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-15', name: 'Brest', badge: 'https://img.sofascore.com/api/v1/team/1715/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-16', name: 'Lens', badge: 'https://img.sofascore.com/api/v1/team/1648/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-17', name: 'Rennes', badge: 'https://img.sofascore.com/api/v1/team/1658/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-18', name: 'AS Monaco', badge: 'https://img.sofascore.com/api/v1/team/1653/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-19', name: 'Lorient', badge: 'https://img.sofascore.com/api/v1/team/1656/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-20', name: 'Paris FC', badge: 'https://img.sofascore.com/api/v1/team/6070/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-21', name: 'Angers', badge: 'https://img.sofascore.com/api/v1/team/1684/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
  { id: 'FRA-22', name: 'Metz', badge: 'https://img.sofascore.com/api/v1/team/1651/image', country: 'FRA', type: TeamType.CLUB, tags: [] },
];
