export const GERMANY_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'DEU-1', name: 'Wolfsburg', badge: 'https://img.sofascore.com/api/v1/team/2524/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-2', name: 'St. Pauli', badge: 'https://img.sofascore.com/api/v1/team/2526/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-3', name: 'Borussia M\'gladbach', badge: 'https://img.sofascore.com/api/v1/team/2527/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-4', name: 'Hertha', badge: 'https://img.sofascore.com/api/v1/team/2528/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-5', name: 'Schalke 04', badge: 'https://img.sofascore.com/api/v1/team/2530/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-6', name: 'Werder Bremen', badge: 'https://img.sofascore.com/api/v1/team/2534/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-7', name: 'Freiburg', badge: 'https://img.sofascore.com/api/v1/team/2538/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-8', name: 'Hannover', badge: 'https://img.sofascore.com/api/v1/team/2541/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-9', name: 'Bochum', badge: 'https://img.sofascore.com/api/v1/team/2542/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-10', name: 'Union Berlin', badge: 'https://img.sofascore.com/api/v1/team/2547/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-11', name: 'Mainz 05', badge: 'https://img.sofascore.com/api/v1/team/2556/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-12', name: 'Hoffenheim', badge: 'https://img.sofascore.com/api/v1/team/2569/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-13', name: 'Holstein Kiel', badge: 'https://img.sofascore.com/api/v1/team/2573/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-14', name: 'Darmstadt', badge: 'https://img.sofascore.com/api/v1/team/2576/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-15', name: 'Augsburg', badge: 'https://img.sofascore.com/api/v1/team/2600/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-16', name: 'Köln', badge: 'https://img.sofascore.com/api/v1/team/2671/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-17', name: 'Bayern München', badge: 'https://img.sofascore.com/api/v1/team/2672/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-18', name: 'Borussia Dortmund', badge: 'https://img.sofascore.com/api/v1/team/2673/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-19', name: 'Eintracht Frankfurt', badge: 'https://img.sofascore.com/api/v1/team/2674/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-20', name: 'Kaiserslautern', badge: 'https://img.sofascore.com/api/v1/team/2675/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-21', name: 'Stuttgart', badge: 'https://img.sofascore.com/api/v1/team/2677/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-22', name: 'Leverkusen', badge: 'https://img.sofascore.com/api/v1/team/2681/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-23', name: 'Heidenheim', badge: 'https://img.sofascore.com/api/v1/team/5885/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-24', name: 'Leipzig', badge: 'https://img.sofascore.com/api/v1/team/36360/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-25', name: 'Hertha Munich', badge: 'https://img.sofascore.com/api/v1/team/289586/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-26', name: 'Hamburger SV', badge: 'https://img.sofascore.com/api/v1/team/2676/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-27', name: 'Elversberg', badge: 'https://img.sofascore.com/api/v1/team/2598/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-28', name: 'Paderborn 07', badge: 'https://img.sofascore.com/api/v1/team/2561/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-29', name: 'Karlsruher SC', badge: 'https://img.sofascore.com/api/v1/team/2553/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-30', name: 'Nürnberg', badge: 'https://img.sofascore.com/api/v1/team/2523/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-31', name: 'Dresden', badge: 'https://img.sofascore.com/api/v1/team/2595/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-32', name: 'Arminia Bielefeld', badge: 'https://img.sofascore.com/api/v1/team/2540/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-33', name: 'Magdeburg', badge: 'https://img.sofascore.com/api/v1/team/2591/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-34', name: 'Braunschweig', badge: 'https://img.sofascore.com/api/v1/team/2557/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-35', name: 'Fortuna Düsseldorf', badge: 'https://img.sofascore.com/api/v1/team/2588/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-36', name: 'Greuther Fürth', badge: 'https://img.sofascore.com/api/v1/team/2551/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
  { id: 'DEU-37', name: 'Preußen Münster', badge: 'https://img.sofascore.com/api/v1/team/2590/image', country: 'DEU', type: TeamType.CLUB, tags: [] },
];
