export const GREECE_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'GRC-1', name: 'Olympiacos', badge: 'https://img.sofascore.com/api/v1/team/3245/image', country: 'GRC', type: TeamType.CLUB, tags: [] },
  { id: 'GRC-2', name: 'Panathinaikos', badge: 'https://img.sofascore.com/api/v1/team/3248/image', country: 'GRC', type: TeamType.CLUB, tags: [] },
  { id: 'GRC-3', name: 'AEK Athens', badge: 'https://img.sofascore.com/api/v1/team/3250/image', country: 'GRC', type: TeamType.CLUB, tags: [] },
  { id: 'GRC-4', name: 'PAOK', badge: 'https://img.sofascore.com/api/v1/team/3251/image', country: 'GRC', type: TeamType.CLUB, tags: [] },
  { id: 'GRC-5', name: 'Levadiakos', badge: 'https://img.sofascore.com/api/v1/team/5063/image', country: 'GRC', type: TeamType.CLUB, tags: [] },
  { id: 'GRC-6', name: 'OFI Crete', badge: 'https://img.sofascore.com/api/v1/team/3241/image', country: 'GRC', type: TeamType.CLUB, tags: [] },
  { id: 'GRC-7', name: 'Volos', badge: 'https://img.sofascore.com/api/v1/team/267459/image', country: 'GRC', type: TeamType.CLUB, tags: [] },
  { id: 'GRC-8', name: 'Aris', badge: 'https://img.sofascore.com/api/v1/team/3252/image', country: 'GRC', type: TeamType.CLUB, tags: [] },
  { id: 'GRC-9', name: 'Atromitos', badge: 'https://img.sofascore.com/api/v1/team/5062/image', country: 'GRC', type: TeamType.CLUB, tags: [] },
  { id: 'GRC-10', name: 'Kifisia', badge: 'https://img.sofascore.com/api/v1/team/120224/image', country: 'GRC', type: TeamType.CLUB, tags: [] },
  { id: 'GRC-11', name: 'Panetolikos', badge: 'https://img.sofascore.com/api/v1/team/7004/image', country: 'GRC', type: TeamType.CLUB, tags: [] },
  { id: 'GRC-12', name: 'AEL Novibet', badge: 'https://img.sofascore.com/api/v1/team/3265/image', country: 'GRC', type: TeamType.CLUB, tags: [] },
  { id: 'GRC-13', name: 'Panserraikos', badge: 'https://img.sofascore.com/api/v1/team/6347/image', country: 'GRC', type: TeamType.CLUB, tags: [] },
  { id: 'GRC-14', name: 'Asteras', badge: 'https://img.sofascore.com/api/v1/team/6342/image', country: 'GRC', type: TeamType.CLUB, tags: [] },
];
