export const ITALY_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'ITA-1', name: 'Bologna', badge: 'https://img.sofascore.com/api/v1/team/2685/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-2', name: 'Atalanta', badge: 'https://img.sofascore.com/api/v1/team/2686/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-3', name: 'Juventus', badge: 'https://img.sofascore.com/api/v1/team/2687/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-4', name: 'Venezia', badge: 'https://img.sofascore.com/api/v1/team/2688/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-5', name: 'Lecce', badge: 'https://img.sofascore.com/api/v1/team/2689/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-6', name: 'Parma', badge: 'https://img.sofascore.com/api/v1/team/2690/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-7', name: 'Milan', badge: 'https://img.sofascore.com/api/v1/team/2692/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-8', name: 'Fiorentina', badge: 'https://img.sofascore.com/api/v1/team/2693/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-9', name: 'Udinese', badge: 'https://img.sofascore.com/api/v1/team/2695/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-10', name: 'Torino', badge: 'https://img.sofascore.com/api/v1/team/2696/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-11', name: 'Inter', badge: 'https://img.sofascore.com/api/v1/team/2697/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-12', name: 'Lazio', badge: 'https://img.sofascore.com/api/v1/team/2699/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-13', name: 'Verona', badge: 'https://img.sofascore.com/api/v1/team/2701/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-14', name: 'Roma', badge: 'https://img.sofascore.com/api/v1/team/2702/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-15', name: 'Como', badge: 'https://img.sofascore.com/api/v1/team/2704/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-16', name: 'Empoli', badge: 'https://img.sofascore.com/api/v1/team/2705/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-17', name: 'Ascoli', badge: 'https://img.sofascore.com/api/v1/team/2707/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-18', name: 'Sampdoria', badge: 'https://img.sofascore.com/api/v1/team/2711/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-19', name: 'Genoa', badge: 'https://img.sofascore.com/api/v1/team/2713/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-20', name: 'Napoli', badge: 'https://img.sofascore.com/api/v1/team/2714/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-21', name: 'Palermo', badge: 'https://img.sofascore.com/api/v1/team/2715/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-22', name: 'Cagliari', badge: 'https://img.sofascore.com/api/v1/team/2719/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-23', name: 'Livorno', badge: 'https://img.sofascore.com/api/v1/team/2726/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-24', name: 'SPAL', badge: 'https://img.sofascore.com/api/v1/team/113755/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-25', name: 'Benevento', badge: 'https://img.sofascore.com/api/v1/team/2759/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-26', name: 'Sassuolo', badge: 'https://img.sofascore.com/api/v1/team/2793/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-27', name: 'Chievo Verona', badge: 'https://img.sofascore.com/api/v1/team/396932/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-28', name: 'Cremonese', badge: 'https://img.sofascore.com/api/v1/team/2761/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-29', name: 'Pisa', badge: 'https://img.sofascore.com/api/v1/team/2737/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-30', name: 'Frosinone', badge: 'https://img.sofascore.com/api/v1/team/2801/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-31', name: 'Monza', badge: 'https://img.sofascore.com/api/v1/team/2729/image', country: 'ITA', type: TeamType.CLUB, tags: [TeamTags.ITALIAN_SERIE_A_26] },
  { id: 'ITA-32', name: 'Catanzaro', badge: 'https://img.sofascore.com/api/v1/team/2796/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-33', name: 'Modena', badge: 'https://img.sofascore.com/api/v1/team/2706/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-34', name: 'Juve Stabia', badge: 'https://img.sofascore.com/api/v1/team/5324/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-35', name: 'Avellino', badge: 'https://img.sofascore.com/api/v1/team/2730/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-36', name: 'Mantova', badge: 'https://img.sofascore.com/api/v1/team/2770/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-37', name: 'Padova', badge: 'https://img.sofascore.com/api/v1/team/2741/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-38', name: 'Cesena', badge: 'https://img.sofascore.com/api/v1/team/2742/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-39', name: 'Carrarese', badge: 'https://img.sofascore.com/api/v1/team/2745/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-40', name: 'Entella', badge: 'https://img.sofascore.com/api/v1/team/43680/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-41', name: 'Südtirol', badge: 'https://img.sofascore.com/api/v1/team/2760/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-42', name: 'Bari', badge: 'https://img.sofascore.com/api/v1/team/2712/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-43', name: 'Reggiana', badge: 'https://img.sofascore.com/api/v1/team/24516/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-44', name: 'Spezia', badge: 'https://img.sofascore.com/api/v1/team/2735/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-45', name: 'Pescara', badge: 'https://img.sofascore.com/api/v1/team/7935/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
];
