export const ITALY_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'ITA-1', name: 'Bologna', badge: 'https://img.sofascore.com/api/v1/team/2685/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-2', name: 'Atalanta', badge: 'https://img.sofascore.com/api/v1/team/2686/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-3', name: 'Juventus', badge: 'https://img.sofascore.com/api/v1/team/2687/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-4', name: 'Venezia', badge: 'https://img.sofascore.com/api/v1/team/2688/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-5', name: 'Lecce', badge: 'https://img.sofascore.com/api/v1/team/2689/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-6', name: 'Parma', badge: 'https://img.sofascore.com/api/v1/team/2690/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-7', name: 'Milan', badge: 'https://img.sofascore.com/api/v1/team/2692/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-8', name: 'Fiorentina', badge: 'https://img.sofascore.com/api/v1/team/2693/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-9', name: 'Udinese', badge: 'https://img.sofascore.com/api/v1/team/2695/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-10', name: 'Torino', badge: 'https://img.sofascore.com/api/v1/team/2696/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-11', name: 'Inter', badge: 'https://img.sofascore.com/api/v1/team/2697/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-12', name: 'Lazio', badge: 'https://img.sofascore.com/api/v1/team/2699/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-13', name: 'Verona', badge: 'https://img.sofascore.com/api/v1/team/2701/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-14', name: 'Roma', badge: 'https://img.sofascore.com/api/v1/team/2702/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-15', name: 'Como', badge: 'https://img.sofascore.com/api/v1/team/2704/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-16', name: 'Empoli', badge: 'https://img.sofascore.com/api/v1/team/2705/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-17', name: 'Ascoli', badge: 'https://img.sofascore.com/api/v1/team/2707/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-18', name: 'Sampdoria', badge: 'https://img.sofascore.com/api/v1/team/2711/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-19', name: 'Genoa', badge: 'https://img.sofascore.com/api/v1/team/2713/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-20', name: 'Napoli', badge: 'https://img.sofascore.com/api/v1/team/2714/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-21', name: 'Palermo', badge: 'https://img.sofascore.com/api/v1/team/2715/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-22', name: 'Cagliari', badge: 'https://img.sofascore.com/api/v1/team/2719/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-23', name: 'Livorno', badge: 'https://img.sofascore.com/api/v1/team/2726/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-24', name: 'SPAL', badge: 'https://img.sofascore.com/api/v1/team/113755/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-25', name: 'Benevento', badge: 'https://img.sofascore.com/api/v1/team/2759/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-26', name: 'Sassuolo', badge: 'https://img.sofascore.com/api/v1/team/2793/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
  { id: 'ITA-27', name: 'Chievo Verona', badge: 'https://img.sofascore.com/api/v1/team/396932/image', country: 'ITA', type: TeamType.CLUB, tags: [] },
];
