export const JAPAN_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'JPN-1', name: 'Kashima Antlers', badge: 'https://img.sofascore.com/api/v1/team/3134/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-2', name: 'Urawa Reds', badge: 'https://img.sofascore.com/api/v1/team/3145/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-3', name: 'Tokyo', badge: 'https://img.sofascore.com/api/v1/team/3147/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-4', name: 'Machida Zelvia', badge: 'https://img.sofascore.com/api/v1/team/44409/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-5', name: 'Tokyo Verdy', badge: 'https://img.sofascore.com/api/v1/team/3139/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-6', name: 'Kawasaki', badge: 'https://img.sofascore.com/api/v1/team/5127/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-7', name: 'Mito Hollyhock', badge: 'https://img.sofascore.com/api/v1/team/21901/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-8', name: 'Yokohama FM', badge: 'https://img.sofascore.com/api/v1/team/3137/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-9', name: 'Chiba', badge: 'https://img.sofascore.com/api/v1/team/3144/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-10', name: 'Kashiwa', badge: 'https://img.sofascore.com/api/v1/team/3140/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-11', name: 'Nagoya', badge: 'https://img.sofascore.com/api/v1/team/3136/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-12', name: 'Vissel Kobe', badge: 'https://img.sofascore.com/api/v1/team/3146/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-13', name: 'Gamba Osaka', badge: 'https://img.sofascore.com/api/v1/team/3138/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-14', name: 'Shimizu', badge: 'https://img.sofascore.com/api/v1/team/3133/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-15', name: 'Cerezo Osaka', badge: 'https://img.sofascore.com/api/v1/team/3141/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-16', name: 'Sanfrecce', badge: 'https://img.sofascore.com/api/v1/team/3135/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-17', name: 'Fukuoka', badge: 'https://img.sofascore.com/api/v1/team/3143/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-18', name: 'Kyoto Sanga', badge: 'https://img.sofascore.com/api/v1/team/3149/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-19', name: 'Okayama', badge: 'https://img.sofascore.com/api/v1/team/34034/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
  { id: 'JPN-20', name: 'Nagasaki', badge: 'https://img.sofascore.com/api/v1/team/38154/image', country: 'JPN', type: TeamType.CLUB, tags: [] },
];
