export const NATIONAL_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'NAT-1', name: 'Albânia', badge: '/images/countries/albania.svg', country: 'ALB', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-2', name: 'Argélia', badge: '/images/countries/algeria.svg', country: 'DZA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-3', name: 'Andorra', badge: '/images/countries/andorra.svg', country: 'AND', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-4', name: 'Angola', badge: '/images/countries/angola.svg', country: 'AGO', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-5', name: 'Argentina', badge: '/images/countries/argentina.svg', country: 'ARG', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-6', name: 'Armênia', badge: '/images/countries/armenia.svg', country: 'ARM', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-7', name: 'Austrália', badge: '/images/countries/australia.svg', country: 'AUS', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-8', name: 'Áustria', badge: '/images/countries/austria.svg', country: 'AUT', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-9', name: 'Azerbaijão', badge: '/images/countries/azerbaijan.svg', country: 'AZE', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-10', name: 'Bahamas', badge: '/images/countries/bahamas.svg', country: 'BHS', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-11', name: 'Bangladesh', badge: '/images/countries/bangladesh.svg', country: 'BGD', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-12', name: 'Bielorrússia', badge: '/images/countries/belarus.svg', country: 'BLR', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-13', name: 'Bélgica', badge: '/images/countries/belgium.svg', country: 'BEL', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-14', name: 'Benim', badge: '/images/countries/benin.svg', country: 'BEN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-15', name: 'Bolívia', badge: '/images/countries/bolivia.svg', country: 'BOL', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-16', name: 'Bósnia e Herzegovina', badge: '/images/countries/bosnia-and-herzegovina.svg', country: 'BIH', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-17', name: 'Botswana', badge: '/images/countries/botswana.svg', country: 'BWA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-18', name: 'Brasil', badge: '/images/countries/brazil.svg', country: 'BRA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-19', name: 'Bulgária', badge: '/images/countries/bulgaria.svg', country: 'BGR', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-20', name: 'Burquina Fasso', badge: '/images/countries/burkina-faso.svg', country: 'BFA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-21', name: 'Burundi', badge: '/images/countries/burundi.svg', country: 'BDI', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-22', name: 'Camarões', badge: '/images/countries/cameroon.svg', country: 'CMR', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-23', name: 'Canadá', badge: '/images/countries/canada.svg', country: 'CAN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-24', name: 'Cabo Verde', badge: '/images/countries/cape-verde.svg', country: 'CPV', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-25', name: 'Ilhas Caimã', badge: '/images/countries/cayman-islands.svg', country: 'CYM', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-26', name: 'República Centro-Africana', badge: '/images/countries/central-african-republic.svg', country: 'CAF', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-27', name: 'Chade', badge: '/images/countries/chad.svg', country: 'TCD', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-28', name: 'Chile', badge: '/images/countries/chile.svg', country: 'CHL', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-29', name: 'China', badge: '/images/countries/china.svg', country: 'CHN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-30', name: 'Colômbia', badge: '/images/countries/colombia.svg', country: 'COL', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-31', name: 'Comores', badge: '/images/countries/comoros.svg', country: 'COM', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-32', name: 'República do Congo', badge: '/images/countries/congo.svg', country: 'COG', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-33', name: 'Costa Rica', badge: '/images/countries/costa-rica.svg', country: 'CRI', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-34', name: 'Costa do Marfim', badge: '/images/countries/cote-divoire.svg', country: 'CIV', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-35', name: 'Croácia', badge: '/images/countries/croatia.svg', country: 'HRV', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-36', name: 'Cuba', badge: '/images/countries/cuba.svg', country: 'CUB', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-37', name: 'Chipre', badge: '/images/countries/cyprus.svg', country: 'CYP', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-38', name: 'República Tcheca', badge: '/images/countries/czechia.svg', country: 'CZE', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-39', name: 'Dinamarca', badge: '/images/countries/denmark.svg', country: 'DNK', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-40', name: 'Djibuti', badge: '/images/countries/djibouti.svg', country: 'DJI', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-41', name: 'República Dominicana', badge: '/images/countries/dominican-republic.svg', country: 'DOM', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-42', name: 'Equador', badge: '/images/countries/ecuador.svg', country: 'ECU', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-43', name: 'Egito', badge: '/images/countries/egypt.svg', country: 'EGY', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-44', name: 'El Salvador', badge: '/images/countries/el-salvador.svg', country: 'SLV', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-45', name: 'Inglaterra', badge: '/images/countries/england.svg', country: 'ENG', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-46', name: 'Guiné Equatorial', badge: '/images/countries/equatorial-guinea.svg', country: 'GNQ', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-47', name: 'Eritreia', badge: '/images/countries/eritrea.svg', country: 'ERI', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-48', name: 'Estônia', badge: '/images/countries/estonia.svg', country: 'EST', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-49', name: 'Essuatíni', badge: '/images/countries/eswatini.svg', country: 'SWZ', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-50', name: 'Etiópia', badge: '/images/countries/ethiopia.svg', country: 'ETH', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-51', name: 'Ilhas Faroe', badge: '/images/countries/faroe-islands.svg', country: 'FRO', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-52', name: 'Finlândia', badge: '/images/countries/finland.svg', country: 'FIN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-53', name: 'França', badge: '/images/countries/france.svg', country: 'FRA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-54', name: 'Gabão', badge: '/images/countries/gabon.svg', country: 'GAB', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-55', name: 'Gâmbia', badge: '/images/countries/gambia.svg', country: 'GMB', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-56', name: 'Geórgia', badge: '/images/countries/georgia.svg', country: 'GEO', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-57', name: 'Alemanha', badge: '/images/countries/germany.svg', country: 'DEU', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-58', name: 'Gana', badge: '/images/countries/ghana.svg', country: 'GHA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-59', name: 'Gibraltar', badge: '/images/countries/gibraltar.svg', country: 'GIB', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-60', name: 'Grécia', badge: '/images/countries/greece.svg', country: 'GRC', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-61', name: 'Guatemala', badge: '/images/countries/guatemala.svg', country: 'GTM', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-62', name: 'Guiné', badge: '/images/countries/guinea.svg', country: 'GIN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-63', name: 'Guiné-Bissau', badge: '/images/countries/guinea-bissau.svg', country: 'GNB', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-64', name: 'Haiti', badge: '/images/countries/haiti.svg', country: 'HTI', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-65', name: 'Honduras', badge: '/images/countries/honduras.svg', country: 'HND', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-66', name: 'Hungria', badge: '/images/countries/hungary.svg', country: 'HUN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-67', name: 'Islândia', badge: '/images/countries/iceland.svg', country: 'ISL', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-68', name: 'Índia', badge: '/images/countries/india.svg', country: 'IND', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-69', name: 'Indonésia', badge: '/images/countries/indonesia.svg', country: 'IDN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-70', name: 'Irã', badge: '/images/countries/iran.svg', country: 'IRN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-71', name: 'Iraque', badge: '/images/countries/iraq.svg', country: 'IRQ', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-72', name: 'Irlanda', badge: '/images/countries/ireland.svg', country: 'IRL', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-73', name: 'Israel', badge: '/images/countries/israel.svg', country: 'ISR', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-74', name: 'Itália', badge: '/images/countries/italy.svg', country: 'ITA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-75', name: 'Jamaica', badge: '/images/countries/jamaica.svg', country: 'JAM', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-76', name: 'Japão', badge: '/images/countries/japan.svg', country: 'JPN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-77', name: 'Cazaquistão', badge: '/images/countries/kazakhstan.svg', country: 'KAZ', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-78', name: 'Quênia', badge: '/images/countries/kenya.svg', country: 'KEN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-79', name: 'Kosovo', badge: '/images/countries/kosovo.svg', country: 'KOS', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-80', name: 'Letônia', badge: '/images/countries/latvia.svg', country: 'LVA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-81', name: 'Líbano', badge: '/images/countries/lebanon.svg', country: 'LBN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-82', name: 'Lesoto', badge: '/images/countries/lesotho.svg', country: 'LSO', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-83', name: 'Libéria', badge: '/images/countries/liberia.svg', country: 'LBR', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-84', name: 'Líbia', badge: '/images/countries/libya.svg', country: 'LBY', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-85', name: 'Liechtenstein', badge: '/images/countries/liechtenstein.svg', country: 'LIE', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-86', name: 'Lituânia', badge: '/images/countries/lithuania.svg', country: 'LTU', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-87', name: 'Luxemburgo', badge: '/images/countries/luxembourg.svg', country: 'LUX', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-88', name: 'Madagascar', badge: '/images/countries/madagascar.svg', country: 'MDG', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-89', name: 'Malawi', badge: '/images/countries/malawi.svg', country: 'MWI', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-90', name: 'Malásia', badge: '/images/countries/malaysia.svg', country: 'MIS', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-91', name: 'Mali', badge: '/images/countries/mali.svg', country: 'MLI', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-92', name: 'Malta', badge: '/images/countries/malta.svg', country: 'MLT', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-93', name: 'Mauritânia', badge: '/images/countries/mauritania.svg', country: 'MRT', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-94', name: 'Ilhas Maurícias', badge: '/images/countries/mauritius.svg', country: 'MUS', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-95', name: 'México', badge: '/images/countries/mexico.svg', country: 'MEX', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-96', name: 'Moldávia', badge: '/images/countries/moldova.svg', country: 'MDA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-97', name: 'Mongólia', badge: '/images/countries/mongolia.svg', country: 'MNG', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-98', name: 'Montenegro', badge: '/images/countries/montenegro.svg', country: 'MNE', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-99', name: 'Monserrate', badge: '/images/countries/montserrat.svg', country: 'MSR', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-100', name: 'Marrocos', badge: '/images/countries/morocco.svg', country: 'MAR', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-101', name: 'Moçambique', badge: '/images/countries/mozambique.svg', country: 'MOZ', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-102', name: 'Namíbia', badge: '/images/countries/namibia.svg', country: 'NAM', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-103', name: 'Nauru', badge: '/images/countries/nauru.svg', country: 'NRU', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-104', name: 'Holanda', badge: '/images/countries/netherlands.svg', country: 'NLD', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-105', name: 'Nova Caledônia', badge: '/images/countries/new-caledonia.svg', country: 'NCL', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-106', name: 'Nova Zelândia', badge: '/images/countries/new-zealand.svg', country: 'NZL', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-107', name: 'Nicarágua', badge: '/images/countries/nicaragua.svg', country: 'NIC', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-108', name: 'Níger', badge: '/images/countries/niger.svg', country: 'NER', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-109', name: 'Nigéria', badge: '/images/countries/nigeria.svg', country: 'NGA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-110', name: 'Irlanda do Norte', badge: '/images/countries/northern-ireland.png', country: 'NIR', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-111', name: 'Macedônia do Norte', badge: '/images/countries/north-macedonia.svg', country: 'MKD', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-112', name: 'Noruega', badge: '/images/countries/norway.svg', country: 'NOR', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-113', name: 'Paquistão', badge: '/images/countries/pakistan.svg', country: 'PAK', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-114', name: 'Panamá', badge: '/images/countries/panama.svg', country: 'PAN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-115', name: 'Paraguai', badge: '/images/countries/paraguay.svg', country: 'PRY', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-116', name: 'Peru', badge: '/images/countries/peru.svg', country: 'PER', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-117', name: 'Filipinas', badge: '/images/countries/philippines.svg', country: 'PHL', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-118', name: 'Polônia', badge: '/images/countries/poland.svg', country: 'POL', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-119', name: 'Portugal', badge: '/images/countries/portugal.svg', country: 'PRT', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-120', name: 'Catar', badge: '/images/countries/qatar.svg', country: 'QAT', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-121', name: 'República Democrática do Congo', badge: '/images/countries/rd-congo.svg', country: 'COD', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-122', name: 'Romênia', badge: '/images/countries/romania.svg', country: 'ROU', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-123', name: 'Russia', badge: '/images/countries/russia.svg', country: 'RUS', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-124', name: 'Ruanda', badge: '/images/countries/rwanda.svg', country: 'RWA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-125', name: 'Samoa Americana', badge: '/images/countries/samoa.svg', country: 'ASM', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-126', name: 'San Marino', badge: '/images/countries/san-marino.svg', country: 'SMR', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-127', name: 'São Tomé e Príncipe', badge: '/images/countries/sao-tome-and-principe.svg', country: 'STP', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-128', name: 'Arábia Saudita', badge: '/images/countries/saudi-arabia.svg', country: 'SAU', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-129', name: 'Escócia', badge: '/images/countries/scotland.svg', country: 'SCT', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-130', name: 'Senegal', badge: '/images/countries/senegal.svg', country: 'SEN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-131', name: 'Sérvia', badge: '/images/countries/serbia.svg', country: 'SRB', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-132', name: 'Seychelles', badge: '/images/countries/seychelles.svg', country: 'SYC', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-133', name: 'Serra Leoa', badge: '/images/countries/sierra-leone.svg', country: 'SLE', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-134', name: 'Singapura', badge: '/images/countries/singapore.svg', country: 'SGP', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-135', name: 'Eslováquia', badge: '/images/countries/slovakia.svg', country: 'SVK', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-136', name: 'Eslovênia', badge: '/images/countries/slovenia.svg', country: 'SVN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-137', name: 'Ilhas Salomão', badge: '/images/countries/solomon-islands.svg', country: 'SLB', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-138', name: 'Somália', badge: '/images/countries/somalia.svg', country: 'SOM', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-139', name: 'África do Sul', badge: '/images/countries/south-africa.svg', country: 'ZAF', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-140', name: 'Coreia do Sul', badge: '/images/countries/south-korea.svg', country: 'KOR', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-141', name: 'Sudão do Sul', badge: '/images/countries/south-sudan.svg', country: 'SSD', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-142', name: 'Espanha', badge: '/images/countries/spain.svg', country: 'ESP', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-143', name: 'Sri Lanka', badge: '/images/countries/sri-lanka.svg', country: 'LKA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-144', name: 'São Cristóvão e Neves', badge: '/images/countries/st-kitts-and-nevis.svg', country: 'KNA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-145', name: 'Santa Lúcia', badge: '/images/countries/st-lucia.svg', country: 'LCA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-146', name: 'São Vicente e Granadinas', badge: '/images/countries/st-vincent-and-grenadines.svg', country: 'VCT', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-147', name: 'Sudão', badge: '/images/countries/sudan.svg', country: 'SDN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-148', name: 'Suriname', badge: '/images/countries/suriname.svg', country: 'SUR', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-149', name: 'Suécia', badge: '/images/countries/sweden.svg', country: 'SWE', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-150', name: 'Suíça', badge: '/images/countries/switzerland.svg', country: 'CHE', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-151', name: 'Tajiquistão', badge: '/images/countries/tajikistan.svg', country: 'TJK', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-152', name: 'Tanzânia', badge: '/images/countries/tanzania.svg', country: 'TZA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-153', name: 'Tailândia', badge: '/images/countries/thailand.svg', country: 'THA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-154', name: 'Togo', badge: '/images/countries/togo.svg', country: 'TGO', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-155', name: 'Trindade e Tobago', badge: '/images/countries/trinidad-and-tobago.svg', country: 'TTO', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-156', name: 'Tunísia', badge: '/images/countries/tunisia.svg', country: 'TUN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-157', name: 'Turquia', badge: '/images/countries/turkey.svg', country: 'TUR', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-158', name: 'Uganda', badge: '/images/countries/uganda.svg', country: 'UGA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-159', name: 'Ucrânia', badge: '/images/countries/ukraine.svg', country: 'UKR', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-160', name: 'Emirados Árabes Unidos', badge: '/images/countries/united-arab-emirates.svg', country: 'ARE', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-161', name: 'Estados Unidos', badge: '/images/countries/united-states.svg', country: 'USA', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-162', name: 'Uruguai', badge: '/images/countries/uruguay.svg', country: 'URY', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-163', name: 'Uzbequistão', badge: '/images/countries/uzbekistan.svg', country: 'UZB', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-164', name: 'Venezuela', badge: '/images/countries/venezuela.svg', country: 'VEN', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-165', name: 'Vietnã', badge: '/images/countries/vietnam.svg', country: 'VNM', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-166', name: 'País de Gales', badge: '/images/countries/wales.svg', country: 'WAL', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-167', name: 'Zâmbia', badge: '/images/countries/zambia.svg', country: 'ZMB', type: TeamType.NATIONAL, tags: [] },
  { id: 'NAT-168', name: 'Zimbabwe', badge: '/images/countries/zimbabwe.svg', country: 'ZWE', type: TeamType.NATIONAL, tags: [] },
];
