export const NETHERLANDS_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'NLD-1', name: 'PSV', badge: 'https://img.sofascore.com/api/v1/team/2952/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-2', name: 'Ajax', badge: 'https://img.sofascore.com/api/v1/team/2953/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-3', name: 'Feyenoord', badge: 'https://img.sofascore.com/api/v1/team/2959/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-4', name: 'Heerenveen', badge: 'https://img.sofascore.com/api/v1/team/2964/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-5', name: 'NEC Nijmegen', badge: 'https://img.sofascore.com/api/v1/team/2962/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-6', name: 'Twente', badge: 'https://img.sofascore.com/api/v1/team/2955/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-7', name: 'AZ', badge: 'https://img.sofascore.com/api/v1/team/2950/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-8', name: 'Utrecht', badge: 'https://img.sofascore.com/api/v1/team/2948/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-9', name: 'Sparta Rotterdam', badge: 'https://img.sofascore.com/api/v1/team/2960/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-10', name: 'Groningen', badge: 'https://img.sofascore.com/api/v1/team/2951/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-11', name: 'GA Eagles', badge: 'https://img.sofascore.com/api/v1/team/2979/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-12', name: 'Zwolle', badge: 'https://img.sofascore.com/api/v1/team/2971/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-13', name: 'Fortuna Sittard', badge: 'https://img.sofascore.com/api/v1/team/2957/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-14', name: 'Excelsior Rotterdam', badge: 'https://img.sofascore.com/api/v1/team/2967/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-15', name: 'Telstar', badge: 'https://img.sofascore.com/api/v1/team/2972/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-16', name: 'Volendam', badge: 'https://img.sofascore.com/api/v1/team/2968/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-17', name: 'NAC Breda', badge: 'https://img.sofascore.com/api/v1/team/2947/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
  { id: 'NLD-18', name: 'Heracles', badge: 'https://img.sofascore.com/api/v1/team/2977/image', country: 'NLD', type: TeamType.CLUB, tags: [] },
];
