export const SAUDI_ARABIA_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'SAU-1', name: 'Al-Hilal', badge: 'https://img.sofascore.com/api/v1/team/21895/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-2', name: 'Al-Nassr', badge: 'https://img.sofascore.com/api/v1/team/23400/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-3', name: 'Al-Ittihad', badge: 'https://img.sofascore.com/api/v1/team/34315/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-4', name: 'Al-Ahli', badge: 'https://img.sofascore.com/api/v1/team/34469/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-5', name: 'Al-Qadsiah', badge: 'https://img.sofascore.com/api/v1/team/56027/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-6', name: 'Al-Taawoun', badge: 'https://img.sofascore.com/api/v1/team/56021/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-7', name: 'Al-Ettifaq', badge: 'https://img.sofascore.com/api/v1/team/34318/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-8', name: 'Neom SC', badge: 'https://img.sofascore.com/api/v1/team/530631/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-9', name: 'Al-Fayha', badge: 'https://img.sofascore.com/api/v1/team/168094/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-10', name: 'Al-Hazem', badge: 'https://img.sofascore.com/api/v1/team/168086/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-11', name: 'Al-Khaleej', badge: 'https://img.sofascore.com/api/v1/team/167228/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-12', name: 'Al-Fateh', badge: 'https://img.sofascore.com/api/v1/team/56023/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-13', name: 'Al-Shabab', badge: 'https://img.sofascore.com/api/v1/team/34313/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-14', name: 'Al-Kholood', badge: 'https://img.sofascore.com/api/v1/team/269199/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-15', name: 'Damac', badge: 'https://img.sofascore.com/api/v1/team/204126/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-16', name: 'Al-Riyadh', badge: 'https://img.sofascore.com/api/v1/team/168088/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-17', name: 'Al-Okhdood', badge: 'https://img.sofascore.com/api/v1/team/336456/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
  { id: 'SAU-18', name: 'Al-Najma', badge: 'https://img.sofascore.com/api/v1/team/395831/image', country: 'SAU', type: TeamType.CLUB, tags: [] },
];
