export const SPAIN_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'ESP-1', name: 'Espanyol', badge: 'https://img.sofascore.com/api/v1/team/2814/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-2', name: 'Real Zaragoza', badge: 'https://img.sofascore.com/api/v1/team/2815/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-3', name: 'Real Betis', badge: 'https://img.sofascore.com/api/v1/team/2816/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-4', name: 'Barcelona', badge: 'https://img.sofascore.com/api/v1/team/2817/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-5', name: 'Villarreal', badge: 'https://img.sofascore.com/api/v1/team/2819/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-6', name: 'Osasuna', badge: 'https://img.sofascore.com/api/v1/team/2820/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-7', name: 'Celta Vigo', badge: 'https://img.sofascore.com/api/v1/team/2821/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-8', name: 'CD Tenerife', badge: 'https://img.sofascore.com/api/v1/team/2822/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-9', name: 'Real Sociedad', badge: 'https://img.sofascore.com/api/v1/team/2824/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-10', name: 'Athletic Club', badge: 'https://img.sofascore.com/api/v1/team/2825/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-11', name: 'Mallorca', badge: 'https://img.sofascore.com/api/v1/team/2826/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-12', name: 'Valencia', badge: 'https://img.sofascore.com/api/v1/team/2828/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-13', name: 'Real Madrid', badge: 'https://img.sofascore.com/api/v1/team/2829/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-14', name: 'Málaga', badge: 'https://img.sofascore.com/api/v1/team/2830/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-15', name: 'Real Valladolid', badge: 'https://img.sofascore.com/api/v1/team/2831/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-16', name: 'Deportivo La Coruña', badge: 'https://img.sofascore.com/api/v1/team/2832/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-17', name: 'Sevilla', badge: 'https://img.sofascore.com/api/v1/team/2833/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-18', name: 'Atlético Madrid', badge: 'https://img.sofascore.com/api/v1/team/2836/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-19', name: 'Eibar', badge: 'https://img.sofascore.com/api/v1/team/2839/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-20', name: 'Leganés', badge: 'https://img.sofascore.com/api/v1/team/2845/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-21', name: 'Elche', badge: 'https://img.sofascore.com/api/v1/team/2846/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-22', name: 'Levante', badge: 'https://img.sofascore.com/api/v1/team/2849/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-23', name: 'Córdoba', badge: 'https://img.sofascore.com/api/v1/team/2850/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-24', name: 'Almería', badge: 'https://img.sofascore.com/api/v1/team/2858/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-25', name: 'Getafe', badge: 'https://img.sofascore.com/api/v1/team/2859/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-26', name: 'Alavés', badge: 'https://img.sofascore.com/api/v1/team/2885/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-27', name: 'Cádiz', badge: 'https://img.sofascore.com/api/v1/team/4488/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-28', name: 'Las Palmas', badge: 'https://img.sofascore.com/api/v1/team/6577/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-29', name: 'Girona', badge: 'https://img.sofascore.com/api/v1/team/24264/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-30', name: 'Huesca', badge: 'https://img.sofascore.com/api/v1/team/24265/image', country: 'ESP', type: TeamType.CLUB },
  { id: 'ESP-31', name: 'Granada', badge: 'https://img.sofascore.com/api/v1/team/33779/image', country: 'ESP', type: TeamType.CLUB },
];
