export const UNITED_STATES_TEAM_LIST: Readonly<TeamDetails[]> = [
  { id: 'USA-1', name: 'LA Galaxy', badge: 'https://img.sofascore.com/api/v1/team/2513/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-2', name: 'Orlando City', badge: 'https://img.sofascore.com/api/v1/team/52237/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-3', name: 'Atlanta', badge: 'https://img.sofascore.com/api/v1/team/243211/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-4', name: 'Inter Miami', badge: 'https://img.sofascore.com/api/v1/team/337602/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-5', name: 'San Jose', badge: 'https://img.sofascore.com/api/v1/team/21825/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-6', name: 'Vancouver', badge: 'https://img.sofascore.com/api/v1/team/22010/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-7', name: 'Nashville', badge: 'https://img.sofascore.com/api/v1/team/337612/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-8', name: 'Los Angeles', badge: 'https://img.sofascore.com/api/v1/team/274650/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-9', name: 'Seattle', badge: 'https://img.sofascore.com/api/v1/team/22009/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-10', name: 'Minnesota', badge: 'https://img.sofascore.com/api/v1/team/41618/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-11', name: 'New England', badge: 'https://img.sofascore.com/api/v1/team/2511/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-12', name: 'Salt Lake', badge: 'https://img.sofascore.com/api/v1/team/5133/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-13', name: 'Chicago', badge: 'https://img.sofascore.com/api/v1/team/2505/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-14', name: 'Dallas', badge: 'https://img.sofascore.com/api/v1/team/2512/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-15', name: 'Houston', badge: 'https://img.sofascore.com/api/v1/team/2508/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-16', name: 'DC United', badge: 'https://img.sofascore.com/api/v1/team/2502/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-17', name: 'Cincinnati', badge: 'https://img.sofascore.com/api/v1/team/215167/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-18', name: 'Charlotte', badge: 'https://img.sofascore.com/api/v1/team/404108/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-19', name: 'Toronto', badge: 'https://img.sofascore.com/api/v1/team/7080/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-20', name: 'Colorado', badge: 'https://img.sofascore.com/api/v1/team/2510/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-21', name: 'Austin', badge: 'https://img.sofascore.com/api/v1/team/377973/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-22', name: 'NY City', badge: 'https://img.sofascore.com/api/v1/team/187643/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-23', name: 'San Diego FC', badge: 'https://img.sofascore.com/api/v1/team/1043961/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-24', name: 'Columbus', badge: 'https://img.sofascore.com/api/v1/team/2504/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-25', name: 'NY Red Bulls', badge: 'https://img.sofascore.com/api/v1/team/2506/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-26', name: 'Portland', badge: 'https://img.sofascore.com/api/v1/team/22007/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-27', name: 'Montréal', badge: 'https://img.sofascore.com/api/v1/team/22006/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-28', name: 'Philadelphia', badge: 'https://img.sofascore.com/api/v1/team/39833/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-29', name: 'St. Louis', badge: 'https://img.sofascore.com/api/v1/team/407803/image', country: 'USA', type: TeamType.CLUB, tags: [] },
  { id: 'USA-30', name: 'Kansas City', badge: 'https://img.sofascore.com/api/v1/team/2509/image', country: 'USA', type: TeamType.CLUB, tags: [] },
];
