export const Breakpoints = {
  LARGE_SMARTPHONE_UP: 375,
  TABLET_PORTRAIT_UP: 600,
  LARGE_TABLET_PORTRAIT_UP: 768,
  TABLET_LANDSCAPE_UP: 900,
  LARGE_TABLET_LANDSCAPE_UP: 992,
  DESKTOP_UP: 1200,
  LARGE_DESKTOP_UP: 1800,
} as const;
