export const breakpoints = {
  LARGE_SMARTPHONE: '375px',
  TABLET_PORTRAIT: '600px',
  LARGE_TABLET_PORTRAIT: '768px',
  TABLET_LANDSCAPE: '900px',
  LARGE_TABLET_LANDSCAPE: '992px',
  DESKTOP: '1200px',
  LARGE_DESKTOP: '1800px',
};
