import type { DropdownOption } from '@/types/Dropdown';

export const COUNTRY_OPTIONS: DropdownOption[] = [
  { id: 'DEU', text: 'Alemanha', icon: '/images/country-flag/DEU.svg' },
  { id: 'ARG', text: 'Argentina', icon: '/images/country-flag/ARG.svg' },
  { id: 'SAU', text: 'Arábia Saudita', icon: '/images/country-flag/SAU.svg' },
  { id: 'AUS', text: 'Austrália', icon: '/images/country-flag/AUS.svg' },
  { id: 'AUT', text: 'Aústria', icon: '/images/country-flag/AUT.svg' },
  { id: 'BRA', text: 'Brasil', icon: '/images/country-flag/BRA.svg' },
  { id: 'CAN', text: 'Canada', icon: '/images/country-flag/CAN.svg' },
  { id: 'CHL', text: 'Chile', icon: '/images/country-flag/CHL.svg' },
  { id: 'CHN', text: 'China', icon: '/images/country-flag/CHN.svg' },
  { id: 'COL', text: 'Colômbia', icon: '/images/country-flag/COL.svg' },
  { id: 'KOR', text: 'Coréia do Sul', icon: '/images/country-flag/KOR.svg' },
  { id: 'DNK', text: 'Dinamarca', icon: '/images/country-flag/DNK.svg' },
  { id: 'EGY', text: 'Egito', icon: '/images/country-flag/EGY.svg' },
  { id: 'ECU', text: 'Equador', icon: '/images/country-flag/ECU.svg' },
  { id: 'SCT', text: 'Escócia', icon: '/images/country-flag/SCT.svg' },
  { id: 'ESP', text: 'Espanha', icon: '/images/country-flag/ESP.svg' },
  { id: 'USA', text: 'Estados Unidos', icon: '/images/country-flag/USA.svg' },
  { id: 'FIN', text: 'Finlândia', icon: '/images/country-flag/FIN.svg' },
  { id: 'FRA', text: 'França', icon: '/images/country-flag/FRA.svg' },
  { id: 'NLD', text: 'Holanda', icon: '/images/country-flag/NLD.svg' },
  { id: 'IND', text: 'Índia', icon: '/images/country-flag/IND.svg' },
  { id: 'ENG', text: 'Inglaterra', icon: '/images/country-flag/ENG.svg' },
  { id: 'IRL', text: 'Irlanda', icon: '/images/country-flag/IRL.svg' },
  { id: 'ITA', text: 'Itália', icon: '/images/country-flag/ITA.svg' },
  { id: 'JPN', text: 'Japão', icon: '/images/country-flag/JPN.svg' },
  { id: 'MEX', text: 'México', icon: '/images/country-flag/MEX.svg' },
  { id: 'NOR', text: 'Noruega', icon: '/images/country-flag/NOR.svg' },
  { id: 'PRY', text: 'Paraguai', icon: '/images/country-flag/PRY.svg' },
  { id: 'PER', text: 'Peru', icon: '/images/country-flag/PER.svg' },
  { id: 'PRT', text: 'Portugal', icon: '/images/country-flag/PRT.svg' },
  { id: 'RUS', text: 'Rússia', icon: '/images/country-flag/RUS.svg' },
  { id: 'SWE', text: 'Suécia', icon: '/images/country-flag/SWE.svg' },
  { id: 'CHE', text: 'Suíça', icon: '/images/country-flag/CHE.svg' },
  { id: 'TUR', text: 'Turquia', icon: '/images/country-flag/TUR.svg' },
  { id: 'URY', text: 'Uruguai', icon: '/images/country-flag/URY.svg' },
  { id: 'VEN', text: 'Venezuela', icon: '/images/country-flag/VEN.svg' },
];
