import type { DropdownOption } from '@/types/Dropdown';
import type { TypeCountry } from '@/types/Country';

export const Country = {
  GERMANY: 'DEU',
  ARGENTINA: 'ARG',
  SAUDI_ARABIA: 'SAU',
  AUSTRALIA: 'AUS',
  AUSTRIA: 'AUT',
  BRAZIL: 'BRA',
  CANADA: 'CAN',
  CHILE: 'CHL',
  CHINA: 'CHN',
  COLOMBIA: 'COL',
  KOREA: 'KOR',
  DENMARK: 'DNK',
  EGYPT: 'EGY',
  ECUADOR: 'ECU',
  SCOTLAND: 'SCT',
  SPAIN: 'ESP',
  UNITED_STATES: 'USA',
  FINLAND: 'FIN',
  FRANCE: 'FRA',
  NETHERLANDS: 'NLD',
  INDIA: 'IND',
  ENGLAND: 'ENG',
  IRELAND: 'IRL',
  ITALY: 'ITA',
  JAPAN: 'JPN',
  MEXICO: 'MEX',
  NORWAY: 'NOR',
  PARAGUAY: 'PRY',
  PERU: 'PER',
  PORTUGAL: 'PRT',
  RUSSIA: 'RUS',
  SWEDEN: 'SWE',
  SWITZERLAND: 'CHE',
  TURKEY: 'TUR',
  URUGUAY: 'URY',
  VENEZUELA: 'VEN',
} as const;

export const COUNTRY_OPTIONS: DropdownOption<TypeCountry>[] = [
  { id: Country.GERMANY, text: 'Alemanha', icon: '/images/country-flag/DEU.svg' },
  { id: Country.ARGENTINA, text: 'Argentina', icon: '/images/country-flag/ARG.svg' },
  { id: Country.SAUDI_ARABIA, text: 'Arábia Saudita', icon: '/images/country-flag/SAU.svg' },
  { id: Country.AUSTRALIA, text: 'Austrália', icon: '/images/country-flag/AUS.svg' },
  { id: Country.AUSTRIA, text: 'Aústria', icon: '/images/country-flag/AUT.svg' },
  { id: Country.BRAZIL, text: 'Brasil', icon: '/images/country-flag/BRA.svg' },
  { id: Country.CANADA, text: 'Canada', icon: '/images/country-flag/CAN.svg' },
  { id: Country.CHILE, text: 'Chile', icon: '/images/country-flag/CHL.svg' },
  { id: Country.CHINA, text: 'China', icon: '/images/country-flag/CHN.svg' },
  { id: Country.COLOMBIA, text: 'Colômbia', icon: '/images/country-flag/COL.svg' },
  { id: Country.KOREA, text: 'Coréia do Sul', icon: '/images/country-flag/KOR.svg' },
  { id: Country.DENMARK, text: 'Dinamarca', icon: '/images/country-flag/DNK.svg' },
  { id: Country.EGYPT, text: 'Egito', icon: '/images/country-flag/EGY.svg' },
  { id: Country.ECUADOR, text: 'Equador', icon: '/images/country-flag/ECU.svg' },
  { id: Country.SCOTLAND, text: 'Escócia', icon: '/images/country-flag/SCT.svg' },
  { id: Country.SPAIN, text: 'Espanha', icon: '/images/country-flag/ESP.svg' },
  { id: Country.UNITED_STATES, text: 'Estados Unidos', icon: '/images/country-flag/USA.svg' },
  { id: Country.FINLAND, text: 'Finlândia', icon: '/images/country-flag/FIN.svg' },
  { id: Country.FRANCE, text: 'França', icon: '/images/country-flag/FRA.svg' },
  { id: Country.NETHERLANDS, text: 'Holanda', icon: '/images/country-flag/NLD.svg' },
  { id: Country.INDIA, text: 'Índia', icon: '/images/country-flag/IND.svg' },
  { id: Country.ENGLAND, text: 'Inglaterra', icon: '/images/country-flag/ENG.svg' },
  { id: Country.IRELAND, text: 'Irlanda', icon: '/images/country-flag/IRL.svg' },
  { id: Country.ITALY, text: 'Itália', icon: '/images/country-flag/ITA.svg' },
  { id: Country.JAPAN, text: 'Japão', icon: '/images/country-flag/JPN.svg' },
  { id: Country.MEXICO, text: 'México', icon: '/images/country-flag/MEX.svg' },
  { id: Country.NORWAY, text: 'Noruega', icon: '/images/country-flag/NOR.svg' },
  { id: Country.PARAGUAY, text: 'Paraguai', icon: '/images/country-flag/PRY.svg' },
  { id: Country.PERU, text: 'Peru', icon: '/images/country-flag/PER.svg' },
  { id: Country.PORTUGAL, text: 'Portugal', icon: '/images/country-flag/PRT.svg' },
  { id: Country.RUSSIA, text: 'Rússia', icon: '/images/country-flag/RUS.svg' },
  { id: Country.SWEDEN, text: 'Suécia', icon: '/images/country-flag/SWE.svg' },
  { id: Country.SWITZERLAND, text: 'Suíça', icon: '/images/country-flag/CHE.svg' },
  { id: Country.TURKEY, text: 'Turquia', icon: '/images/country-flag/TUR.svg' },
  { id: Country.URUGUAY, text: 'Uruguai', icon: '/images/country-flag/URY.svg' },
  { id: Country.VENEZUELA, text: 'Venezuela', icon: '/images/country-flag/VEN.svg' },
];
