export enum Country {
  GERMANY = 'DEU',
  ARGENTINA = 'ARG',
  BELGIUM = 'BEL',
  SAUDI_ARABIA = 'SAU',
  AUSTRALIA = 'AUS',
  AUSTRIA = 'AUT',
  BRAZIL = 'BRA',
  CANADA = 'CAN',
  CHILE = 'CHL',
  CHINA = 'CHN',
  COLOMBIA = 'COL',
  KOREA = 'KOR',
  DENMARK = 'DNK',
  EGYPT = 'EGY',
  ECUADOR = 'ECU',
  SCOTLAND = 'SCT',
  SPAIN = 'ESP',
  UNITED_STATES = 'USA',
  FINLAND = 'FIN',
  FRANCE = 'FRA',
  NETHERLANDS = 'NLD',
  INDIA = 'IND',
  ENGLAND = 'ENG',
  IRELAND = 'IRL',
  ITALY = 'ITA',
  JAPAN = 'JPN',
  MEXICO = 'MEX',
  NORWAY = 'NOR',
  PARAGUAY = 'PRY',
  PERU = 'PER',
  PORTUGAL = 'PRT',
  RUSSIA = 'RUS',
  SWEDEN = 'SWE',
  SWITZERLAND = 'CHE',
  TURKEY = 'TUR',
  URUGUAY = 'URY',
  VENEZUELA = 'VEN',
}

export const COUNTRY_OPTIONS: SelectOptionList<Country | ''> = [
  { value: '', label: 'Qualquer país' },
  { value: Country.GERMANY, label: 'Alemanha' },
  { value: Country.ARGENTINA, label: 'Argentina' },
  { value: Country.SAUDI_ARABIA, label: 'Arábia Saudita' },
  { value: Country.AUSTRALIA, label: 'Austrália' },
  { value: Country.AUSTRIA, label: 'Aústria' },
  { value: Country.BELGIUM, label: 'Bélgica' },
  { value: Country.BRAZIL, label: 'Brasil' },
  { value: Country.CANADA, label: 'Canada' },
  { value: Country.CHILE, label: 'Chile' },
  { value: Country.CHINA, label: 'China' },
  { value: Country.COLOMBIA, label: 'Colômbia' },
  { value: Country.KOREA, label: 'Coréia do Sul' },
  { value: Country.DENMARK, label: 'Dinamarca' },
  { value: Country.EGYPT, label: 'Egito' },
  { value: Country.ECUADOR, label: 'Equador' },
  { value: Country.SCOTLAND, label: 'Escócia' },
  { value: Country.SPAIN, label: 'Espanha' },
  { value: Country.UNITED_STATES, label: 'Estados Unidos' },
  { value: Country.FINLAND, label: 'Finlândia' },
  { value: Country.FRANCE, label: 'França' },
  { value: Country.NETHERLANDS, label: 'Holanda' },
  { value: Country.INDIA, label: 'Índia' },
  { value: Country.ENGLAND, label: 'Inglaterra' },
  { value: Country.IRELAND, label: 'Irlanda' },
  { value: Country.ITALY, label: 'Itália' },
  { value: Country.JAPAN, label: 'Japão' },
  { value: Country.MEXICO, label: 'México' },
  { value: Country.NORWAY, label: 'Noruega' },
  { value: Country.PARAGUAY, label: 'Paraguai' },
  { value: Country.PERU, label: 'Peru' },
  { value: Country.PORTUGAL, label: 'Portugal' },
  { value: Country.RUSSIA, label: 'Rússia' },
  { value: Country.SWEDEN, label: 'Suécia' },
  { value: Country.SWITZERLAND, label: 'Suíça' },
  { value: Country.TURKEY, label: 'Turquia' },
  { value: Country.URUGUAY, label: 'Uruguai' },
  { value: Country.VENEZUELA, label: 'Venezuela' },
];
