export const DETAILED_TEAM_LIST: TeamDetails[] = [
  {id: 1, name: "QPR", badge: "https://img.sofascore.com/api/v1/team/1/image", country: "ENG"},
  {id: 2, name: "Portsmouth", badge: "https://img.sofascore.com/api/v1/team/2/image", country: "ENG"},
  {id: 3, name: "Wolves", badge: "https://img.sofascore.com/api/v1/team/3/image", country: "ENG"},
  {id: 4, name: "Bolton", badge: "https://img.sofascore.com/api/v1/team/5/image", country: "ENG"},
  {id: 5, name: "Burnley", badge: "https://img.sofascore.com/api/v1/team/6/image", country: "ENG"},
  {id: 6, name: "Crystal Palace", badge: "https://img.sofascore.com/api/v1/team/7/image", country: "ENG"},
  {id: 7, name: "West Brom", badge: "https://img.sofascore.com/api/v1/team/8/image", country: "ENG"},
  {id: 8, name: "Birmingham", badge: "https://img.sofascore.com/api/v1/team/9/image", country: "ENG"},
  {id: 9, name: "Coventry", badge: "https://img.sofascore.com/api/v1/team/11/image", country: "ENG"},
  {id: 10, name: "Rotherham", badge: "https://img.sofascore.com/api/v1/team/13/image", country: "ENG"},
  {id: 11, name: "Nottingham Forest", badge: "https://img.sofascore.com/api/v1/team/14/image", country: "ENG"},
  {id: 12, name: "Sheffield Utd", badge: "https://img.sofascore.com/api/v1/team/15/image", country: "ENG"},
  {id: 13, name: "Manchester City", badge: "https://img.sofascore.com/api/v1/team/17/image", country: "ENG"},
  {id: 14, name: "Barnsley", badge: "https://img.sofascore.com/api/v1/team/23/image", country: "ENG"},
  {id: 15, name: "Watford", badge: "https://img.sofascore.com/api/v1/team/24/image", country: "ENG"},
  {id: 16, name: "Derby County", badge: "https://img.sofascore.com/api/v1/team/27/image", country: "ENG"},
  {id: 17, name: "Reading", badge: "https://img.sofascore.com/api/v1/team/28/image", country: "ENG"},
  {id: 18, name: "Brighton", badge: "https://img.sofascore.com/api/v1/team/30/image", country: "ENG"},
  {id: 19, name: "Leicester", badge: "https://img.sofascore.com/api/v1/team/31/image", country: "ENG"},
  {id: 20, name: "Ipswich Town", badge: "https://img.sofascore.com/api/v1/team/32/image", country: "ENG"},
  {id: 21, name: "Tottenham ", badge: "https://img.sofascore.com/api/v1/team/33/image", country: "ENG"},
  {id: 22, name: "Leeds", badge: "https://img.sofascore.com/api/v1/team/34/image", country: "ENG"},
  {id: 23, name: "Manchester United", badge: "https://img.sofascore.com/api/v1/team/35/image", country: "ENG"},
  {id: 24, name: "Middlesbrough", badge: "https://img.sofascore.com/api/v1/team/36/image", country: "ENG"},
  {id: 25, name: "West Ham", badge: "https://img.sofascore.com/api/v1/team/37/image", country: "ENG"},
  {id: 26, name: "Chelsea", badge: "https://img.sofascore.com/api/v1/team/38/image", country: "ENG"},
  {id: 27, name: "Newcastle", badge: "https://img.sofascore.com/api/v1/team/39/image", country: "ENG"},
  {id: 28, name: "Aston Villa", badge: "https://img.sofascore.com/api/v1/team/40/image", country: "ENG"},
  {id: 29, name: "Sunderland", badge: "https://img.sofascore.com/api/v1/team/41/image", country: "ENG"},
  {id: 30, name: "Arsenal", badge: "https://img.sofascore.com/api/v1/team/42/image", country: "ENG"},
  {id: 31, name: "Fulham", badge: "https://img.sofascore.com/api/v1/team/43/image", country: "ENG"},
  {id: 32, name: "Liverpool", badge: "https://img.sofascore.com/api/v1/team/44/image", country: "ENG"},
  {id: 33, name: "Southampton", badge: "https://img.sofascore.com/api/v1/team/45/image", country: "ENG"},
  {id: 34, name: "Blackburn", badge: "https://img.sofascore.com/api/v1/team/46/image", country: "ENG"},
  {id: 35, name: "Wigan", badge: "https://img.sofascore.com/api/v1/team/49/image", country: "ENG"},
  {id: 36, name: "Brentford", badge: "https://img.sofascore.com/api/v1/team/50/image", country: "ENG"},
  {id: 37, name: "Northampton", badge: "https://img.sofascore.com/api/v1/team/57/image", country: "ENG"},
  {id: 38, name: "Bristol City", badge: "https://img.sofascore.com/api/v1/team/58/image", country: "ENG"},
  {id: 39, name: "Huddersfield", badge: "https://img.sofascore.com/api/v1/team/59/image", country: "ENG"},
  {id: 40, name: "Bournemouth", badge: "https://img.sofascore.com/api/v1/team/60/image", country: "ENG"},
  {id: 41, name: "Cambridge", badge: "https://img.sofascore.com/api/v1/team/63/image", country: "ENG"},
  {id: 42, name: "Mansfield", badge: "https://img.sofascore.com/api/v1/team/70/image", country: "ENG"},
  {id: 43, name: "Plymouth", badge: "https://img.sofascore.com/api/v1/team/71/image", country: "ENG"},
  {id: 44, name: "Luton", badge: "https://img.sofascore.com/api/v1/team/72/image", country: "ENG"},
  {id: 45, name: "Bristol Rovers", badge: "https://img.sofascore.com/api/v1/team/76/image", country: "ENG"},
  {id: 46, name: "Carlisle", badge: "https://img.sofascore.com/api/v1/team/78/image", country: "ENG"},
  {id: 47, name: "Hull", badge: "https://img.sofascore.com/api/v1/team/96/image", country: "ENG"},
  {id: 48, name: "Norwich", badge: "https://img.sofascore.com/api/v1/team/263/image", country: "ENG"},
  {id: 49, name: "Midtjylland", badge: "https://img.sofascore.com/api/v1/team/1289/image", country: "DNK"},
  {id: 50, name: "Olympique de Marseille", badge: "https://img.sofascore.com/api/v1/team/1641/image", country: "FRA"},
  {id: 51, name: "Montpellier", badge: "https://img.sofascore.com/api/v1/team/1642/image", country: "FRA"},
  {id: 52, name: "Lille", badge: "https://img.sofascore.com/api/v1/team/1643/image", country: "FRA"},
  {id: 53, name: "PSG", badge: "https://img.sofascore.com/api/v1/team/1644/image", country: "FRA"},
  {id: 54, name: "Bordeaux", badge: "https://img.sofascore.com/api/v1/team/1645/image", country: "FRA"},
  {id: 55, name: "Auxerre", badge: "https://img.sofascore.com/api/v1/team/1646/image", country: "FRA"},
  {id: 56, name: "Nantes", badge: "https://img.sofascore.com/api/v1/team/1647/image", country: "FRA"},
  {id: 57, name: "Lyon", badge: "https://img.sofascore.com/api/v1/team/1649/image", country: "FRA"},
  {id: 58, name: "Strasbourg", badge: "https://img.sofascore.com/api/v1/team/1659/image", country: "FRA"},
  {id: 59, name: "Nice", badge: "https://img.sofascore.com/api/v1/team/1661/image", country: "FRA"},
  {id: 60, name: "Le Havre", badge: "https://img.sofascore.com/api/v1/team/1662/image", country: "FRA"},
  {id: 61, name: "Saint-Étienne", badge: "https://img.sofascore.com/api/v1/team/1678/image", country: "FRA"},
  {id: 62, name: "Toulouse", badge: "https://img.sofascore.com/api/v1/team/1681/image", country: "FRA"},
  {id: 63, name: "Stade de Reims", badge: "https://img.sofascore.com/api/v1/team/1682/image", country: "FRA"},
  {id: 64, name: "Brest", badge: "https://img.sofascore.com/api/v1/team/1715/image", country: "FRA"},
  {id: 65, name: "Monterrey", badge: "https://img.sofascore.com/api/v1/team/1932/image", country: "MEX"},
  {id: 66, name: "Pachuca", badge: "https://img.sofascore.com/api/v1/team/1936/image", country: "MEX"},
  {id: 67, name: "América", badge: "https://img.sofascore.com/api/v1/team/1939/image", country: "MEX"},
  {id: 68, name: "Tigres", badge: "https://img.sofascore.com/api/v1/team/1940/image", country: "MEX"},
  {id: 69, name: "Cruzeiro", badge: "https://img.sofascore.com/api/v1/team/1954/image", country: "BRA"},
  {id: 70, name: "Bahia", badge: "https://img.sofascore.com/api/v1/team/1955/image", country: "BRA"},
  {id: 71, name: "Corinthians", badge: "https://img.sofascore.com/api/v1/team/1957/image", country: "BRA"},
  {id: 72, name: "Botafogo", badge: "https://img.sofascore.com/api/v1/team/1958/image", country: "BRA"},
  {id: 73, name: "Sport", badge: "https://img.sofascore.com/api/v1/team/1959/image", country: "BRA"},
  {id: 74, name: "Goiás", badge: "https://img.sofascore.com/api/v1/team/1960/image", country: "BRA"},
  {id: 75, name: "Fluminense", badge: "https://img.sofascore.com/api/v1/team/1961/image", country: "BRA"},
  {id: 76, name: "Vitória", badge: "https://img.sofascore.com/api/v1/team/1962/image", country: "BRA"},
  {id: 77, name: "Palmeiras", badge: "https://img.sofascore.com/api/v1/team/1963/image", country: "BRA"},
  {id: 78, name: "São Caetano", badge: "https://img.sofascore.com/api/v1/team/1964/image", country: "BRA"},
  {id: 79, name: "Paraná", badge: "https://img.sofascore.com/api/v1/team/1965/image", country: "BRA"},
  {id: 80, name: "Internacional", badge: "https://img.sofascore.com/api/v1/team/1966/image", country: "BRA"},
  {id: 81, name: "Athletico", badge: "https://img.sofascore.com/api/v1/team/1967/image", country: "BRA"},
  {id: 82, name: "Santos", badge: "https://img.sofascore.com/api/v1/team/1968/image", country: "BRA"},
  {id: 83, name: "Ponte Preta", badge: "https://img.sofascore.com/api/v1/team/1969/image", country: "BRA"},
  {id: 84, name: "Guarani", badge: "https://img.sofascore.com/api/v1/team/1972/image", country: "BRA"},
  {id: 85, name: "América-MG", badge: "https://img.sofascore.com/api/v1/team/1973/image", country: "BRA"},
  {id: 86, name: "Vasco", badge: "https://img.sofascore.com/api/v1/team/1974/image", country: "BRA"},
  {id: 87, name: "Santa Cruz ", badge: "https://img.sofascore.com/api/v1/team/1976/image", country: "BRA"},
  {id: 88, name: "Atlético-MG", badge: "https://img.sofascore.com/api/v1/team/1977/image", country: "BRA"},
  {id: 89, name: "Gama", badge: "https://img.sofascore.com/api/v1/team/1978/image", country: "BRA"},
  {id: 90, name: "Botafogo-SP", badge: "https://img.sofascore.com/api/v1/team/1979/image", country: "BRA"},
  {id: 91, name: "Juventude", badge: "https://img.sofascore.com/api/v1/team/1980/image", country: "BRA"},
  {id: 92, name: "São Paulo", badge: "https://img.sofascore.com/api/v1/team/1981/image", country: "BRA"},
  {id: 93, name: "Coritiba", badge: "https://img.sofascore.com/api/v1/team/1982/image", country: "BRA"},
  {id: 94, name: "Criciúma", badge: "https://img.sofascore.com/api/v1/team/1984/image", country: "BRA"},
  {id: 95, name: "Figueirense", badge: "https://img.sofascore.com/api/v1/team/1985/image", country: "BRA"},
  {id: 96, name: "GE Brasil", badge: "https://img.sofascore.com/api/v1/team/1986/image", country: "BRA"},
  {id: 97, name: "Joinville", badge: "https://img.sofascore.com/api/v1/team/1987/image", country: "BRA"},
  {id: 98, name: "Bangu", badge: "https://img.sofascore.com/api/v1/team/1993/image", country: "BRA"},
  {id: 99, name: "Paysandu", badge: "https://img.sofascore.com/api/v1/team/1997/image", country: "BRA"},
  {id: 100, name: "RB Bragantino", badge: "https://img.sofascore.com/api/v1/team/1999/image", country: "BRA"},
  {id: 101, name: "Ceará", badge: "https://img.sofascore.com/api/v1/team/2001/image", country: "BRA"},
  {id: 102, name: "Sampaio Corrêa", badge: "https://img.sofascore.com/api/v1/team/2005/image", country: "BRA"},
  {id: 103, name: "Moto Club", badge: "https://img.sofascore.com/api/v1/team/2009/image", country: "BRA"},
  {id: 104, name: "CSA", badge: "https://img.sofascore.com/api/v1/team/2010/image", country: "BRA"},
  {id: 105, name: "Náutico", badge: "https://img.sofascore.com/api/v1/team/2011/image", country: "BRA"},
  {id: 106, name: "Remo", badge: "https://img.sofascore.com/api/v1/team/2012/image", country: "BRA"},
  {id: 107, name: "Confiança", badge: "https://img.sofascore.com/api/v1/team/2017/image", country: "BRA"},
  {id: 108, name: "Treze", badge: "https://img.sofascore.com/api/v1/team/2018/image", country: "BRA"},
  {id: 109, name: "ASA", badge: "https://img.sofascore.com/api/v1/team/2019/image", country: "BRA"},
  {id: 110, name: "Fortaleza", badge: "https://img.sofascore.com/api/v1/team/2020/image", country: "BRA"},
  {id: 111, name: "Vila Nova", badge: "https://img.sofascore.com/api/v1/team/2021/image", country: "BRA"},
  {id: 112, name: "Londrina", badge: "https://img.sofascore.com/api/v1/team/2022/image", country: "BRA"},
  {id: 113, name: "América-RN", badge: "https://img.sofascore.com/api/v1/team/2023/image", country: "BRA"},
  {id: 114, name: "Brasiliense", badge: "https://img.sofascore.com/api/v1/team/2024/image", country: "BRA"},
  {id: 115, name: "Ituano", badge: "https://img.sofascore.com/api/v1/team/2025/image", country: "BRA"},
  {id: 116, name: "RB Salzburg", badge: "https://img.sofascore.com/api/v1/team/2046/image", country: "AUT"},
  {id: 117, name: "Sturm Graz", badge: "https://img.sofascore.com/api/v1/team/2051/image", country: "AUT"},
  {id: 118, name: "LASK", badge: "https://img.sofascore.com/api/v1/team/2058/image", country: "AUT"},
  {id: 119, name: "BW Linz", badge: "https://img.sofascore.com/api/v1/team/2113/image", country: "AUT"},
  {id: 120, name: "Slavia Praha", badge: "https://img.sofascore.com/api/v1/team/2216/image", country: "CZE"},
  {id: 121, name: "Sparta Praha", badge: "https://img.sofascore.com/api/v1/team/2218/image", country: "CZE"},
  {id: 122, name: "Cienciano", badge: "https://img.sofascore.com/api/v1/team/2301/image", country: "PER"},
  {id: 123, name: "Sporting Cristal", badge: "https://img.sofascore.com/api/v1/team/2302/image", country: "PER"},
  {id: 124, name: "Melgar", badge: "https://img.sofascore.com/api/v1/team/2308/image", country: "PER"},
  {id: 125, name: "Alianza Lima", badge: "https://img.sofascore.com/api/v1/team/2311/image", country: "PER"},
  {id: 126, name: "Dynamo Moscow", badge: "https://img.sofascore.com/api/v1/team/2315/image", country: "RUS"},
  {id: 127, name: "Lokomotiv", badge: "https://img.sofascore.com/api/v1/team/2320/image", country: "RUS"},
  {id: 128, name: "Zenit", badge: "https://img.sofascore.com/api/v1/team/2321/image", country: "RUS"},
  {id: 129, name: "Spartak ", badge: "https://img.sofascore.com/api/v1/team/2323/image", country: "RUS"},
  {id: 130, name: "CSKA", badge: "https://img.sofascore.com/api/v1/team/2325/image", country: "RUS"},
  {id: 131, name: "Rostov", badge: "https://img.sofascore.com/api/v1/team/2326/image", country: "RUS"},
  {id: 132, name: "Rubin Kazan", badge: "https://img.sofascore.com/api/v1/team/2333/image", country: "RUS"},
  {id: 133, name: "Young Boys", badge: "https://img.sofascore.com/api/v1/team/2445/image", country: "CHE"},
  {id: 134, name: "Lausanne", badge: "https://img.sofascore.com/api/v1/team/2446/image", country: "CHE"},
  {id: 135, name: "Grasshoppers", badge: "https://img.sofascore.com/api/v1/team/2449/image", country: "CHE"},
  {id: 136, name: "Zürich", badge: "https://img.sofascore.com/api/v1/team/2450/image", country: "CHE"},
  {id: 137, name: "Sion", badge: "https://img.sofascore.com/api/v1/team/2452/image", country: "CHE"},
  {id: 138, name: "Basel", badge: "https://img.sofascore.com/api/v1/team/2501/image", country: "CHE"},
  {id: 139, name: "LA Galaxy", badge: "https://img.sofascore.com/api/v1/team/2513/image", country: "USA"},
  {id: 140, name: "Wolfsburg", badge: "https://img.sofascore.com/api/v1/team/2524/image", country: "DEU"},
  {id: 141, name: "St. Pauli", badge: "https://img.sofascore.com/api/v1/team/2526/image", country: "DEU"},
  {id: 142, name: "Borussia M'gladbach", badge: "https://img.sofascore.com/api/v1/team/2527/image", country: "DEU"},
  {id: 143, name: "Hertha", badge: "https://img.sofascore.com/api/v1/team/2528/image", country: "DEU"},
  {id: 144, name: "Schalke 04", badge: "https://img.sofascore.com/api/v1/team/2530/image", country: "DEU"},
  {id: 145, name: "Werder Bremen", badge: "https://img.sofascore.com/api/v1/team/2534/image", country: "DEU"},
  {id: 146, name: "Freiburg", badge: "https://img.sofascore.com/api/v1/team/2538/image", country: "DEU"},
  {id: 147, name: "Hannover", badge: "https://img.sofascore.com/api/v1/team/2541/image", country: "DEU"},
  {id: 148, name: "Bochum", badge: "https://img.sofascore.com/api/v1/team/2542/image", country: "DEU"},
  {id: 149, name: "Union Berlin", badge: "https://img.sofascore.com/api/v1/team/2547/image", country: "DEU"},
  {id: 150, name: "Mainz 05", badge: "https://img.sofascore.com/api/v1/team/2556/image", country: "DEU"},
  {id: 151, name: "Hoffenheim", badge: "https://img.sofascore.com/api/v1/team/2569/image", country: "DEU"},
  {id: 152, name: "Holstein Kiel", badge: "https://img.sofascore.com/api/v1/team/2573/image", country: "DEU"},
  {id: 153, name: "Darmstadt", badge: "https://img.sofascore.com/api/v1/team/2576/image", country: "DEU"},
  {id: 154, name: "Augsburg", badge: "https://img.sofascore.com/api/v1/team/2600/image", country: "DEU"},
  {id: 155, name: "Köln", badge: "https://img.sofascore.com/api/v1/team/2671/image", country: "DEU"},
  {id: 156, name: "Bayern", badge: "https://img.sofascore.com/api/v1/team/2672/image", country: "DEU"},
  {id: 157, name: "Borussia Dortmund", badge: "https://img.sofascore.com/api/v1/team/2673/image", country: "DEU"},
  {id: 158, name: "Eintracht Frankfurt", badge: "https://img.sofascore.com/api/v1/team/2674/image", country: "DEU"},
  {id: 159, name: "Kaiserslautern", badge: "https://img.sofascore.com/api/v1/team/2675/image", country: "DEU"},
  {id: 160, name: "Stuttgart", badge: "https://img.sofascore.com/api/v1/team/2677/image", country: "DEU"},
  {id: 161, name: "Leverkusen", badge: "https://img.sofascore.com/api/v1/team/2681/image", country: "DEU"},
  {id: 162, name: "Bologna", badge: "https://img.sofascore.com/api/v1/team/2685/image", country: "ITA"},
  {id: 163, name: "Atalanta", badge: "https://img.sofascore.com/api/v1/team/2686/image", country: "ITA"},
  {id: 164, name: "Juventus", badge: "https://img.sofascore.com/api/v1/team/2687/image", country: "ITA"},
  {id: 165, name: "Venezia", badge: "https://img.sofascore.com/api/v1/team/2688/image", country: "ITA"},
  {id: 166, name: "Lecce", badge: "https://img.sofascore.com/api/v1/team/2689/image", country: "ITA"},
  {id: 167, name: "Parma", badge: "https://img.sofascore.com/api/v1/team/2690/image", country: "ITA"},
  {id: 168, name: "Milan", badge: "https://img.sofascore.com/api/v1/team/2692/image", country: "ITA"},
  {id: 169, name: "Fiorentina", badge: "https://img.sofascore.com/api/v1/team/2693/image", country: "ITA"},
  {id: 170, name: "Udinese", badge: "https://img.sofascore.com/api/v1/team/2695/image", country: "ITA"},
  {id: 171, name: "Torino", badge: "https://img.sofascore.com/api/v1/team/2696/image", country: "ITA"},
  {id: 172, name: "Inter", badge: "https://img.sofascore.com/api/v1/team/2697/image", country: "ITA"},
  {id: 173, name: "Lazio", badge: "https://img.sofascore.com/api/v1/team/2699/image", country: "ITA"},
  {id: 174, name: "Verona", badge: "https://img.sofascore.com/api/v1/team/2701/image", country: "ITA"},
  {id: 175, name: "Roma", badge: "https://img.sofascore.com/api/v1/team/2702/image", country: "ITA"},
  {id: 176, name: "Como", badge: "https://img.sofascore.com/api/v1/team/2704/image", country: "ITA"},
  {id: 177, name: "Empoli", badge: "https://img.sofascore.com/api/v1/team/2705/image", country: "ITA"},
  {id: 178, name: "Ascoli", badge: "https://img.sofascore.com/api/v1/team/2707/image", country: "ITA"},
  {id: 179, name: "Sampdoria", badge: "https://img.sofascore.com/api/v1/team/2711/image", country: "ITA"},
  {id: 180, name: "Genoa", badge: "https://img.sofascore.com/api/v1/team/2713/image", country: "ITA"},
  {id: 181, name: "Napoli", badge: "https://img.sofascore.com/api/v1/team/2714/image", country: "ITA"},
  {id: 182, name: "Palermo", badge: "https://img.sofascore.com/api/v1/team/2715/image", country: "ITA"},
  {id: 183, name: "Cagliari", badge: "https://img.sofascore.com/api/v1/team/2719/image", country: "ITA"},
  {id: 184, name: "Livorno", badge: "https://img.sofascore.com/api/v1/team/2726/image", country: "ITA"},
  {id: 185, name: "SPAL", badge: "https://img.sofascore.com/api/v1/team/113755/image", country: "ITA"},
  {id: 186, name: "Benevento", badge: "https://img.sofascore.com/api/v1/team/2759/image", country: "ITA"},
  {id: 187, name: "Sassuolo", badge: "https://img.sofascore.com/api/v1/team/2793/image", country: "ITA"},
  {id: 188, name: "Espanyol", badge: "https://img.sofascore.com/api/v1/team/2814/image", country: "ESP"},
  {id: 189, name: "Real Zaragoza", badge: "https://img.sofascore.com/api/v1/team/2815/image", country: "ESP"},
  {id: 190, name: "Real Betis", badge: "https://img.sofascore.com/api/v1/team/2816/image", country: "ESP"},
  {id: 191, name: "Barcelona", badge: "https://img.sofascore.com/api/v1/team/2817/image", country: "ESP"},
  {id: 192, name: "Villarreal", badge: "https://img.sofascore.com/api/v1/team/2819/image", country: "ESP"},
  {id: 193, name: "Osasuna", badge: "https://img.sofascore.com/api/v1/team/2820/image", country: "ESP"},
  {id: 194, name: "Celta Vigo", badge: "https://img.sofascore.com/api/v1/team/2821/image", country: "ESP"},
  {id: 195, name: "CD Tenerife", badge: "https://img.sofascore.com/api/v1/team/2822/image", country: "ESP"},
  {id: 196, name: "Real Sociedad", badge: "https://img.sofascore.com/api/v1/team/2824/image", country: "ESP"},
  {id: 197, name: "Athletic Club", badge: "https://img.sofascore.com/api/v1/team/2825/image", country: "ESP"},
  {id: 198, name: "Mallorca", badge: "https://img.sofascore.com/api/v1/team/2826/image", country: "ESP"},
  {id: 199, name: "Valencia", badge: "https://img.sofascore.com/api/v1/team/2828/image", country: "ESP"},
  {id: 200, name: "Real Madrid", badge: "https://img.sofascore.com/api/v1/team/2829/image", country: "ESP"},
  {id: 201, name: "Málaga", badge: "https://img.sofascore.com/api/v1/team/2830/image", country: "ESP"},
  {id: 202, name: "Real Valladolid", badge: "https://img.sofascore.com/api/v1/team/2831/image", country: "ESP"},
  {id: 203, name: "Deportivo La Coruña", badge: "https://img.sofascore.com/api/v1/team/2832/image", country: "ESP"},
  {id: 204, name: "Sevilla", badge: "https://img.sofascore.com/api/v1/team/2833/image", country: "ESP"},
  {id: 205, name: "Atlético Madrid", badge: "https://img.sofascore.com/api/v1/team/2836/image", country: "ESP"},
  {id: 206, name: "Eibar", badge: "https://img.sofascore.com/api/v1/team/2839/image", country: "ESP"},
  {id: 207, name: "Leganés", badge: "https://img.sofascore.com/api/v1/team/2845/image", country: "ESP"},
  {id: 208, name: "Elche", badge: "https://img.sofascore.com/api/v1/team/2846/image", country: "ESP"},
  {id: 209, name: "Levante", badge: "https://img.sofascore.com/api/v1/team/2849/image", country: "ESP"},
  {id: 210, name: "Córdoba", badge: "https://img.sofascore.com/api/v1/team/2850/image", country: "ESP"},
  {id: 211, name: "Almería", badge: "https://img.sofascore.com/api/v1/team/2858/image", country: "ESP"},
  {id: 212, name: "Getafe", badge: "https://img.sofascore.com/api/v1/team/2859/image", country: "ESP"},
  {id: 213, name: "Alavés", badge: "https://img.sofascore.com/api/v1/team/2885/image", country: "ESP"},
  {id: 214, name: "Club Brugge", badge: "https://img.sofascore.com/api/v1/team/2888/image", country: "BEL"},
  {id: 215, name: "Royal Antwerp", badge: "https://img.sofascore.com/api/v1/team/2889/image", country: "BEL"},
  {id: 216, name: "Genk", badge: "https://img.sofascore.com/api/v1/team/2890/image", country: "BEL"},
  {id: 217, name: "Anderlecht", badge: "https://img.sofascore.com/api/v1/team/2900/image", country: "BEL"},
  {id: 218, name: "Gent", badge: "https://img.sofascore.com/api/v1/team/2903/image", country: "BEL"},
  {id: 219, name: "PSV", badge: "https://img.sofascore.com/api/v1/team/2952/image", country: "NLD"},
  {id: 220, name: "Ajax", badge: "https://img.sofascore.com/api/v1/team/2953/image", country: "NLD"},
  {id: 221, name: "Feyenoord", badge: "https://img.sofascore.com/api/v1/team/2959/image", country: "NLD"},
  {id: 222, name: "Heerenveen", badge: "https://img.sofascore.com/api/v1/team/2964/image", country: "NLD"},
  {id: 223, name: "Boavista", badge: "https://img.sofascore.com/api/v1/team/2995/image", country: "PRT"},
  {id: 224, name: "Farense", badge: "https://img.sofascore.com/api/v1/team/2998/image", country: "PRT"},
  {id: 225, name: "Braga", badge: "https://img.sofascore.com/api/v1/team/2999/image", country: "PRT"},
  {id: 226, name: "Sporting", badge: "https://img.sofascore.com/api/v1/team/3001/image", country: "PRT"},
  {id: 227, name: "Porto", badge: "https://img.sofascore.com/api/v1/team/3002/image", country: "PRT"},
  {id: 228, name: "Benfica", badge: "https://img.sofascore.com/api/v1/team/3006/image", country: "PRT"},
  {id: 229, name: "Santa Clara", badge: "https://img.sofascore.com/api/v1/team/3011/image", country: "PRT"},
  {id: 230, name: "Estrela Amadora", badge: "https://img.sofascore.com/api/v1/team/3035/image", country: "PRT"},
  {id: 231, name: "Rio Ave", badge: "https://img.sofascore.com/api/v1/team/3036/image", country: "PRT"},
  {id: 232, name: "Beşiktaş", badge: "https://img.sofascore.com/api/v1/team/3050/image", country: "TUR"},
  {id: 233, name: "Trabzonspor", badge: "https://img.sofascore.com/api/v1/team/3051/image", country: "TUR"},
  {id: 234, name: "Fenerbahçe", badge: "https://img.sofascore.com/api/v1/team/3052/image", country: "TUR"},
  {id: 235, name: "Galatasaray", badge: "https://img.sofascore.com/api/v1/team/3061/image", country: "TUR"},
  {id: 236, name: "Legia", badge: "https://img.sofascore.com/api/v1/team/3106/image", country: "POL"},
  {id: 237, name: "Kashima Antlers", badge: "https://img.sofascore.com/api/v1/team/3134/image", country: "JPN"},
  {id: 238, name: "Urawa Reds", badge: "https://img.sofascore.com/api/v1/team/3145/image", country: "JPN"},
  {id: 239, name: "Universidad Católica", badge: "https://img.sofascore.com/api/v1/team/3151/image", country: "CHL"},
  {id: 240, name: "Unión Española", badge: "https://img.sofascore.com/api/v1/team/3153/image", country: "CHL"},
  {id: 241, name: "Colo-Colo", badge: "https://img.sofascore.com/api/v1/team/3155/image", country: "CHL"},
  {id: 242, name: "Palestino", badge: "https://img.sofascore.com/api/v1/team/3157/image", country: "CHL"},
  {id: 243, name: "Audax Italiano", badge: "https://img.sofascore.com/api/v1/team/3162/image", country: "CHL"},
  {id: 244, name: "O'Higgins", badge: "https://img.sofascore.com/api/v1/team/3163/image", country: "CHL"},
  {id: 245, name: "Huachipato", badge: "https://img.sofascore.com/api/v1/team/3164/image", country: "CHL"},
  {id: 246, name: "Coquimbo Unido", badge: "https://img.sofascore.com/api/v1/team/3165/image", country: "CHL"},
  {id: 247, name: "Cobresal", badge: "https://img.sofascore.com/api/v1/team/3167/image", country: "CHL"},
  {id: 248, name: "San Lorenzo", badge: "https://img.sofascore.com/api/v1/team/3201/image", country: "ARG"},
  {id: 249, name: "Boca Juniors", badge: "https://img.sofascore.com/api/v1/team/3202/image", country: "ARG"},
  {id: 250, name: "Belgrano", badge: "https://img.sofascore.com/api/v1/team/3203/image", country: "ARG"},
  {id: 251, name: "Unión de Santa Fe", badge: "https://img.sofascore.com/api/v1/team/3204/image", country: "ARG"},
  {id: 252, name: "Gimnasia y Esgrima", badge: "https://img.sofascore.com/api/v1/team/3205/image", country: "ARG"},
  {id: 253, name: "Estudiantes", badge: "https://img.sofascore.com/api/v1/team/3206/image", country: "ARG"},
  {id: 254, name: "Colón", badge: "https://img.sofascore.com/api/v1/team/3207/image", country: "ARG"},
  {id: 255, name: "Vélez Sarsfield", badge: "https://img.sofascore.com/api/v1/team/3208/image", country: "ARG"},
  {id: 256, name: "Independiente", badge: "https://img.sofascore.com/api/v1/team/3209/image", country: "ARG"},
  {id: 257, name: "Talleres", badge: "https://img.sofascore.com/api/v1/team/3210/image", country: "ARG"},
  {id: 258, name: "River", badge: "https://img.sofascore.com/api/v1/team/3211/image", country: "ARG"},
  {id: 259, name: "Newell's", badge: "https://img.sofascore.com/api/v1/team/3212/image", country: "ARG"},
  {id: 260, name: "Racing", badge: "https://img.sofascore.com/api/v1/team/3215/image", country: "ARG"},
  {id: 261, name: "Argentinos Jrs.", badge: "https://img.sofascore.com/api/v1/team/3216/image", country: "ARG"},
  {id: 262, name: "Rosario Central", badge: "https://img.sofascore.com/api/v1/team/3217/image", country: "ARG"},
  {id: 263, name: "Lanús", badge: "https://img.sofascore.com/api/v1/team/3218/image", country: "ARG"},
  {id: 264, name: "Banfield", badge: "https://img.sofascore.com/api/v1/team/3219/image", country: "ARG"},
  {id: 265, name: "Arsenal de Sarandí", badge: "https://img.sofascore.com/api/v1/team/3221/image", country: "ARG"},
  {id: 266, name: "Peñarol", badge: "https://img.sofascore.com/api/v1/team/3227/image", country: "URY"},
  {id: 267, name: "Danubio", badge: "https://img.sofascore.com/api/v1/team/3228/image", country: "URY"},
  {id: 268, name: "Defensor", badge: "https://img.sofascore.com/api/v1/team/3229/image", country: "URY"},
  {id: 269, name: "Nacional", badge: "https://img.sofascore.com/api/v1/team/3230/image", country: "URY"},
  {id: 270, name: "Olympiacos", badge: "https://img.sofascore.com/api/v1/team/3245/image", country: "GRC"},
  {id: 271, name: "Panathinaikos", badge: "https://img.sofascore.com/api/v1/team/3248/image", country: "GRC"},
  {id: 272, name: "AEK Athens", badge: "https://img.sofascore.com/api/v1/team/3250/image", country: "GRC"},
  {id: 273, name: "PAOK", badge: "https://img.sofascore.com/api/v1/team/3251/image", country: "GRC"},
  {id: 274, name: "Dynamo Kyiv", badge: "https://img.sofascore.com/api/v1/team/3305/image", country: "UKR"},
  {id: 275, name: "Shakhtar", badge: "https://img.sofascore.com/api/v1/team/3313/image", country: "UKR"},
  {id: 276, name: "Cádiz", badge: "https://img.sofascore.com/api/v1/team/4488/image", country: "ESP"},
  {id: 277, name: "Estoril Praia", badge: "https://img.sofascore.com/api/v1/team/4500/image", country: "PRT"},
  {id: 278, name: "Viktoria Plzeň", badge: "https://img.sofascore.com/api/v1/team/4502/image", country: "CZE"},
  {id: 279, name: "Union Saint-Gilloise", badge: "https://img.sofascore.com/api/v1/team/4860/image", country: "BEL"},
  {id: 280, name: "Mechelen", badge: "https://img.sofascore.com/api/v1/team/5044/image", country: "BEL"},
  {id: 281, name: "Aucas", badge: "https://img.sofascore.com/api/v1/team/5249/image", country: "ECU"},
  {id: 282, name: "Barcelona SC", badge: "https://img.sofascore.com/api/v1/team/5250/image", country: "ECU"},
  {id: 283, name: "Emelec", badge: "https://img.sofascore.com/api/v1/team/5255/image", country: "ECU"},
  {id: 284, name: "LDU", badge: "https://img.sofascore.com/api/v1/team/5257/image", country: "ECU"},
  {id: 285, name: "Antofagasta", badge: "https://img.sofascore.com/api/v1/team/5601/image", country: "CHL"},
  {id: 286, name: "Heidenheim", badge: "https://img.sofascore.com/api/v1/team/5885/image", country: "DEU"},
  {id: 287, name: "Grêmio", badge: "https://img.sofascore.com/api/v1/team/5926/image", country: "BRA"},
  {id: 288, name: "Flamengo", badge: "https://img.sofascore.com/api/v1/team/5981/image", country: "BRA"},
  {id: 289, name: "Cerro Porteño", badge: "https://img.sofascore.com/api/v1/team/5991/image", country: "PRY"},
  {id: 290, name: "Guaraní", badge: "https://img.sofascore.com/api/v1/team/5994/image", country: "PRY"},
  {id: 291, name: "Libertad", badge: "https://img.sofascore.com/api/v1/team/5996/image", country: "PRY"},
  {id: 292, name: "Olimpia", badge: "https://img.sofascore.com/api/v1/team/5997/image", country: "PRY"},
  {id: 293, name: "Sportivo Luqueño", badge: "https://img.sofascore.com/api/v1/team/5998/image", country: "PRY"},
  {id: 294, name: "Macará", badge: "https://img.sofascore.com/api/v1/team/6001/image", country: "ECU"},
  {id: 295, name: "Godoy Cruz", badge: "https://img.sofascore.com/api/v1/team/6074/image", country: "ARG"},
  {id: 296, name: "América de Cali", badge: "https://img.sofascore.com/api/v1/team/6102/image", country: "COL"},
  {id: 297, name: "Junior Barranquilla", badge: "https://img.sofascore.com/api/v1/team/6105/image", country: "COL"},
  {id: 298, name: "Atlético Nacional", badge: "https://img.sofascore.com/api/v1/team/6106/image", country: "COL"},
  {id: 299, name: "Deportivo Pereira", badge: "https://img.sofascore.com/api/v1/team/6109/image", country: "COL"},
  {id: 300, name: "Tolima", badge: "https://img.sofascore.com/api/v1/team/6111/image", country: "COL"},
  {id: 301, name: "Deportivo Cali", badge: "https://img.sofascore.com/api/v1/team/6112/image", country: "COL"},
  {id: 302, name: "Independiente Medellín", badge: "https://img.sofascore.com/api/v1/team/6115/image", country: "COL"},
  {id: 303, name: "Santa Fe", badge: "https://img.sofascore.com/api/v1/team/6116/image", country: "COL"},
  {id: 304, name: "Millonarios", badge: "https://img.sofascore.com/api/v1/team/6117/image", country: "COL"},
  {id: 305, name: "Once Caldas", badge: "https://img.sofascore.com/api/v1/team/6118/image", country: "COL"},
  {id: 306, name: "Carabobo", badge: "https://img.sofascore.com/api/v1/team/6229/image", country: "VEN"},
  {id: 307, name: "Caracas", badge: "https://img.sofascore.com/api/v1/team/6230/image", country: "VEN"},
  {id: 308, name: "Deportivo Táchira", badge: "https://img.sofascore.com/api/v1/team/6231/image", country: "VEN"},
  {id: 309, name: "Monagas", badge: "https://img.sofascore.com/api/v1/team/6233/image", country: "VEN"},
  {id: 310, name: "Zamora", badge: "https://img.sofascore.com/api/v1/team/6237/image", country: "VEN"},
  {id: 311, name: "Las Palmas", badge: "https://img.sofascore.com/api/v1/team/6577/image", country: "ESP"},
  {id: 312, name: "Liverpool UY", badge: "https://img.sofascore.com/api/v1/team/6879/image", country: "URY"},
  {id: 313, name: "Al Ahly", badge: "https://img.sofascore.com/api/v1/team/6910/image", country: "EGY"},
  {id: 314, name: "Barueri", badge: "https://img.sofascore.com/api/v1/team/6956/image", country: "BRA"},
  {id: 315, name: "Guaratinguetá", badge: "https://img.sofascore.com/api/v1/team/6957/image", country: "BRA"},
  {id: 316, name: "Juventus-SP", badge: "https://img.sofascore.com/api/v1/team/6960/image", country: "BRA"},
  {id: 317, name: "Marília", badge: "https://img.sofascore.com/api/v1/team/6961/image", country: "BRA"},
  {id: 318, name: "Noroeste", badge: "https://img.sofascore.com/api/v1/team/6962/image", country: "BRA"},
  {id: 319, name: "Rio Branco-SP", badge: "https://img.sofascore.com/api/v1/team/6964/image", country: "BRA"},
  {id: 320, name: "Rio Claro", badge: "https://img.sofascore.com/api/v1/team/6965/image", country: "BRA"},
  {id: 321, name: "Santo André", badge: "https://img.sofascore.com/api/v1/team/6966/image", country: "BRA"},
  {id: 322, name: "São Bento", badge: "https://img.sofascore.com/api/v1/team/6967/image", country: "BRA"},
  {id: 323, name: "Blooming", badge: "https://img.sofascore.com/api/v1/team/6968/image", country: "BOL"},
  {id: 324, name: "Madureira", badge: "https://img.sofascore.com/api/v1/team/6980/image", country: "BRA"},
  {id: 325, name: "Nova Iguaçu", badge: "https://img.sofascore.com/api/v1/team/6981/image", country: "BRA"},
  {id: 326, name: "Volta Redonda", badge: "https://img.sofascore.com/api/v1/team/6982/image", country: "BRA"},
  {id: 327, name: "Ñublense", badge: "https://img.sofascore.com/api/v1/team/7029/image", country: "CHL"},
  {id: 328, name: "Bolívar", badge: "https://img.sofascore.com/api/v1/team/7059/image", country: "BOL"},
  {id: 329, name: "Ipatinga", badge: "https://img.sofascore.com/api/v1/team/7297/image", country: "BRA"},
  {id: 330, name: "Atlético-GO", badge: "https://img.sofascore.com/api/v1/team/7314/image", country: "BRA"},
  {id: 331, name: "Avaí", badge: "https://img.sofascore.com/api/v1/team/7315/image", country: "BRA"},
  {id: 332, name: "Tigre", badge: "https://img.sofascore.com/api/v1/team/7628/image", country: "ARG"},
  {id: 333, name: "Huracán", badge: "https://img.sofascore.com/api/v1/team/7629/image", country: "ARG"},
  {id: 334, name: "Daejeon Hana", badge: "https://img.sofascore.com/api/v1/team/7645/image", country: "KOR"},
  {id: 335, name: "FC Seoul", badge: "https://img.sofascore.com/api/v1/team/7646/image", country: "KOR"},
  {id: 336, name: "Ulsan", badge: "https://img.sofascore.com/api/v1/team/7653/image", country: "KOR"},
  {id: 337, name: "San Martín", badge: "https://img.sofascore.com/api/v1/team/7772/image", country: "ARG"},
  {id: 338, name: "Jorge Wilstermann", badge: "https://img.sofascore.com/api/v1/team/7878/image", country: "BOL"},
  {id: 339, name: "ABC", badge: "https://img.sofascore.com/api/v1/team/21838/image", country: "BRA"},
  {id: 340, name: "Chapecoense", badge: "https://img.sofascore.com/api/v1/team/21845/image", country: "BRA"},
  {id: 341, name: "Icasa", badge: "https://img.sofascore.com/api/v1/team/21851/image", country: "BRA"},
  {id: 342, name: "Itabaiana", badge: "https://img.sofascore.com/api/v1/team/21853/image", country: "BRA"},
  {id: 343, name: "Boa Esporte", badge: "https://img.sofascore.com/api/v1/team/21854/image", country: "BRA"},
  {id: 344, name: "Sousa", badge: "https://img.sofascore.com/api/v1/team/21864/image", country: "BRA"},
  {id: 345, name: "Trem", badge: "https://img.sofascore.com/api/v1/team/21865/image", country: "BRA"},
  {id: 346, name: "XV de Piracicaba", badge: "https://img.sofascore.com/api/v1/team/61692/image", country: "BRA"},
  {id: 347, name: "Anápolis", badge: "https://img.sofascore.com/api/v1/team/21872/image", country: "BRA"},
  {id: 348, name: "Brusque", badge: "https://img.sofascore.com/api/v1/team/21884/image", country: "BRA"},
  {id: 349, name: "Cascavel", badge: "https://img.sofascore.com/api/v1/team/21891/image", country: "BRA"},
  {id: 350, name: "Cianorte", badge: "https://img.sofascore.com/api/v1/team/21892/image", country: "BRA"},
  {id: 351, name: "Al-Hilal", badge: "https://img.sofascore.com/api/v1/team/21895/image", country: "SAU"},
  {id: 352, name: "Portuguesa", badge: "https://img.sofascore.com/api/v1/team/21896/image", country: "BRA"},
  {id: 353, name: "Duque de Caxias", badge: "https://img.sofascore.com/api/v1/team/21959/image", country: "BRA"},
  {id: 354, name: "Itabuna EC", badge: "https://img.sofascore.com/api/v1/team/21973/image", country: "BRA"},
  {id: 355, name: "Marcílio Dias", badge: "https://img.sofascore.com/api/v1/team/21978/image", country: "BRA"},
  {id: 356, name: "Mirassol", badge: "https://img.sofascore.com/api/v1/team/21982/image", country: "BRA"},
  {id: 357, name: "Novo Hamburgo", badge: "https://img.sofascore.com/api/v1/team/480376/image", country: "BRA"},
  {id: 358, name: "CRB", badge: "https://img.sofascore.com/api/v1/team/22032/image", country: "BRA"},
  {id: 359, name: "Al-Nassr", badge: "https://img.sofascore.com/api/v1/team/23400/image", country: "SAU"},
  {id: 360, name: "Girona", badge: "https://img.sofascore.com/api/v1/team/24264/image", country: "ESP"},
  {id: 361, name: "Huesca", badge: "https://img.sofascore.com/api/v1/team/24265/image", country: "ESP"},
  {id: 362, name: "Cerro Largo", badge: "https://img.sofascore.com/api/v1/team/25009/image", country: "URY"},
  {id: 363, name: "Racing UY", badge: "https://img.sofascore.com/api/v1/team/25010/image", country: "URY"},
  {id: 364, name: "The Strongest", badge: "https://img.sofascore.com/api/v1/team/32529/image", country: "BOL"},
  {id: 365, name: "Ferroviário", badge: "https://img.sofascore.com/api/v1/team/32672/image", country: "BRA"},
  {id: 366, name: "Avenida", badge: "https://img.sofascore.com/api/v1/team/32765/image", country: "BRA"},
  {id: 367, name: "Ypiranga", badge: "https://img.sofascore.com/api/v1/team/32766/image", country: "BRA"},
  {id: 368, name: "São José-RS", badge: "https://img.sofascore.com/api/v1/team/480379/image", country: "BRA"},
  {id: 369, name: "Oeste", badge: "https://img.sofascore.com/api/v1/team/32779/image", country: "BRA"},
  {id: 370, name: "Mogi Mirim", badge: "https://img.sofascore.com/api/v1/team/32781/image", country: "BRA"},
  {id: 371, name: "Uberlândia", badge: "https://img.sofascore.com/api/v1/team/32873/image", country: "BRA"},
  {id: 372, name: "Nacional Asunción", badge: "https://img.sofascore.com/api/v1/team/33001/image", country: "PRY"},
  {id: 373, name: "Deportes Iquique", badge: "https://img.sofascore.com/api/v1/team/33596/image", country: "CHL"},
  {id: 374, name: "Granada", badge: "https://img.sofascore.com/api/v1/team/33779/image", country: "ESP"},
  {id: 375, name: "Oriente Petrolero", badge: "https://img.sofascore.com/api/v1/team/33820/image", country: "BOL"},
  {id: 376, name: "Águia de Marabá", badge: "https://img.sofascore.com/api/v1/team/33998/image", country: "BRA"},
  {id: 377, name: "Mixto", badge: "https://img.sofascore.com/api/v1/team/34005/image", country: "BRA"},
  {id: 378, name: "Potiguar", badge: "https://img.sofascore.com/api/v1/team/34006/image", country: "BRA"},
  {id: 379, name: "Al-Ittihad", badge: "https://img.sofascore.com/api/v1/team/34315/image", country: "SAU"},
  {id: 380, name: "Krasnodar", badge: "https://img.sofascore.com/api/v1/team/34425/image", country: "RUS"},
  {id: 381, name: "Al-Ahli", badge: "https://img.sofascore.com/api/v1/team/34469/image", country: "SAU"},
  {id: 382, name: "Ferroviária", badge: "https://img.sofascore.com/api/v1/team/35285/image", country: "BRA"},
  {id: 383, name: "Leipzig", badge: "https://img.sofascore.com/api/v1/team/36360/image", country: "DEU"},
  {id: 384, name: "Casa Pia", badge: "https://img.sofascore.com/api/v1/team/36365/image", country: "PRT"},
  {id: 385, name: "Deportivo La Guaira", badge: "https://img.sofascore.com/api/v1/team/36437/image", country: "VEN"},
  {id: 386, name: "León", badge: "https://img.sofascore.com/api/v1/team/36534/image", country: "MEX"},
  {id: 387, name: "Platense", badge: "https://img.sofascore.com/api/v1/team/36837/image", country: "ARG"},
  {id: 388, name: "Defensa y Justicia", badge: "https://img.sofascore.com/api/v1/team/36839/image", country: "ARG"},
  {id: 389, name: "Olaria", badge: "https://img.sofascore.com/api/v1/team/39616/image", country: "BRA"},
  {id: 390, name: "Caldense", badge: "https://img.sofascore.com/api/v1/team/39621/image", country: "BRA"},
  {id: 391, name: "Operário-PR", badge: "https://img.sofascore.com/api/v1/team/39634/image", country: "BRA"},
  {id: 392, name: "Luverdense", badge: "https://img.sofascore.com/api/v1/team/40161/image", country: "BRA"},
  {id: 393, name: "Naviraiense", badge: "https://img.sofascore.com/api/v1/team/40168/image", country: "BRA"},
  {id: 394, name: "Sarmiento", badge: "https://img.sofascore.com/api/v1/team/42338/image", country: "ARG"},
  {id: 395, name: "Concórdia", badge: "https://img.sofascore.com/api/v1/team/257674/image", country: "BRA"},
  {id: 396, name: "Linense", badge: "https://img.sofascore.com/api/v1/team/47503/image", country: "BRA"},
  {id: 397, name: "São Bernardo", badge: "https://img.sofascore.com/api/v1/team/47504/image", country: "BRA"},
  {id: 398, name: "Nacional Potosí", badge: "https://img.sofascore.com/api/v1/team/47700/image", country: "BOL"},
  {id: 399, name: "Unión La Calera", badge: "https://img.sofascore.com/api/v1/team/48242/image", country: "CHL"},
  {id: 400, name: "Botafogo-PB", badge: "https://img.sofascore.com/api/v1/team/49196/image", country: "BRA"},
  {id: 401, name: "Comercial-PI", badge: "https://img.sofascore.com/api/v1/team/49200/image", country: "BRA"},
  {id: 402, name: "Cuiabá", badge: "https://img.sofascore.com/api/v1/team/49202/image", country: "BRA"},
  {id: 403, name: "Famalicão", badge: "https://img.sofascore.com/api/v1/team/49531/image", country: "PRT"},
  {id: 404, name: "Comercial-SP", badge: "https://img.sofascore.com/api/v1/team/61690/image", country: "BRA"},
  {id: 405, name: "Juazeirense", badge: "https://img.sofascore.com/api/v1/team/61724/image", country: "BRA"},
  {id: 406, name: "Barracas", badge: "https://img.sofascore.com/api/v1/team/65668/image", country: "ARG"},
  {id: 407, name: "Central Córdoba", badge: "https://img.sofascore.com/api/v1/team/65676/image", country: "ARG"},
  {id: 408, name: "Maracanã", badge: "https://img.sofascore.com/api/v1/team/87156/image", country: "BRA"},
  {id: 409, name: "Jacuipense", badge: "https://img.sofascore.com/api/v1/team/87166/image", country: "BRA"},
  {id: 410, name: "Tombense", badge: "https://img.sofascore.com/api/v1/team/87202/image", country: "BRA"},
  {id: 411, name: "Capivariano", badge: "https://img.sofascore.com/api/v1/team/88738/image", country: "BRA"},
  {id: 412, name: "Cametá", badge: "https://img.sofascore.com/api/v1/team/90272/image", country: "BRA"},
  {id: 413, name: "Betim", badge: "https://img.sofascore.com/api/v1/team/368413/image", country: "BRA"},
  {id: 414, name: "Aimoré", badge: "https://img.sofascore.com/api/v1/team/480383/image", country: "BRA"},
  {id: 415, name: "Mushuc Runa", badge: "https://img.sofascore.com/api/v1/team/134976/image", country: "ECU"},
  {id: 416, name: "Maringá", badge: "https://img.sofascore.com/api/v1/team/135324/image", country: "BRA"},
  {id: 417, name: "Água Santa", badge: "https://img.sofascore.com/api/v1/team/135510/image", country: "BRA"},
  {id: 418, name: "Novorizontino", badge: "https://img.sofascore.com/api/v1/team/135514/image", country: "BRA"},
  {id: 419, name: "Votuporanguense", badge: "https://img.sofascore.com/api/v1/team/135524/image", country: "BRA"},
  {id: 420, name: "Inter de Limeira", badge: "https://img.sofascore.com/api/v1/team/135526/image", country: "BRA"},
  {id: 421, name: "Princesa", badge: "https://img.sofascore.com/api/v1/team/144854/image", country: "BRA"},
  {id: 422, name: "Orlando City", badge: "https://img.sofascore.com/api/v1/team/52237/image", country: "USA"},
  {id: 423, name: "Metropolitanos", badge: "https://img.sofascore.com/api/v1/team/162480/image", country: "VEN"},
  {id: 424, name: "Boston River", badge: "https://img.sofascore.com/api/v1/team/174970/image", country: "URY"},
  {id: 425, name: "Pyramids", badge: "https://img.sofascore.com/api/v1/team/175002/image", country: "EGY"},
  {id: 426, name: "Lemense", badge: "https://img.sofascore.com/api/v1/team/188775/image", country: "BRA"},
  {id: 427, name: "Primavera", badge: "https://img.sofascore.com/api/v1/team/188777/image", country: "BRA"},
  {id: 428, name: "Ríver-PI", badge: "https://img.sofascore.com/api/v1/team/188849/image", country: "BRA"},
  {id: 429, name: "Alecrim", badge: "https://img.sofascore.com/api/v1/team/189493/image", country: "BRA"},
  {id: 430, name: "Rochester United", badge: "https://img.sofascore.com/api/v1/team/206439/image", country: "ENG"},
  {id: 431, name: "Portuguesa-RJ", badge: "https://img.sofascore.com/api/v1/team/208067/image", country: "BRA"},
  {id: 432, name: "Delfín", badge: "https://img.sofascore.com/api/v1/team/213638/image", country: "ECU"},
  {id: 433, name: "Tocantinópolis", badge: "https://img.sofascore.com/api/v1/team/215371/image", country: "BRA"},
  {id: 434, name: "EC São Bernardo", badge: "https://img.sofascore.com/api/v1/team/224647/image", country: "BRA"},
  {id: 435, name: "Portuguesa Santista", badge: "https://img.sofascore.com/api/v1/team/225186/image", country: "BRA"},
  {id: 436, name: "Altos", badge: "https://img.sofascore.com/api/v1/team/228199/image", country: "BRA"},
  {id: 437, name: "Puerto Cabello", badge: "https://img.sofascore.com/api/v1/team/230725/image", country: "VEN"},
  {id: 438, name: "Hercílio Luz", badge: "https://img.sofascore.com/api/v1/team/234222/image", country: "BRA"},
  {id: 439, name: "Afogados", badge: "https://img.sofascore.com/api/v1/team/242130/image", country: "BRA"},
  {id: 440, name: "Atlanta", badge: "https://img.sofascore.com/api/v1/team/243211/image", country: "USA"},
  {id: 441, name: "Grêmio Prudente", badge: "https://img.sofascore.com/api/v1/team/252408/image", country: "BRA"},
  {id: 442, name: "XV de Jaú", badge: "https://img.sofascore.com/api/v1/team/389971/image", country: "BRA"},
  {id: 443, name: "Sampaio Corrêa-RJ", badge: "https://img.sofascore.com/api/v1/team/257632/image", country: "BRA"},
  {id: 444, name: "Everton (LP)", badge: "https://img.sofascore.com/api/v1/team/260041/image", country: "ARG"},
  {id: 445, name: "Universitario de Vinto", badge: "https://img.sofascore.com/api/v1/team/268082/image", country: "BOL"},
  {id: 446, name: "Always Ready", badge: "https://img.sofascore.com/api/v1/team/268083/image", country: "BOL"},
  {id: 447, name: "Floresta", badge: "https://img.sofascore.com/api/v1/team/274286/image", country: "BRA"},
  {id: 448, name: "Atlético Grau", badge: "https://img.sofascore.com/api/v1/team/282538/image", country: "PER"},
  {id: 449, name: "Maricá", badge: "https://img.sofascore.com/api/v1/team/288535/image", country: "BRA"},
  {id: 450, name: "Hertha Munich", badge: "https://img.sofascore.com/api/v1/team/289586/image", country: "DEU"},
  {id: 451, name: "Humaitá", badge: "https://img.sofascore.com/api/v1/team/293460/image", country: "BRA"},
  {id: 452, name: "Costa Rica-MS", badge: "https://img.sofascore.com/api/v1/team/308001/image", country: "BRA"},
  {id: 453, name: "Real Santa Cruz", badge: "https://img.sofascore.com/api/v1/team/327860/image", country: "BOL"},
  {id: 454, name: "Tuna Luso", badge: "https://img.sofascore.com/api/v1/team/333422/image", country: "BRA"},
  {id: 455, name: "Real Tomayapo", badge: "https://img.sofascore.com/api/v1/team/335685/image", country: "BOL"},
  {id: 456, name: "Amazonas", badge: "https://img.sofascore.com/api/v1/team/336664/image", country: "BRA"},
  {id: 457, name: "Inter Miami", badge: "https://img.sofascore.com/api/v1/team/337602/image", country: "USA"},
  {id: 458, name: "Pouso Alegre", badge: "https://img.sofascore.com/api/v1/team/343540/image", country: "BRA"},
  {id: 459, name: "Democrata (SL)", badge: "https://img.sofascore.com/api/v1/team/343628/image", country: "BRA"},
  {id: 460, name: "Independiente Petrolero", badge: "https://img.sofascore.com/api/v1/team/372975/image", country: "BOL"},
  {id: 461, name: "Fluminense-PI", badge: "https://img.sofascore.com/api/v1/team/375317/image", country: "BRA"},
  {id: 462, name: "Azuriz", badge: "https://img.sofascore.com/api/v1/team/375853/image", country: "BRA"},
  {id: 463, name: "Barcelona de Ilhéus", badge: "https://img.sofascore.com/api/v1/team/386170/image", country: "BRA"},
  {id: 464, name: "Rayo Zuliano", badge: "https://img.sofascore.com/api/v1/team/386310/image", country: "VEN"},
  {id: 465, name: "Aymorés", badge: "https://img.sofascore.com/api/v1/team/388220/image", country: "BRA"},
  {id: 466, name: "San Antonio Bulo-Bulo", badge: "https://img.sofascore.com/api/v1/team/396625/image", country: "BOL"},
  {id: 467, name: "Chievo Verona", badge: "https://img.sofascore.com/api/v1/team/396932/image", country: "ITA"},
  {id: 468, name: "Aster Brasil", badge: "https://img.sofascore.com/api/v1/team/401092/image", country: "BRA"},
  {id: 469, name: "Itabirito", badge: "https://img.sofascore.com/api/v1/team/454864/image", country: "BRA"},
  {id: 470, name: "Deportivo Garcilaso", badge: "https://img.sofascore.com/api/v1/team/458584/image", country: "PER"},
  {id: 471, name: "Albânia", badge: "/images/countries/albania.svg", country: "ALB", national: true},
  {id: 472, name: "Argélia", badge: "/images/countries/algeria.svg", country: "DZA", national: true},
  {id: 473, name: "Andorra", badge: "/images/countries/andorra.svg", country: "AND", national: true},
  {id: 474, name: "Angola", badge: "/images/countries/angola.svg", country: "AGO", national: true},
  {id: 475, name: "Argentina", badge: "/images/countries/argentina.svg", country: "ARG", national: true},
  {id: 476, name: "Armênia", badge: "/images/countries/armenia.svg", country: "ARM", national: true},
  {id: 477, name: "Austrália", badge: "/images/countries/australia.svg", country: "AUS", national: true},
  {id: 478, name: "Áustria", badge: "/images/countries/austria.svg", country: "AUT", national: true},
  {id: 479, name: "Azerbaijão", badge: "/images/countries/azerbaijan.svg", country: "AZE", national: true},
  {id: 480, name: "Bahamas", badge: "/images/countries/bahamas.svg", country: "BHS", national: true},
  {id: 481, name: "Bangladesh", badge: "/images/countries/bangladesh.svg", country: "BGD", national: true},
  {id: 482, name: "Bielorrússia", badge: "/images/countries/belarus.svg", country: "BLR", national: true},
  {id: 483, name: "Bélgica", badge: "/images/countries/belgium.svg", country: "BEL", national: true},
  {id: 484, name: "Benim", badge: "/images/countries/benin.svg", country: "BEN", national: true},
  {id: 485, name: "Bolívia", badge: "/images/countries/bolivia.svg", country: "BOL", national: true},
  {id: 486, name: "Bósnia e Herzegovina", badge: "/images/countries/bosnia-and-herzegovina.svg", country: "BIH", national: true},
  {id: 487, name: "Botswana", badge: "/images/countries/botswana.svg", country: "BWA", national: true},
  {id: 488, name: "Brasil", badge: "/images/countries/brazil.svg", country: "BRA", national: true},
  {id: 489, name: "Bulgária", badge: "/images/countries/bulgaria.svg", country: "BGR", national: true},
  {id: 490, name: "Burquina Fasso", badge: "/images/countries/burkina-faso.svg", country: "BFA", national: true},
  {id: 491, name: "Burundi", badge: "/images/countries/burundi.svg", country: "BDI", national: true},
  {id: 492, name: "Camarões", badge: "/images/countries/cameroon.svg", country: "CMR", national: true},
  {id: 493, name: "Canadá", badge: "/images/countries/canada.svg", country: "CAN", national: true},
  {id: 494, name: "Cabo Verde", badge: "/images/countries/cape-verde.svg", country: "CPV", national: true},
  {id: 495, name: "Ilhas Caimã", badge: "/images/countries/cayman-islands.svg", country: "CYM", national: true},
  {id: 496, name: "República Centro-Africana", badge: "/images/countries/central-african-republic.svg", country: "CAF", national: true},
  {id: 497, name: "Chade", badge: "/images/countries/chad.svg", country: "TCD", national: true},
  {id: 498, name: "Chile", badge: "/images/countries/chile.svg", country: "CHL", national: true},
  {id: 499, name: "China", badge: "/images/countries/china.svg", country: "CHN", national: true},
  {id: 500, name: "Colômbia", badge: "/images/countries/colombia.svg", country: "COL", national: true},
  {id: 501, name: "Comores", badge: "/images/countries/comoros.svg", country: "COM", national: true},
  {id: 502, name: "República do Congo", badge: "/images/countries/congo.svg", country: "COG", national: true},
  {id: 503, name: "Costa Rica", badge: "/images/countries/costa-rica.svg", country: "CRI", national: true},
  {id: 504, name: "Costa do Marfim", badge: "/images/countries/cote-divoire.svg", country: "CIV", national: true},
  {id: 505, name: "Croácia", badge: "/images/countries/croatia.svg", country: "HRV", national: true},
  {id: 506, name: "Cuba", badge: "/images/countries/cuba.svg", country: "CUB", national: true},
  {id: 507, name: "Chipre", badge: "/images/countries/cyprus.svg", country: "CYP", national: true},
  {id: 508, name: "República Tcheca", badge: "/images/countries/czechia.svg", country: "CZE", national: true},
  {id: 509, name: "Dinamarca", badge: "/images/countries/denmark.svg", country: "DNK", national: true},
  {id: 510, name: "Djibuti", badge: "/images/countries/djibouti.svg", country: "DJI", national: true},
  {id: 511, name: "República Dominicana", badge: "/images/countries/dominican-republic.svg", country: "DOM", national: true},
  {id: 512, name: "Equador", badge: "/images/countries/ecuador.svg", country: "ECU", national: true},
  {id: 513, name: "Egito", badge: "/images/countries/egypt.svg", country: "EGY", national: true},
  {id: 514, name: "El Salvador", badge: "/images/countries/el-salvador.svg", country: "SLV", national: true},
  {id: 515, name: "Inglaterra", badge: "/images/countries/england.svg", country: "ENG", national: true},
  {id: 516, name: "Guiné Equatorial", badge: "/images/countries/equatorial-guinea.svg", country: "GNQ", national: true},
  {id: 517, name: "Eritreia", badge: "/images/countries/eritrea.svg", country: "ERI", national: true},
  {id: 518, name: "Estônia", badge: "/images/countries/estonia.svg", country: "EST", national: true},
  {id: 519, name: "Essuatíni", badge: "/images/countries/eswatini.svg", country: "SWZ", national: true},
  {id: 520, name: "Etiópia", badge: "/images/countries/ethiopia.svg", country: "ETH", national: true},
  {id: 521, name: "Ilhas Faroe", badge: "/images/countries/faroe-islands.svg", country: "FRO", national: true},
  {id: 522, name: "Finlândia", badge: "/images/countries/finland.svg", country: "FIN", national: true},
  {id: 523, name: "França", badge: "/images/countries/france.svg", country: "FRA", national: true},
  {id: 524, name: "Gabão", badge: "/images/countries/gabon.svg", country: "GAB", national: true},
  {id: 525, name: "Gâmbia", badge: "/images/countries/gambia.svg", country: "GMB", national: true},
  {id: 526, name: "Geórgia", badge: "/images/countries/georgia.svg", country: "GEO", national: true},
  {id: 527, name: "Alemanha", badge: "/images/countries/germany.svg", country: "DEU", national: true},
  {id: 528, name: "Gana", badge: "/images/countries/ghana.svg", country: "GHA", national: true},
  {id: 529, name: "Gibraltar", badge: "/images/countries/gibraltar.svg", country: "GIB", national: true},
  {id: 530, name: "Grécia", badge: "/images/countries/greece.svg", country: "GRC", national: true},
  {id: 531, name: "Guatemala", badge: "/images/countries/guatemala.svg", country: "GTM", national: true},
  {id: 532, name: "Guiné", badge: "/images/countries/guinea.svg", country: "GIN", national: true},
  {id: 533, name: "Guiné-Bissau", badge: "/images/countries/guinea-bissau.svg", country: "GNB", national: true},
  {id: 534, name: "Haiti", badge: "/images/countries/haiti.svg", country: "HTI", national: true},
  {id: 535, name: "Honduras", badge: "/images/countries/honduras.svg", country: "HND", national: true},
  {id: 536, name: "Hungria", badge: "/images/countries/hungary.svg", country: "HUN", national: true},
  {id: 537, name: "Islândia", badge: "/images/countries/iceland.svg", country: "ISL", national: true},
  {id: 538, name: "Índia", badge: "/images/countries/india.svg", country: "IND", national: true},
  {id: 539, name: "Indonésia", badge: "/images/countries/indonesia.svg", country: "IDN", national: true},
  {id: 540, name: "Irã", badge: "/images/countries/iran.svg", country: "IRN", national: true},
  {id: 541, name: "Iraque", badge: "/images/countries/iraq.svg", country: "IRQ", national: true},
  {id: 542, name: "Irlanda", badge: "/images/countries/ireland.svg", country: "IRL", national: true},
  {id: 543, name: "Israel", badge: "/images/countries/israel.svg", country: "ISR", national: true},
  {id: 544, name: "Itália", badge: "/images/countries/italy.svg", country: "ITA", national: true},
  {id: 545, name: "Jamaica", badge: "/images/countries/jamaica.svg", country: "JAM", national: true},
  {id: 546, name: "Japão", badge: "/images/countries/japan.svg", country: "JPN", national: true},
  {id: 547, name: "Cazaquistão", badge: "/images/countries/kazakhstan.svg", country: "KAZ", national: true},
  {id: 548, name: "Quênia", badge: "/images/countries/kenya.svg", country: "KEN", national: true},
  {id: 549, name: "Kosovo", badge: "/images/countries/kosovo.svg", country: "KOS", national: true},
  {id: 550, name: "Letônia", badge: "/images/countries/latvia.svg", country: "LVA", national: true},
  {id: 551, name: "Líbano", badge: "/images/countries/lebanon.svg", country: "LBN", national: true},
  {id: 552, name: "Lesoto", badge: "/images/countries/lesotho.svg", country: "LSO", national: true},
  {id: 553, name: "Libéria", badge: "/images/countries/liberia.svg", country: "LBR", national: true},
  {id: 554, name: "Líbia", badge: "/images/countries/libya.svg", country: "LBY", national: true},
  {id: 555, name: "Liechtenstein", badge: "/images/countries/liechtenstein.svg", country: "LIE", national: true},
  {id: 556, name: "Lituânia", badge: "/images/countries/lithuania.svg", country: "LTU", national: true},
  {id: 557, name: "Luxemburgo", badge: "/images/countries/luxembourg.svg", country: "LUX", national: true},
  {id: 558, name: "Madagascar", badge: "/images/countries/madagascar.svg", country: "MDG", national: true},
  {id: 559, name: "Malawi", badge: "/images/countries/malawi.svg", country: "MWI", national: true},
  {id: 560, name: "Malásia", badge: "/images/countries/malaysia.svg", country: "MIS", national: true},
  {id: 561, name: "Mali", badge: "/images/countries/mali.svg", country: "MLI", national: true},
  {id: 562, name: "Malta", badge: "/images/countries/malta.svg", country: "MLT", national: true},
  {id: 563, name: "Mauritânia", badge: "/images/countries/mauritania.svg", country: "MRT", national: true},
  {id: 564, name: "Ilhas Maurícias", badge: "/images/countries/mauritius.svg", country: "MUS", national: true},
  {id: 565, name: "México", badge: "/images/countries/mexico.svg", country: "MEX", national: true},
  {id: 566, name: "Moldávia", badge: "/images/countries/moldova.svg", country: "MDA", national: true},
  {id: 567, name: "Mongólia", badge: "/images/countries/mongolia.svg", country: "MNG", national: true},
  {id: 568, name: "Montenegro", badge: "/images/countries/montenegro.svg", country: "MNE", national: true},
  {id: 569, name: "Monserrate", badge: "/images/countries/montserrat.svg", country: "MSR", national: true},
  {id: 570, name: "Marrocos", badge: "/images/countries/morocco.svg", country: "MAR", national: true},
  {id: 571, name: "Moçambique", badge: "/images/countries/mozambique.svg", country: "MOZ", national: true},
  {id: 572, name: "Namíbia", badge: "/images/countries/namibia.svg", country: "NAM", national: true},
  {id: 573, name: "Nauru", badge: "/images/countries/nauru.svg", country: "NRU", national: true},
  {id: 574, name: "Holanda", badge: "/images/countries/netherlands.svg", country: "NLD", national: true},
  {id: 575, name: "Nova Caledônia", badge: "/images/countries/new-caledonia.svg", country: "NCL", national: true},
  {id: 576, name: "Nova Zelândia", badge: "/images/countries/new-zealand.svg", country: "NZL", national: true},
  {id: 577, name: "Nicarágua", badge: "/images/countries/nicaragua.svg", country: "NIC", national: true},
  {id: 578, name: "Níger", badge: "/images/countries/niger.svg", country: "NER", national: true},
  {id: 579, name: "Nigéria", badge: "/images/countries/nigeria.svg", country: "NGA", national: true},
  {id: 580, name: "Irlanda do Norte", badge: "/images/countries/northern-ireland.png", country: "NIR", national: true},
  {id: 581, name: "Macedônia do Norte", badge: "/images/countries/north-macedonia.svg", country: "MKD", national: true},
  {id: 582, name: "Noruega", badge: "/images/countries/norway.svg", country: "NOR", national: true},
  {id: 583, name: "Paquistão", badge: "/images/countries/pakistan.svg", country: "PAK", national: true},
  {id: 584, name: "Panamá", badge: "/images/countries/panama.svg", country: "PAN", national: true},
  {id: 585, name: "Paraguai", badge: "/images/countries/paraguay.svg", country: "PRY", national: true},
  {id: 586, name: "Peru", badge: "/images/countries/peru.svg", country: "PER", national: true},
  {id: 587, name: "Filipinas", badge: "/images/countries/philippines.svg", country: "PHL", national: true},
  {id: 588, name: "Polônia", badge: "/images/countries/poland.svg", country: "POL", national: true},
  {id: 589, name: "Portugal", badge: "/images/countries/portugal.svg", country: "PRT", national: true},
  {id: 590, name: "Catar", badge: "/images/countries/qatar.svg", country: "QAT", national: true},
  {id: 591, name: "República Democrática do Congo", badge: "/images/countries/rd-congo.svg", country: "COD", national: true},
  {id: 592, name: "Romênia", badge: "/images/countries/romania.svg", country: "ROU", national: true},
  {id: 593, name: "Russia", badge: "/images/countries/russia.svg", country: "RUS", national: true},
  {id: 594, name: "Ruanda", badge: "/images/countries/rwanda.svg", country: "RWA", national: true},
  {id: 595, name: "Samoa Americana", badge: "/images/countries/samoa.svg", country: "ASM", national: true},
  {id: 596, name: "San Marino", badge: "/images/countries/san-marino.svg", country: "SMR", national: true},
  {id: 597, name: "São Tomé e Príncipe", badge: "/images/countries/sao-tome-and-principe.svg", country: "STP", national: true},
  {id: 598, name: "Arábia Saudita", badge: "/images/countries/saudi-arabia.svg", country: "SAU", national: true},
  {id: 599, name: "Escócia", badge: "/images/countries/scotland.svg", country: "SCT", national: true},
  {id: 600, name: "Senegal", badge: "/images/countries/senegal.svg", country: "SEN", national: true},
  {id: 601, name: "Sérvia", badge: "/images/countries/serbia.svg", country: "SRB", national: true},
  {id: 602, name: "Seychelles", badge: "/images/countries/seychelles.svg", country: "SYC", national: true},
  {id: 603, name: "Serra Leoa", badge: "/images/countries/sierra-leone.svg", country: "SLE", national: true},
  {id: 604, name: "Singapura", badge: "/images/countries/singapore.svg", country: "SGP", national: true},
  {id: 605, name: "Eslováquia", badge: "/images/countries/slovakia.svg", country: "SVK", national: true},
  {id: 606, name: "Eslovênia", badge: "/images/countries/slovenia.svg", country: "SVN", national: true},
  {id: 607, name: "Ilhas Salomão", badge: "/images/countries/solomon-islands.svg", country: "SLB", national: true},
  {id: 608, name: "Somália", badge: "/images/countries/somalia.svg", country: "SOM", national: true},
  {id: 609, name: "África do Sul", badge: "/images/countries/south-africa.svg", country: "ZAF", national: true},
  {id: 610, name: "Coreia do Sul", badge: "/images/countries/south-korea.svg", country: "KOR", national: true},
  {id: 611, name: "Sudão do Sul", badge: "/images/countries/south-sudan.svg", country: "SSD", national: true},
  {id: 612, name: "Espanha", badge: "/images/countries/spain.svg", country: "ESP", national: true},
  {id: 613, name: "Sri Lanka", badge: "/images/countries/sri-lanka.svg", country: "LKA", national: true},
  {id: 614, name: "São Cristóvão e Neves", badge: "/images/countries/st-kitts-and-nevis.svg", country: "KNA", national: true},
  {id: 615, name: "Santa Lúcia", badge: "/images/countries/st-lucia.svg", country: "LCA", national: true},
  {id: 616, name: "São Vicente e Granadinas", badge: "/images/countries/st-vincent-and-grenadines.svg", country: "VCT", national: true},
  {id: 617, name: "Sudão", badge: "/images/countries/sudan.svg", country: "SDN", national: true},
  {id: 618, name: "Suriname", badge: "/images/countries/suriname.svg", country: "SUR", national: true},
  {id: 619, name: "Suécia", badge: "/images/countries/sweden.svg", country: "SWE", national: true},
  {id: 620, name: "Suíça", badge: "/images/countries/switzerland.svg", country: "CHE", national: true},
  {id: 621, name: "Tajiquistão", badge: "/images/countries/tajikistan.svg", country: "TJK", national: true},
  {id: 622, name: "Tanzânia", badge: "/images/countries/tanzania.svg", country: "TZA", national: true},
  {id: 623, name: "Tailândia", badge: "/images/countries/thailand.svg", country: "THA", national: true},
  {id: 624, name: "Togo", badge: "/images/countries/togo.svg", country: "TGO", national: true},
  {id: 625, name: "Trindade e Tobago", badge: "/images/countries/trinidad-and-tobago.svg", country: "TTO", national: true},
  {id: 626, name: "Tunísia", badge: "/images/countries/tunisia.svg", country: "TUN", national: true},
  {id: 627, name: "Turquia", badge: "/images/countries/turkey.svg", country: "TUR", national: true},
  {id: 628, name: "Uganda", badge: "/images/countries/uganda.svg", country: "UGA", national: true},
  {id: 629, name: "Ucrânia", badge: "/images/countries/ukraine.svg", country: "UKR", national: true},
  {id: 630, name: "Emirados Árabes Unidos", badge: "/images/countries/united-arab-emirates.svg", country: "ARE", national: true},
  {id: 631, name: "Estados Unidos", badge: "/images/countries/united-states.svg", country: "USA", national: true},
  {id: 632, name: "Uruguai", badge: "/images/countries/uruguay.svg", country: "URY", national: true},
  {id: 633, name: "Uzbequistão", badge: "/images/countries/uzbekistan.svg", country: "UZB", national: true},
  {id: 634, name: "Venezuela", badge: "/images/countries/venezuela.svg", country: "VEN", national: true},
  {id: 635, name: "Vietnã", badge: "/images/countries/vietnam.svg", country: "VNM", national: true},
  {id: 636, name: "País de Gales", badge: "/images/countries/wales.svg", country: "WAL", national: true},
  {id: 637, name: "Zâmbia", badge: "/images/countries/zambia.svg", country: "ZMB", national: true},
  {id: 638, name: "Zimbabwe", badge: "/images/countries/zimbabwe.svg", country: "ZWE", national: true},
  {id: 639, name: "Alves Dias", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 640, name: "Anchieta", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 641, name: "Assunção", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 642, name: "Baeta Neves", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 643, name: "Bairro dos Casa", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 644, name: "Chácara Inglesa", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 645, name: "Demarchi", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 646, name: "Jardim Batistini", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 647, name: "Jardim Calux", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 648, name: "Jardim Campestre", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 649, name: "Jardim Cláudia", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 650, name: "Jardim Colombo", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 651, name: "Jardim Colonial", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 652, name: "Jardim Detroid", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 653, name: "Jardim Independência", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 654, name: "Jardim Ipanema", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 655, name: "Jardim Ipê", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 656, name: "Jardim Las Palmas", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 657, name: "Jardim Las Vegas", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 658, name: "Jardim Laura", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 659, name: "Jardim Los Angeles", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 660, name: "Jardim Piraporinha", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 661, name: "Jardim Represa", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 662, name: "Jardim Telma", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 663, name: "Jardim Vergueiro", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 664, name: "Jardim do Lago", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 665, name: "Jardim do Mar", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 666, name: "Jordanópolis", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 667, name: "Ferrazópolis", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 668, name: "Mizuo", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 669, name: "Nova Petrópolis", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 670, name: "Orquídeas", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 671, name: "Paradão", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 672, name: "Parque Avaí", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 673, name: "Parque Espacial", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 674, name: "Parque dos Pássaros", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 675, name: "Parque Imigrantes", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 676, name: "Parque Terra Nova", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 677, name: "Paulicéia", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 678, name: "Planalto", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 679, name: "Químicos", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 680, name: "Rudge Ramos", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 681, name: "Sítio Bom Jesus", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 682, name: "Sítio dos Vianas", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 683, name: "Taboão", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 684, name: "Vila Alvarenga", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 685, name: "Vila Aurora", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 686, name: "Vila Capivari", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 687, name: "Vila Cooperativa", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 688, name: "Vila Euclides", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 689, name: "Vila Euro", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 690, name: "Vila Floresta", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 691, name: "Vila Marchi", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 692, name: "Vila Rosa", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 693, name: "Vila São Pedro", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 694, name: "Vila Vitória", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 695, name: "Bairro da Sé", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 696, name: "Freguesia do Ó", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 697, name: "Itaim Paulista", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 698, name: "Itaquera", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 699, name: "Jabaquara", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 700, name: "Jardins", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 701, name: "Jardim Belém", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 702, name: "Jardim Imperial", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 703, name: "Jardim Limoeiro", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 704, name: "Jardim Primavera", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 705, name: "Jardim Turquesa", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 706, name: "Lapa", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 707, name: "Liberdade", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 708, name: "Moca", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 709, name: "Moema", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 710, name: "Morumbi", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 711, name: "Parque Primavera", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 712, name: "Pinheiros", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 713, name: "Planalto Paulista", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 714, name: "Tatuapé", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 715, name: "Tietê", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 716, name: "Vila Alpina", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 717, name: "Vila Alvinópolis", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 718, name: "Vila Brás", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 719, name: "Vila Brasilândia", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 720, name: "Vila Clemente", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 721, name: "Vila Guilherme", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 722, name: "Vila Ipiranga", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 723, name: "Vila Leopoldina", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 724, name: "Vila Lobos", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 725, name: "Vila Madalena", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 726, name: "Vila Olímpia", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 727, name: "Vila Paulina", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 728, name: "Vila Paulista", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 729, name: "Vila Prudente", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 730, name: "Vila Ré", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 731, name: "Vila Rica", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 732, name: "Vila Rio Claro", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 733, name: "Vila Romana", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 734, name: "Vila Saúde", badge: "/images/leagues/brazilian-league.png", custom: true, country: "BRA"},
  {id: 735, name: "Bariloche", badge: "/images/leagues/argentinian-league.png", custom: true, country: "ARG"},
  {id: 736, name: "Jardim Lopez", badge: "/images/leagues/argentinian-league.png", custom: true, country: "ARG"},
  {id: 737, name: "Jardim Mendonza", badge: "/images/leagues/argentinian-league.png", custom: true, country: "ARG"},
  {id: 738, name: "Vila Banfield", badge: "/images/leagues/argentinian-league.png", custom: true, country: "ARG"},
  {id: 739, name: "Vila Buenos Aires", badge: "/images/leagues/argentinian-league.png", custom: true, country: "ARG"},
  {id: 740, name: "Vila Ortobom", badge: "/images/leagues/argentinian-league.png", custom: true, country: "ARG"},
  {id: 741, name: "Vila Rosário", badge: "/images/leagues/argentinian-league.png", custom: true, country: "ARG"},
  {id: 742, name: "Vila Santa Rosa", badge: "/images/leagues/argentinian-league.png", custom: true, country: "ARG"},
  {id: 743, name: "Vila Tucumán", badge: "/images/leagues/argentinian-league.png", custom: true, country: "ARG"},
  {id: 744, name: "Vila Mercedez", badge: "/images/leagues/argentinian-league.png", custom: true, country: "ARG"},
  {id: 745, name: "Cancún", badge: "/images/leagues/mexican-league.png", custom: true, country: "MEX"},
  {id: 746, name: "Huatulco", badge: "/images/leagues/mexican-league.png", custom: true, country: "MEX"},
  {id: 747, name: "Jardim Asteca", badge: "/images/leagues/mexican-league.png", custom: true, country: "MEX"},
  {id: 748, name: "Jardim Laguna", badge: "/images/leagues/mexican-league.png", custom: true, country: "MEX"},
  {id: 749, name: "Jardim Tijuana", badge: "/images/leagues/mexican-league.png", custom: true, country: "MEX"},
  {id: 750, name: "Olarya", badge: "/images/leagues/mexican-league.png", custom: true, country: "MEX"},
  {id: 751, name: "Vila América", badge: "/images/leagues/mexican-league.png", custom: true, country: "MEX"},
  {id: 752, name: "Vila Monterrey", badge: "/images/leagues/mexican-league.png", custom: true, country: "MEX"},
  {id: 753, name: "Vila Titaco", badge: "/images/leagues/mexican-league.png", custom: true, country: "MEX"},
  {id: 754, name: "Vila Yucatán", badge: "/images/leagues/mexican-league.png", custom: true, country: "MEX"},
  {id: 755, name: "Brooklin", badge: "/images/leagues/american-league.png", custom: true, country: "USA"},
  {id: 756, name: "Parque Hood River", badge: "/images/leagues/american-league.png", custom: true, country: "USA"},
  {id: 757, name: "Jardim Dallas", badge: "/images/leagues/american-league.png", custom: true, country: "USA"},
  {id: 758, name: "Jardim Lancaster", badge: "/images/leagues/american-league.png", custom: true, country: "USA"},
  {id: 759, name: "Nashville", badge: "/images/leagues/american-league.png", custom: true, country: "USA"},
  {id: 760, name: "Palm Island", badge: "/images/leagues/american-league.png", custom: true, country: "USA"},
  {id: 761, name: "Vila Phoenix", badge: "/images/leagues/american-league.png", custom: true, country: "USA"},
  {id: 762, name: "Vila Portland", badge: "/images/leagues/american-league.png", custom: true, country: "USA"},
  {id: 763, name: "Jardim Ametista", badge: "/images/leagues/colombian-league.png", custom: true, country: "COL"},
  {id: 764, name: "Jardim Aliança", badge: "/images/leagues/colombian-league.png", custom: true, country: "COL"},
  {id: 765, name: "Jardim Cali", badge: "/images/leagues/colombian-league.png", custom: true, country: "COL"},
  {id: 766, name: "Vila Candelária", badge: "/images/leagues/colombian-league.png", custom: true, country: "COL"},
  {id: 767, name: "Vila Medellín", badge: "/images/leagues/colombian-league.png", custom: true, country: "COL"},
  {id: 768, name: "Jardim Bellavista", badge: "/images/leagues/colombian-league.png", custom: true, country: "COL"},
  {id: 769, name: "Turmalina", badge: "/images/leagues/colombian-league.png", custom: true, country: "COL"},
  {id: 770, name: "Parque Industrial", badge: "/images/leagues/colombian-league.png", custom: true, country: "COL"},
  {id: 771, name: "Bairro Únion", badge: "/images/leagues/chilean-league.png", custom: true, country: "CHL"},
  {id: 772, name: "Vila Salinitas", badge: "/images/leagues/chilean-league.png", custom: true, country: "CHL"},
  {id: 773, name: "Jardim Santiago", badge: "/images/leagues/chilean-league.png", custom: true, country: "CHL"},
  {id: 774, name: "Jardim Valência", badge: "/images/leagues/chilean-league.png", custom: true, country: "CHL"},
  {id: 775, name: "Vila Águilas", badge: "/images/leagues/chilean-league.png", custom: true, country: "CHL"},
  {id: 776, name: "Vila Santander", badge: "/images/leagues/chilean-league.png", custom: true, country: "CHL"},
  {id: 777, name: "Vila Estación Central", badge: "/images/leagues/chilean-league.png", custom: true, country: "CHL"},
  {id: 778, name: "Jardim Del Este", badge: "/images/leagues/chilean-league.png", custom: true, country: "CHL"},
  {id: 779, name: "Vila Real Audiencia", badge: "/images/leagues/chilean-league.png", custom: true, country: "CHL"},
  {id: 780, name: "Jardim Atacama", badge: "/images/leagues/chilean-league.png", custom: true, country: "CHL"},
  {id: 781, name: "Castanhal", badge: "/images/leagues/uruguayan-league.png", custom: true, country: "URY"},
  {id: 782, name: "Jardim Castillos", badge: "/images/leagues/uruguayan-league.png", custom: true, country: "URY"},
  {id: 783, name: "Jardim Canelones", badge: "/images/leagues/uruguayan-league.png", custom: true, country: "URY"},
  {id: 784, name: "Punta Este", badge: "/images/leagues/uruguayan-league.png", custom: true, country: "URY"},
  {id: 785, name: "Vila Libertad", badge: "/images/leagues/uruguayan-league.png", custom: true, country: "URY"},
  {id: 786, name: "Vila Montevidéu", badge: "/images/leagues/uruguayan-league.png", custom: true, country: "URY"},
  {id: 787, name: "Vila Molina", badge: "/images/leagues/uruguayan-league.png", custom: true, country: "URY"},
  {id: 788, name: "Casavalle", badge: "/images/leagues/uruguayan-league.png", custom: true, country: "URY"},
  {id: 789, name: "Allende", badge: "/images/leagues/peruvian-league.png", custom: true, country: "PER"},
  {id: 790, name: "Jardim Iolita", badge: "/images/leagues/peruvian-league.png", custom: true, country: "PER"},
  {id: 791, name: "Vila Lima", badge: "/images/leagues/peruvian-league.png", custom: true, country: "PER"},
  {id: 792, name: "Vila Maya", badge: "/images/leagues/peruvian-league.png", custom: true, country: "PER"},
  {id: 793, name: "Vila Larimar", badge: "/images/leagues/peruvian-league.png", custom: true, country: "PER"},
  {id: 794, name: "Avellana", badge: "/images/leagues/peruvian-league.png", custom: true, country: "PER"},
  {id: 795, name: "Jardim Miraflores", badge: "/images/leagues/paraguayan-league.png", custom: true, country: "PRY"},
  {id: 796, name: "Parque Assuncíon", badge: "/images/leagues/paraguayan-league.png", custom: true, country: "PRY"},
  {id: 797, name: "Vila San Bernardino", badge: "/images/leagues/paraguayan-league.png", custom: true, country: "PRY"},
  {id: 798, name: "Villarica", badge: "/images/leagues/paraguayan-league.png", custom: true, country: "PRY"},
  {id: 799, name: "Parque Guaraní", badge: "/images/leagues/paraguayan-league.png", custom: true, country: "PRY"},
  {id: 800, name: "Vila Mirtillo", badge: "/images/leagues/paraguayan-league.png", custom: true, country: "PRY"},
  {id: 801, name: "Jardim Independente", badge: "/images/leagues/venezuelan-league.png", custom: true, country: "VEN"},
  {id: 802, name: "Jardim Lázuli", badge: "/images/leagues/venezuelan-league.png", custom: true, country: "VEN"},
  {id: 803, name: "Vila Baltimore", badge: "/images/leagues/venezuelan-league.png", custom: true, country: "VEN"},
  {id: 804, name: "Vila Caracas", badge: "/images/leagues/venezuelan-league.png", custom: true, country: "VEN"},
  {id: 805, name: "Jardim Nuevo", badge: "/images/leagues/venezuelan-league.png", custom: true, country: "VEN"},
  {id: 806, name: "Vila Andaluz", badge: "/images/leagues/venezuelan-league.png", custom: true, country: "VEN"},
  {id: 807, name: "Jardim Ambatho", badge: "/images/leagues/ecuadorian-league.png", custom: true, country: "ECU"},
  {id: 808, name: "Jardim Huesca", badge: "/images/leagues/ecuadorian-league.png", custom: true, country: "ECU"},
  {id: 809, name: "Salta", badge: "/images/leagues/ecuadorian-league.png", custom: true, country: "ECU"},
  {id: 810, name: "Vila Mérida", badge: "/images/leagues/ecuadorian-league.png", custom: true, country: "ECU"},
  {id: 811, name: "Vila Central", badge: "/images/leagues/ecuadorian-league.png", custom: true, country: "ECU"},
  {id: 812, name: "Vila Cobre", badge: "/images/leagues/ecuadorian-league.png", custom: true, country: "ECU"},
  {id: 813, name: "Jardim da Prata", badge: "/images/leagues/bolivian-league.png", custom: true, country: "BOL"},
  {id: 814, name: "Vila Loretto", badge: "/images/leagues/bolivian-league.png", custom: true, country: "BOL"},
  {id: 815, name: "Vila Rúbia", badge: "/images/leagues/bolivian-league.png", custom: true, country: "BOL"},
  {id: 816, name: "Vila Hamburgo", badge: "/images/leagues/bolivian-league.png", custom: true, country: "BOL"},
  {id: 817, name: "Jardim Sierra", badge: "/images/leagues/bolivian-league.png", custom: true, country: "BOL"},
  {id: 818, name: "Vila Ouro", badge: "/images/leagues/bolivian-league.png", custom: true, country: "BOL"}]

