export default {
  themes: {
    'user-menu': {
      $extend: 'menu',
      $resetCss: true,
      arrowOverflow: false,
      placement: 'bottom-end',
      distance: 16,
      overflowPadding: 12,
    },
    'app-dropdown': {
      $extend: 'dropdown',
      $resetCss: true,
      arrowOverflow: false,
      placement: 'bottom-start',
      distance: 2,
      overflowPadding: 12,
    },
    'app-popup-large': {
      $extend: 'dropdown',
      $resetCss: true,
      arrowOverflow: false,
      placement: 'bottom-start',
      distance: 12,
      skidding: -12,
      overflowPadding: 12,
    },
    'context-menu': {
      $extend: 'dropdown',
      $resetCss: true,
      arrowOverflow: false,
      placement: 'right-start',
      distance: 8,
      overflowPadding: 12,
    },
    'popup-menu': {
      $extend: 'dropdown',
      $resetCss: true,
      arrowOverflow: false,
      placement: 'right-start',
      distance: 8,
      skidding: -102,
      overflowPadding: 12,
    },
    tooltip: {
      $resetCss: true,
      distance: 8,
      overflowPadding: 12,
    },
    'match-tooltip': {
      $extend: 'menu',
      $resetCss: true,
      arrowOverflow: false,
      distance: 8,
      placement: 'top-end',
      arrowPadding: 12,
      triggers: ['hover', 'focus'],
      delay: {
        hide: 0,
      },
    },
    'team-performance': {
      $extend: 'app-dropdown',
    },
  },
};
